// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::group::add_group_member_request::AddGroupMemberRequest;
use crate::types::group::group_member_response::GroupMemberResponse;
use crate::types::group::set_group_member_role_request::SetGroupMemberRoleRequest;

/// Add an existing user to the group with a role.
///
/// Requires `AddMembers` in the group itself, and the caller's role there must be able to manage the role being assigned; a user already in the group is a conflict, and a user who does not exist yet is invited, not added.
pub async fn add(__client: &crate::runtime::Client, group_uid: &str, __body: &AddGroupMemberRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/group/{group_uid}/member");
  __path = __path.replace("{group_uid}", &crate::runtime::encode_path(group_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// List the group's members, each carrying the identity fields that name the person behind the membership.
///
/// Requires `ViewMembers` in the group itself.
pub async fn list(__client: &crate::runtime::Client, group_uid: &str) -> crate::runtime::ApiResult<Vec<GroupMemberResponse>> {
  let mut __path = String::from("/group/{group_uid}/member");
  __path = __path.replace("{group_uid}", &crate::runtime::encode_path(group_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Remove a member from the group; the user itself and every other membership they hold are untouched.
///
/// Requires `RemoveMembers` in the group itself, and the caller's role there must be able to manage the member's current role; the caller can never remove their own membership, and a user who is not a member of this group reads as not found.
pub async fn remove(__client: &crate::runtime::Client, group_uid: &str, user_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/group/{group_uid}/member/{user_uid}");
  __path = __path.replace("{group_uid}", &crate::runtime::encode_path(group_uid));
  __path = __path.replace("{user_uid}", &crate::runtime::encode_path(user_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Replace a member's role in the group.
///
/// Requires `SetMemberRole` in the group itself, and the caller's role there must be able to manage both the role being replaced and the one replacing it; the caller can never re-role their own membership, and a user who is not a member of this group reads as not found.
pub async fn set_role(__client: &crate::runtime::Client, group_uid: &str, user_uid: &str, __body: &SetGroupMemberRoleRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/group/{group_uid}/member/{user_uid}");
  __path = __path.replace("{group_uid}", &crate::runtime::encode_path(group_uid));
  __path = __path.replace("{user_uid}", &crate::runtime::encode_path(user_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
