// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::facebook_media::FacebookMedia;

/// A Facebook Page publication. `message` is the post text / media caption /
/// video description; `place_id` tags a location (feed and photo posts only).
/// All media URLs must be publicly reachable — Meta fetches them.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
pub struct FacebookPostContent {
  pub media: FacebookMedia,
  pub message: Option<String>,
  pub place_id: Option<String>,
}
