// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::instagram_media::InstagramMedia;

/// An Instagram post. All media URLs must be publicly reachable — Meta's
/// servers fetch them. Video-backed media (reels, video stories, video
/// carousel items) process asynchronously on Meta's side.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
pub struct InstagramPostContent {
  pub media: InstagramMedia,
  pub caption: Option<String>,
  /// Instagram location id (from Meta's location search) to tag.
  pub location_id: Option<String>,
  /// Usernames invited as collaborators (public professional accounts).
  pub collaborators: Vec<String>,
}
