// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::instagram_user_tag::InstagramUserTag;

/// One carousel item: exactly one of `image_url` / `video_url`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
pub struct InstagramCarouselItem {
  pub image_url: Option<String>,
  pub video_url: Option<String>,
  pub user_tags: Vec<InstagramUserTag>,
}
