// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Messaging tags that lift the standard 24h response window (Send API `tag`
/// parameter). Only `HumanAgent` survives in 2026 (7-day window for human
/// replies; the app must hold the `human_agent` permission).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
#[serde(rename_all = "snake_case")]
pub enum MessageTag {
  HumanAgent,
}
