// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Conversation presence signals (Send API `sender_action` parameter).
/// WhatsApp rides its own read-receipt + typing-indicator call instead:
/// `mark_seen`/`typing_on` map onto it and there is no `typing_off`
/// (indicators auto-dismiss).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
#[serde(rename_all = "snake_case")]
pub enum SenderAction {
  MarkSeen,
  TypingOn,
  TypingOff,
}
