// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::whatsapp_template_button_sub_type::WhatsappTemplateButtonSubType;
use crate::types::meta::whatsapp_template_parameter::WhatsappTemplateParameter;

/// One substitution block of a template *send* — the values that fill an
/// approved template's placeholders. Serializes straight to the Cloud API
/// shape: Meta spells these lowercase already, so no boundary translation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum WhatsappTemplateSendComponent {
  Header {
    parameters: Vec<WhatsappTemplateParameter>,
  },
  Body {
    parameters: Vec<WhatsappTemplateParameter>,
  },
  /// One button's payload. `index` is the button's position (`"0"`-based) in
  /// the approved definition — Meta's own field, a string.
  Button {
    sub_type: WhatsappTemplateButtonSubType,
    index: String,
    parameters: Vec<WhatsappTemplateParameter>,
  },
}
