// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Where a template sits in Meta's review pipeline. Only `approved` is
/// sendable.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
#[serde(rename_all = "snake_case")]
pub enum WhatsappTemplateStatus {
  Approved,
  Pending,
  Rejected,
  /// Paused for poor quality; sends fail until it recovers or is edited.
  Paused,
  /// Disabled for repeated quality failures — terminal.
  Disabled,
  /// A rejection under appeal.
  InAppeal,
  PendingDeletion,
  /// A status Meta introduced after this build. Surfaced rather than dropped
  /// so the template still lists; treat as not sendable.
  Unknown,
}
