// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// What the template is for. Meta prices and rate-limits by category, and a
/// template's category is fixed at approval.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
#[serde(rename_all = "snake_case")]
pub enum WhatsappTemplateCategory {
  /// Order updates, receipts, alerts — tied to an existing transaction.
  Utility,
  /// Promotional. The most expensive tier and the easiest to get blocked.
  Marketing,
  /// One-time passcodes.
  Authentication,
  /// A category Meta introduced after this build. Surfaced rather than
  /// folded into a priced tier the template does not belong to; not
  /// submittable.
  Unknown,
}
