// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// A header's format and the payload that format carries. Media headers are
/// defined with an uploaded sample (a resumable-upload handle), not a URL —
/// the real media is supplied per send.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.meta"))]
#[serde(tag = "format")]
#[serde(rename_all = "snake_case")]
pub enum WhatsappTemplateHeader {
  Text {
    text: String,
    /// One sample per placeholder. A header takes at most one.
    example: Option<Vec<String>>,
  },
  Image {
    example: Option<Vec<String>>,
  },
  Video {
    example: Option<Vec<String>>,
  },
  Document {
    example: Option<Vec<String>>,
  },
  /// A map pin, supplied per send. Carries nothing in the definition.
  Location,
}
