// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::user_session::list_user_sessions_query::ListUserSessionsQuery;
use crate::types::user_session::user_session_login_request::UserSessionLoginRequest;
use crate::types::user_session::user_session_login_response::UserSessionLoginResponse;
use crate::types::user_session::user_session_logout_all_response::UserSessionLogoutAllResponse;
use crate::types::user_session::user_session_row::UserSessionRow;

/// List active sessions for the caller or, when a user is specified, for another user.
///
/// Any authenticated user for their own sessions; naming another user requires `ViewUserSessions`, which only platform staff hold.
pub async fn list(__client: &crate::runtime::Client, __query: &ListUserSessionsQuery) -> crate::runtime::ApiResult<Vec<UserSessionRow>> {
  let mut __path = String::from("/user-session");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Authenticate with email and password, returning a session token or an MFA/enrollment challenge.
///
/// Public — no authentication required; the caller proves identity with the supplied email and password.
pub async fn login(__client: &crate::runtime::Client, __body: &UserSessionLoginRequest) -> crate::runtime::ApiResult<UserSessionLoginResponse> {
  let mut __path = String::from("/user-session/login");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Invalidate the caller's current session and clear the session cookie.
///
/// Authenticated user acting on their own session; no permission required.
pub async fn logout(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/user-session/logout");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Invalidate all of the caller's sessions and clear the session cookie.
///
/// Authenticated user acting on their own sessions; no permission required.
pub async fn logout_all(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<UserSessionLogoutAllResponse> {
  let mut __path = String::from("/user-session/logout-all");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Revoke a single session by its identifier.
///
/// Any authenticated user for their own sessions; revoking another user's session requires `RevokeUserSessions`, which only platform staff hold.
pub async fn revoke(__client: &crate::runtime::Client, session_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/user-session/{session_uid}");
  __path = __path.replace("{session_uid}", &crate::runtime::encode_path(session_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
