// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::social_account::account_insights_query::AccountInsightsQuery;
use crate::types::social_account::connect_callback_query::ConnectCallbackQuery;
use crate::types::social_account::connect_confirm_request::ConnectConfirmRequest;
use crate::types::social_account::connect_native_request::ConnectNativeRequest;
use crate::types::social_account::connect_review_query::ConnectReviewQuery;
use crate::types::social_account::connect_review_response::ConnectReviewResponse;
use crate::types::social_account::connect_social_account_request::ConnectSocialAccountRequest;
use crate::types::social_account::connect_social_account_response::ConnectSocialAccountResponse;
use crate::types::social_account::connect_social_accounts_connected::ConnectSocialAccountsConnected;
use crate::types::social_account::connect_stevo_request::ConnectStevoRequest;
use crate::types::social_account::connect_stevo_response::ConnectStevoResponse;
use crate::types::social_account::connect_whatsapp_request::ConnectWhatsappRequest;
use crate::types::social_account::connect_whatsapp_response::ConnectWhatsappResponse;
use crate::types::social_account::exposure_query::ExposureQuery;
use crate::types::domain::exposure_report::ExposureReport;
use crate::types::meta::insight::Insight;
use crate::types::insight::insight_history_query::InsightHistoryQuery;
use crate::types::insight::insight_series::InsightSeries;
use crate::types::social_account::list_social_accounts_query::ListSocialAccountsQuery;
use crate::types::social_account::native_pairing_status_response::NativePairingStatusResponse;
use crate::types::social_account::native_qr_response::NativeQrResponse;
use crate::types::social_account::refresh_profile_response::RefreshProfileResponse;
use crate::types::social_account::session_status::SessionStatus;
use crate::types::social_account::set_social_account_alias_request::SetSocialAccountAliasRequest;
use crate::types::social_account::set_social_account_conversation_cap_request::SetSocialAccountConversationCapRequest;
use crate::types::social_account::set_social_account_enabled_request::SetSocialAccountEnabledRequest;
use crate::types::social_account::set_social_account_presence_request::SetSocialAccountPresenceRequest;
use crate::types::social_account::social_account_response::SocialAccountResponse;
use crate::types::social_account::start_native_pairing_response::StartNativePairingResponse;
use crate::types::social_account::stevo_pair_request::StevoPairRequest;
use crate::types::social_account::stevo_pair_response::StevoPairResponse;
use crate::types::social_account::stevo_qr_response::StevoQrResponse;
use crate::types::social_account::stevo_status_response::StevoStatusResponse;

/// Meta OAuth redirect target: consumes the state, exchanges the code, and
/// stashes the grant snapshot for review — nothing is registered yet; always
/// redirects the browser back to the frontend, with a review token on
/// success.
///
/// Public — no authentication required; authorization comes from the one-shot state token issued by `socialAccount.connect`.
pub async fn callback(__client: &crate::runtime::Client, __query: &ConnectCallbackQuery) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/callback");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Start the Meta OAuth flow for a group, returning the login dialog URL. The
/// callback stashes the granted pages (and linked Instagram accounts) for
/// review; `socialAccount.connectConfirm` is what registers the selection.
///
/// Requires `ConnectSocialAccounts` in the named group.
pub async fn connect(__client: &crate::runtime::Client, __body: &ConnectSocialAccountRequest) -> crate::runtime::ApiResult<ConnectSocialAccountResponse> {
  let mut __path = String::from("/social-account/connect");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Register the selected accounts from a stashed grant (one-shot). Pages and
/// instagram accounts are selected independently; unselected accounts stay in
/// the Meta grant but out of the hub.
///
/// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
pub async fn connect_confirm(__client: &crate::runtime::Client, __body: &ConnectConfirmRequest) -> crate::runtime::ApiResult<ConnectSocialAccountsConnected> {
  let mut __path = String::from("/social-account/connect/confirm");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Load a stashed Meta grant for the selection screen: every account it
/// covers, plus group accounts whose stored token died on the Meta side
/// (access removed) — those are flagged for reauthorization. Repeatable;
/// only confirm consumes the stash.
///
/// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
pub async fn connect_review(__client: &crate::runtime::Client, __query: &ConnectReviewQuery) -> crate::runtime::ApiResult<ConnectReviewResponse> {
  let mut __path = String::from("/social-account/connect/review");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Connect a Stevo instance (unofficial WhatsApp gateway) to a group: the hub
/// validates the server + apikey and registers the account. The webhook must
/// be set manually in the Stevo panel. Pair the phone afterwards via the
/// `stevo/qr` or `stevo/pair` sub-routes.
///
/// Requires `ConnectSocialAccounts` in the named group.
pub async fn connect_stevo(__client: &crate::runtime::Client, __body: &ConnectStevoRequest) -> crate::runtime::ApiResult<ConnectStevoResponse> {
  let mut __path = String::from("/social-account/stevo");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Connect a WhatsApp Business Account to a group by manual provisioning: the
/// hub discovers the WABA's phone numbers with the supplied permanent token,
/// subscribes webhooks, and registers one social account per number.
///
/// Requires `ConnectSocialAccounts` in the named group.
pub async fn connect_whatsapp(__client: &crate::runtime::Client, __body: &ConnectWhatsappRequest) -> crate::runtime::ApiResult<ConnectWhatsappResponse> {
  let mut __path = String::from("/social-account/whatsapp");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Count connected social accounts, optionally filtered by group.
///
/// Requires `ViewSocialAccounts`; the count covers only accounts of groups where the caller holds it.
pub async fn count(__client: &crate::runtime::Client, __query: &ListSocialAccountsQuery) -> crate::runtime::ApiResult<u64> {
  let mut __path = String::from("/social-account/count");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Disconnect a social account, deleting its conversations, messages, and
/// posts with it. Native whatsapp accounts also unpair the phone
/// (best-effort, in the background).
///
/// Requires `DeleteSocialAccounts` in the account's group.
pub async fn delete(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Read the account's exposure telemetry, hour by hour over the requested
/// period (at most 92 days): how many platform lookups it made (usync number
/// checks, profile pictures, presence subscriptions), its sends by origin,
/// first-time contacts, whatsapp 429 and 463/475 answers, slow send acks and
/// sends still without a delivery receipt an hour later, plus the alerts the
/// last 24 hours raise right now. Only the session-backed whatsapp channels
/// are metered.
///
/// Requires `ViewSocialAccounts` in the account's group.
pub async fn exposure(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ExposureQuery) -> crate::runtime::ApiResult<ExposureReport> {
  let mut __path = String::from("/social-account/{social_account_uid}/exposure");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Fetch a single connected social account by uid, with the live session
/// status of its whatsapp session when applicable.
///
/// Requires `ViewSocialAccounts` in the account's group.
pub async fn get(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<SocialAccountResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Fetch platform metrics for a facebook page or instagram professional
/// account (the per-channel defaults, or a caller-supplied
/// `metrics`/`period`/`metric_type`). No whatsapp flavor exposes insights.
///
/// Requires `ViewInsights` in the account's group.
pub async fn insights(__client: &crate::runtime::Client, social_account_uid: &str, __query: &AccountInsightsQuery) -> crate::runtime::ApiResult<Vec<Insight>> {
  let mut __path = String::from("/social-account/{social_account_uid}/insight");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Day-by-day history of the account's collected metrics (reach, views,
/// follower counts, …), grouped per metric — the charting companion to the
/// live insights passthrough. History exists only from the day the account
/// was connected. A channel that reports no insights is refused here exactly
/// as the live endpoint refuses it.
///
/// Requires `ViewInsights` in the account's group.
pub async fn insights_history(__client: &crate::runtime::Client, social_account_uid: &str, __query: &InsightHistoryQuery) -> crate::runtime::ApiResult<Vec<InsightSeries>> {
  let mut __path = String::from("/social-account/{social_account_uid}/insight/history");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List connected social accounts, optionally filtered by group, each with the
/// live session status of its whatsapp session when applicable.
///
/// Requires `ViewSocialAccounts`; the list covers only accounts of groups where the caller holds it.
pub async fn list(__client: &crate::runtime::Client, __query: &ListSocialAccountsQuery) -> crate::runtime::ApiResult<Vec<SocialAccountResponse>> {
  let mut __path = String::from("/social-account");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Close the account's session without unpairing the phone; conflicts if the
/// phone already unpaired.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn native_disconnect(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/native/disconnect");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Unpair the phone entirely (logout); re-pairing needs a new QR scan;
/// conflicts if the phone already unpaired.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn native_logout(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/native/session");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Poll a pairing's outcome; stop polling once `status` leaves `pairing`.
///
/// Requires `ConnectSocialAccounts` in the group the pairing targets.
pub async fn native_pairing_status(__client: &crate::runtime::Client, pairing_handle: &str) -> crate::runtime::ApiResult<NativePairingStatusResponse> {
  let mut __path = String::from("/social-account-pairing/{pairing_handle}/status");
  __path = __path.replace("{pairing_handle}", &crate::runtime::encode_path(pairing_handle));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// The current pairing QR to render (null until the first code arrives).
///
/// Requires `ConnectSocialAccounts` in the group the pairing targets.
pub async fn native_qr(__client: &crate::runtime::Client, pairing_handle: &str) -> crate::runtime::ApiResult<NativeQrResponse> {
  let mut __path = String::from("/social-account-pairing/{pairing_handle}/qr");
  __path = __path.replace("{pairing_handle}", &crate::runtime::encode_path(pairing_handle));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Re-establish the account's session after a drop; conflicts if the phone
/// unpaired (re-pair with a new QR instead) or while a whatsapp ban on the
/// number is still in force, since logging back in during a ban lengthens it.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn native_reconnect(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/native/reconnect");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Live session status of a native account; a phone-side unpair reports
/// `unpaired` instead of an error.
///
/// Requires `ViewSocialAccounts` in the account's group.
pub async fn native_status(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<SessionStatus> {
  let mut __path = String::from("/social-account/{social_account_uid}/native/status");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Re-read this account's name and picture from its platform now, rather than
/// waiting for the daily sweep. Answers `true` when something actually changed.
///
/// Never touches the alias — that is yours, and a platform rename is exactly
/// what it is meant to survive.
///
/// Requires `UpdateSocialAccounts` in the account's group.
pub async fn refresh_profile(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<RefreshProfileResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}/profile/refresh");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Set or clear an operator's own label for a connected account, on any
/// channel. The account's `name` is the platform's and is refreshed from it —
/// this is the field a team controls, for telling apart several accounts that
/// the platform names alike. Clearing it leaves the platform name alone.
///
/// Requires `UpdateSocialAccounts` in the account's group.
pub async fn set_alias(__client: &crate::runtime::Client, social_account_uid: &str, __body: &SetSocialAccountAliasRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/alias");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Cap how many conversations the hub may open on this account in any 24
/// hours, whoever asks for them (inbox, api key, campaign, import, GoHighLevel),
/// or lift the cap with `null`. Only the session-backed whatsapp channels enforce
/// it; other channels are refused.
///
/// Requires `UpdateSocialAccounts` in the account's group.
pub async fn set_conversation_cap(__client: &crate::runtime::Client, social_account_uid: &str, __body: &SetSocialAccountConversationCapRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/conversation-cap");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Enable or disable a connected social account; disabled accounts stop
/// ingesting webhooks and reject sends/publishes. Enabling clears a session
/// incident the next connect would clear anyway, leaves a reach-out hold to
/// expire on its own, and conflicts while a whatsapp ban is still in force. Disabling a native whatsapp account also
/// disconnects its session, and enabling connects it again.
///
/// Requires `UpdateSocialAccounts` in the account's group.
pub async fn set_enabled(__client: &crate::runtime::Client, social_account_uid: &str, __body: &SetSocialAccountEnabledRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/enabled");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Choose how this native whatsapp account announces itself online: following
/// the operators looking at its inbox (the default) or never. Takes effect on
/// the live session at once. One change per account every 30 seconds; a
/// sooner one is refused with the seconds left. Other channels have no
/// presence to steer and are refused.
///
/// Requires `UpdateSocialAccounts` in the account's group.
pub async fn set_presence(__client: &crate::runtime::Client, social_account_uid: &str, __body: &SetSocialAccountPresenceRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/presence");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Start a native (whatsmeow) pairing; returns a handle to poll for the QR and
/// the paired account. The account row is created only when the scan succeeds.
///
/// Requires `ConnectSocialAccounts` in the named group.
pub async fn start_native_pairing(__client: &crate::runtime::Client, __body: &ConnectNativeRequest) -> crate::runtime::ApiResult<StartNativePairingResponse> {
  let mut __path = String::from("/social-account/native");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Close the instance's session without unpairing the phone. Temporarily
/// disabled — always fails with 503.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn stevo_disconnect(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/stevo/disconnect");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Unpair the phone entirely (logout); re-pairing needs a new QR scan.
/// Temporarily disabled — always fails with 503.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn stevo_logout(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/stevo/session");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Start QR-less pairing: returns the code the user types under "link with
/// phone number" on the device. Temporarily disabled — always fails with 503.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn stevo_pair(__client: &crate::runtime::Client, social_account_uid: &str, __body: &StevoPairRequest) -> crate::runtime::ApiResult<StevoPairResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}/stevo/pair");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Fetch the instance's pairing QR code to render for the admin (valid while
/// the instance is connected but not yet logged in). Temporarily disabled —
/// always fails with 503.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn stevo_qr(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<StevoQrResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}/stevo/qr");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Re-establish the instance's session after a drop; conflicts while a
/// whatsapp ban on the number is still in force, since logging back in
/// during a ban lengthens it. Temporarily disabled — always fails with 503.
///
/// Requires `ConnectSocialAccounts` in the account's group.
pub async fn stevo_reconnect(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/stevo/reconnect");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Live connection status of the instance (connected = session up; logged_in
/// = phone paired). Reading it also refreshes the account's stored name from
/// the paired profile when it changed (the picture follows the daily profile
/// sweep, which asks for it only once the gateway has echoed the account's
/// own number), and reads the gateway's health report: a reported reach-out
/// hold records a `reachout_timelock` session incident on the account, and its
/// lifting clears it. Both emit `account_updated` — the poll is the natural
/// refresh point, since it already runs whenever the panel is open.
///
/// Requires `ViewSocialAccounts` in the account's group.
pub async fn stevo_status(__client: &crate::runtime::Client, social_account_uid: &str) -> crate::runtime::ApiResult<StevoStatusResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}/stevo/status");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
