// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// The three video verbs a call carries, which are not interchangeable:
/// `Start` sends an upgrade *request* and holds our video until the peer
/// accepts, `Accept` answers the peer's request, and `Stop` withdraws video
/// entirely. Turning the camera on and off inside an already-video call is not
/// one of them — that is an ungated toggle, since no handshake is owed.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum CallVideoAction {
  Start,
  Accept,
  Stop,
}
