// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// One recipient's outcome. `Sent` means the message entered the send queue —
/// the platform's own verdict (delivered, read, failed) lives on the message
/// row the recipient points at, never copied here.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum CampaignRecipientStatus {
  /// Queued; the dispatcher has not reached it.
  Pending,
  /// Handed to the send queue; `message_uid` names the message.
  Sent,
  /// The send could not be enqueued (account refused, payload invalid).
  Failed,
  /// A safety rail ruled it out; `skip_reason` names which.
  Skipped,
  /// Canceled with the campaign before dispatch. Terminal.
  Canceled,
}
