// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum EmailQueueStatus {
  Pending,
  /// Claimed by the worker and handed to SMTP. The row is out of the queue's
  /// candidate set while it is in flight; a process that dies mid-send leaves
  /// it here, and the startup sweep returns it to `Pending`.
  Sending,
  Sent,
  Failed,
}
