// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Tags a queued email so the worker can update the originating record on
/// completion (e.g. flip an `user_invite.email_status` to Sent/Failed).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum EmailKind {
  Other,
  UserInvite,
  UserPasswordReset,
}
