// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Who produced an outbound message row — the attribution consumers (CRMs)
/// use to tell machine sends from human takeovers without correlation
/// heuristics. `None` on inbound rows and on rows stored before the field
/// existed.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum MessageSentBy {
  /// Sent through the hub API by a machine client (a CRM's key).
  ApiKey,
  /// Sent by a hub operator (frontend session).
  User,
  /// Echo ingested from the platform — the paired phone, whatsapp web, the
  /// Meta business inbox — or imported history.
  Platform,
  /// Sent by a linked GoHighLevel location through the conversation-provider
  /// delivery webhook.
  Ghl,
}
