// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::facebook_post_content::FacebookPostContent;
use crate::types::meta::instagram_post_content::InstagramPostContent;

/// Channel-tagged post payload: publishing surfaces genuinely differ per
/// platform, so the variants carry channel-specific fields while the API
/// stays a single endpoint distinguished by the `channel` tag.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum PostContent {
  Facebook(FacebookPostContent),
  Instagram(InstagramPostContent),
}
