// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Every kind of account the hub connects — the account registry's axis.
/// Distinct from [`Channel`], which is the *messaging-domain* discriminator
/// carried by conversations, messages, and posts: every messaging provider
/// projects onto a channel, while non-messaging providers (calendar) have
/// none — so messaging payloads can never name them.
///
/// Adding an integration = a variant here + its connect flow + its
/// capability module; the registry (table, CRUD, listing UI) is shared.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum Provider {
  Facebook,
  Instagram,
  /// WhatsApp Business Platform (official Meta Cloud API).
  Whatsapp,
  /// WhatsApp via a StevoManager v2 instance (unofficial gateway).
  WhatsappStevo,
  /// WhatsApp via an in-process whatsmeow linked-device session (unofficial).
  WhatsappNative,
  /// A Google account (per-account OAuth). Which surfaces it reaches —
  /// calendar today, business profile ahead — is decided by the scopes the
  /// grant carries, not by the provider.
  Google,
}
