// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::email::Email;
use crate::types::types::message_search_hit::MessageSearchHit;
use crate::types::primitives::name::Name;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum SearchHitKind {
  Group {
    uid: Uid,
    name: Name,
  },
  User {
    uid: Uid,
    name: Name,
    email: Email,
  },
  /// A conversation matched by its participant's alias, name, username or
  /// phone. `name` is the best one known, alias first.
  Conversation {
    uid: Uid,
    social_account_uid: Uid,
    name: Option<String>,
    participant_id: String,
    participant_avatar_url: Option<String>,
  },
  Message(MessageSearchHit),
}
