// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Why a session-backed whatsapp account (native/stevo) last stopped working.
///
/// [`crate::channel::Channel`]-agnostic, and split by what an operator has to
/// *do* about it — which is why the three terminal cases are separate variants
/// rather than one "logged out". The platform reports them as three different
/// codes and they call for three different responses: re-pair, wait, or give up
/// on the number. Collapsing them would throw away the one thing that tells
/// them apart.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(rename_all = "snake_case")]
pub enum SessionIncidentKind {
  /// The platform temporarily banned the account (connect failure 402).
  /// Sending is halted and the account disabled;
  /// `session_incident_expires_at` carries when the ban lifts and
  /// `session_incident_ban_reason` which behaviour caused it.
  TemporaryBan,
  /// The platform banned the account for good (connect failure 406, "BANNED"
  /// in whatsapp web's own code). Terminal: the session store is gone and the
  /// number itself is spent — re-pairing it is not a recovery.
  Banned,
  /// The phone unlinked this device (stream error 401, or connect failure
  /// 401). The session is gone, but the number is fine: a fresh pairing with
  /// the same number restores the account and its history.
  LoggedOut,
  /// The primary device is gone or locked (connect failure 403). The
  /// companion cannot outlive it; recovery starts on the phone.
  MainDeviceGone,
  /// The platform refused this client version (connect failure 405). Not the
  /// account's fault and not fixable by the operator: the bridge has to be
  /// updated and redeployed.
  ClientOutdated,
  /// Another client took the session over. Whoever connected last owns it;
  /// nothing here reconnects, since fighting for it would loop.
  StreamReplaced,
  /// The platform refused the connection for some other reason.
  ConnectFailure,
  /// A protocol error this build does not model. Recorded rather than dropped
  /// precisely because it is the unknown-unknowns channel: a failure mode
  /// whatsapp introduces after this build shows up here or nowhere.
  StreamError,
}
