// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// A button on a structured message. `Url` opens the link; `Postback` sends
/// the payload back as an [`InboundContent::Postback`] message.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.types"))]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum TemplateButton {
  Url {
    title: String,
    url: String,
  },
  Postback {
    title: String,
    payload: String,
  },
}
