// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct AccountInsightsQuery {
  /// Meta metric names (comma-separated); defaults per channel. Metrics of a
  /// single `metric_type` only — Meta rejects a mixed list.
  pub metrics: Option<String>,
  /// day / week / days_28 — defaults to day.
  pub period: Option<String>,
  /// `total_value` for metrics Meta only reports as a total; omit for
  /// time-series ones. Only read alongside `metrics`.
  pub metric_type: Option<String>,
}
