// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct ConnectWhatsappRequest {
  pub group_uid: Uid,
  /// The WhatsApp Business Account id (from Business Manager).
  pub waba_id: String,
  /// A permanent system user token holding `whatsapp_business_messaging` +
  /// `whatsapp_business_management`, generated once in Business Manager.
  pub access_token: String,
}
