// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::instagram_login::InstagramLogin;
use crate::types::primitives::uid::Uid;

/// Which login opens the grant: the hub's own Meta app (every page and linked
/// instagram account the admin grants, reviewed together) or the alternate
/// gateway's, one channel per grant while the hub's app awaits review. An
/// instagram grant also names its dialog: Instagram Login needs no Facebook
/// Page, Facebook Login needs the account linked to one. A login may name the
/// group's account it reconnects, so the grant lands on that account and
/// refreshes it in place; otherwise every selected account is registered
/// anew, however many times the same page or number is already connected —
/// each connection is its own account, sharing nothing with the others.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
#[serde(tag = "login")]
#[serde(rename_all = "snake_case")]
pub enum ConnectSocialAccountRequest {
  Meta {
    group_uid: Uid,
    /// The group's official facebook or instagram account this login
    /// reconnects, if any.
    social_account_uid: Option<Uid>,
  },
  FacebookAlt {
    group_uid: Uid,
    /// The group's alt account this login reconnects, if any.
    social_account_uid: Option<Uid>,
  },
  InstagramAlt {
    group_uid: Uid,
    method: InstagramLogin,
    /// The group's alt account this login reconnects, if any.
    social_account_uid: Option<Uid>,
  },
  WhatsappAlt {
    group_uid: Uid,
    /// The group's alt account this login reconnects, if any.
    social_account_uid: Option<Uid>,
  },
}
