// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// What the login's redirect carries back: the hub's one-shot `state`, then
/// Meta's `code`/`error` or the alternate gateway's selection state in its
/// own spelling.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct ConnectCallbackQuery {
  pub state: Option<String>,
  pub code: Option<String>,
  pub error: Option<String>,
  pub error_description: Option<String>,
  pub platform: Option<String>,
  #[serde(rename = "profileId")]
  pub profile_id: Option<String>,
  #[serde(rename = "tempToken")]
  pub temp_token: Option<String>,
  pub step: Option<String>,
  #[serde(rename = "accountId")]
  pub account_id: Option<String>,
  pub connect_token: Option<String>,
  #[serde(rename = "userProfile")]
  pub user_profile: Option<String>,
}
