// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::social_account::grant_account::GrantAccount;
use crate::types::social_account::removed_access::RemovedAccess;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct ConnectReviewResponse {
  /// Every account the grant covers, facebook pages and their linked
  /// instagram accounts alike.
  pub accounts: Vec<GrantAccount>,
  /// Group accounts whose access died on the Meta side.
  pub removed: Vec<RemovedAccess>,
}
