// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::channel::Channel;

/// One account the stashed grant covers, for the selection screen.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct GrantAccount {
  pub channel: Channel,
  pub external_id: String,
  pub name: String,
  pub username: Option<String>,
  /// How many accounts of this identity the target group already holds;
  /// confirming adds another, independent one, unless the login named the
  /// account it reconnects.
  pub connections: u32,
}
