// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::channel::Channel;

/// One account the stashed grant covers, for the selection screen.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct GrantAccount {
  pub channel: Channel,
  pub external_id: String,
  pub name: String,
  pub username: Option<String>,
  /// Already registered in the target group — confirming it refreshes the
  /// stored token and display fields.
  pub connected: bool,
  /// Registered in another group: shown locked, never selectable (accounts
  /// cannot be moved between groups by a connect).
  pub other_group: bool,
}
