// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::instagram_login::InstagramLogin;
use crate::types::primitives::uid::Uid;

/// What an alternate instagram login lands on. A new connect names its
/// dialog: Instagram Login needs no Facebook Page, Facebook Login needs the
/// account linked to one. A reconnect opens the dialog the account was
/// connected through.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum InstagramAltTarget {
  New {
    method: InstagramLogin,
  },
  Reconnect {
    /// The group's alt account this login reconnects.
    social_account_uid: Uid,
  },
}
