// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Progress of a native QR pairing.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
#[serde(rename_all = "snake_case")]
pub enum NativePairingStatus {
  /// Waiting for the phone to scan the QR (poll `native/qr`).
  Pairing,
  /// Paired; `social_account_uid` is set.
  Paired,
  /// Failed or timed out — start a new pairing.
  Failed,
}
