// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::channel::Channel;
use crate::types::primitives::uid::Uid;

/// A group account whose stored token no longer works — access was removed
/// on the Meta side. Flagged `needs_reauth`; a connect naming it by
/// `social_account_uid` is the cure.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct RemovedAccess {
  pub social_account_uid: Uid,
  pub channel: Channel,
  pub name: String,
}
