// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_100000::Number1_100000;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.social_account"))]
pub struct SetSocialAccountConversationCapRequest {
  /// Most conversations the hub may open on the account in any 24 hours;
  /// `null` lifts the cap.
  pub cap: Option<Number1_100000>,
}
