// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::email::Email;
use crate::types::domain::membership_role::MembershipRole;
use crate::types::primitives::name::Name;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user_invite"))]
pub struct UserInviteDetailResponse {
  pub email: Email,
  pub group_uid: Uid,
  pub group_name: Name,
  /// The group's logo at a signed address the invited account may fetch
  /// before it holds `ViewGroups`; valid for 30 minutes from this answer.
  pub logo_url: Option<String>,
  pub role: MembershipRole,
  pub invited_by_name: Name,
  pub expires_at: Timestamp,
}
