// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::password8_128__f__f__t__f::Password8_128_F_F_T_F;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user_invite"))]
pub struct UserInviteAcceptRequest {
  pub token: Uid,
  pub password: Password8_128_F_F_T_F,
}
