// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};

/// Stevo webhook receiver: authenticates the delivery by the echoed instance
/// token, stores normalized messages (deduplicating redeliveries), applies
/// receipts/reactions/edits/revokes, and enqueues CRM fan-out events.
///
/// Public — no authentication required; authorization comes from the instance token echoed inside the payload.
pub async fn receive(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/webhook/stevo");
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
