// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_100::Number1_100;
use crate::types::primitives::text0_8000::Text0_8000;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.search"))]
pub struct MessageSearchQuery {
  pub q: Text0_8000,
  pub group_uid: Option<Uid>,
  pub social_account_uid: Option<Uid>,
  /// Search inside this conversation only.
  pub conversation_uid: Option<Uid>,
  /// Keyset cursor: only hits with `id` strictly smaller are returned.
  pub before_id: Option<u64>,
  pub limit: Option<Number1_100>,
}
