// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::google_account::calendar_event_query::CalendarEventQuery;
use crate::types::google::calendar_page::CalendarPage;
use crate::types::google::event::Event;
use crate::types::google::event_input::EventInput;
use crate::types::google::event_page::EventPage;
use crate::types::google_account::free_busy_request::FreeBusyRequest;
use crate::types::google_account::free_busy_response::FreeBusyResponse;
use crate::types::google_account::list_calendar_events_query::ListCalendarEventsQuery;
use crate::types::google_account::list_calendars_query::ListCalendarsQuery;

/// Create an event on a calendar the account can write to.
///
/// Requires `ManageCalendars` in the account's group.
pub async fn create_event(__client: &crate::runtime::Client, social_account_uid: &str, __query: &CalendarEventQuery, __body: &EventInput) -> crate::runtime::ApiResult<Event> {
  let mut __path = String::from("/calendar/{social_account_uid}/event");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, Some(__query), Some(__body)).await
}
/// Delete (cancel) an event; deleting an already-cancelled event succeeds.
///
/// Requires `ManageCalendars` in the account's group.
pub async fn delete_event(__client: &crate::runtime::Client, social_account_uid: &str, event_id: &str, __query: &CalendarEventQuery) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/calendar/{social_account_uid}/event/{event_id}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{event_id}", &crate::runtime::encode_path(event_id));
  __client.request(crate::runtime::Method::DELETE, &__path, Some(__query), None::<&()>).await
}
/// Busy intervals for a set of calendars within a time range. A calendar
/// that cannot be read carries an `error` — never treat it as free.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn free_busy(__client: &crate::runtime::Client, social_account_uid: &str, __body: &FreeBusyRequest) -> crate::runtime::ApiResult<FreeBusyResponse> {
  let mut __path = String::from("/calendar/{social_account_uid}/freebusy");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Get one event.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn get_event(__client: &crate::runtime::Client, social_account_uid: &str, event_id: &str, __query: &CalendarEventQuery) -> crate::runtime::ApiResult<Event> {
  let mut __path = String::from("/calendar/{social_account_uid}/event/{event_id}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{event_id}", &crate::runtime::encode_path(event_id));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List the calendars the account can see — for pickers. Follow
/// `next_page_token` for more.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn list_calendars(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListCalendarsQuery) -> crate::runtime::ApiResult<CalendarPage> {
  let mut __path = String::from("/calendar/{social_account_uid}/calendar");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List a calendar's events within a time range, expanded to single
/// instances and ordered by start. Follow `next_page_token` for more.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn list_events(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListCalendarEventsQuery) -> crate::runtime::ApiResult<EventPage> {
  let mut __path = String::from("/calendar/{social_account_uid}/event");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Patch an event: only the fields sent are changed — an omitted field is
/// kept, never cleared.
///
/// Requires `ManageCalendars` in the account's group.
pub async fn update_event(__client: &crate::runtime::Client, social_account_uid: &str, event_id: &str, __query: &CalendarEventQuery, __body: &EventInput) -> crate::runtime::ApiResult<Event> {
  let mut __path = String::from("/calendar/{social_account_uid}/event/{event_id}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{event_id}", &crate::runtime::encode_path(event_id));
  __client.request(crate::runtime::Method::PATCH, &__path, Some(__query), Some(__body)).await
}
