// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::google_account::calendar_event_query::CalendarEventQuery;
use crate::types::google::calendar_page::CalendarPage;
use crate::types::google::event::Event;
use crate::types::google::event_input::EventInput;
use crate::types::google::event_page::EventPage;
use crate::types::google_account::free_busy_request::FreeBusyRequest;
use crate::types::google_account::free_busy_response::FreeBusyResponse;
use crate::types::google_account::list_calendar_events_query::ListCalendarEventsQuery;
use crate::types::google_account::list_calendars_query::ListCalendarsQuery;

/// Create an event on a calendar the account can write to.
///
/// Requires `ManageCalendars` in the account's group.
pub async fn create_event(client: &Client, social_account_uid: &str, query: &CalendarEventQuery, body: &EventInput) -> ApiResult<Event> {
  let mut __path = String::from("/calendar/{social_account_uid}/event");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  client.request(Method::POST, &__path, Some(query), Some(body)).await
}
/// Delete (cancel) an event; deleting an already-cancelled event succeeds.
///
/// Requires `ManageCalendars` in the account's group.
pub async fn delete_event(client: &Client, social_account_uid: &str, event_id: &str, query: &CalendarEventQuery) -> ApiResult<()> {
  let mut __path = String::from("/calendar/{social_account_uid}/event/{event_id}");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{event_id}", &encode_path(event_id));
  client.request(Method::DELETE, &__path, Some(query), None::<&()>).await
}
/// Busy intervals for a set of calendars within a time range. A calendar
/// that cannot be read carries an `error` — never treat it as free.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn free_busy(client: &Client, social_account_uid: &str, body: &FreeBusyRequest) -> ApiResult<FreeBusyResponse> {
  let mut __path = String::from("/calendar/{social_account_uid}/freebusy");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Get one event.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn get_event(client: &Client, social_account_uid: &str, event_id: &str, query: &CalendarEventQuery) -> ApiResult<Event> {
  let mut __path = String::from("/calendar/{social_account_uid}/event/{event_id}");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{event_id}", &encode_path(event_id));
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// List the calendars the account can see — for pickers. Follow
/// `next_page_token` for more.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn list_calendars(client: &Client, social_account_uid: &str, query: &ListCalendarsQuery) -> ApiResult<CalendarPage> {
  let mut __path = String::from("/calendar/{social_account_uid}/calendar");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// List a calendar's events within a time range, expanded to single
/// instances and ordered by start. Follow `next_page_token` for more.
///
/// Requires `ViewCalendars` in the account's group.
pub async fn list_events(client: &Client, social_account_uid: &str, query: &ListCalendarEventsQuery) -> ApiResult<EventPage> {
  let mut __path = String::from("/calendar/{social_account_uid}/event");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Patch an event: only the fields sent are changed — an omitted field is
/// kept, never cleared.
///
/// Requires `ManageCalendars` in the account's group.
pub async fn update_event(client: &Client, social_account_uid: &str, event_id: &str, query: &CalendarEventQuery, body: &EventInput) -> ApiResult<Event> {
  let mut __path = String::from("/calendar/{social_account_uid}/event/{event_id}");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{event_id}", &encode_path(event_id));
  client.request(Method::PATCH, &__path, Some(query), Some(body)).await
}
