// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.oauth_server"))]
pub struct ApproveResponse {
  /// The client's redirect uri with the code (and state) appended; the page navigates there.
  pub redirect_to: String,
}
