// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::engagement::comment_create::CommentCreate;

/// Channel-tagged top-level comment: only facebook and instagram carry a
/// comment surface, so no other channel's shape deserializes. The `channel`
/// must match the account's.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.engagement"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum CreateCommentRequest {
  Facebook(CommentCreate),
  Instagram(CommentCreate),
}
