// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.engagement"))]
pub struct CreateCommentRequest {
  /// Platform post/media id — hub posts expose it as `external_id`, and any
  /// other post of the account works too.
  pub external_post_id: String,
  pub message: String,
}
