// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_500::Number1_500;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.engagement"))]
pub struct ListCommentsQuery {
  /// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
  pub group_uids: Option<Vec<Uid>>,
  /// Narrow to these accounts, each one in scope; naming any account overrides the groups.
  pub social_account_uids: Option<Vec<Uid>>,
  /// Filter to one post's comments (platform post/media id).
  pub external_post_id: Option<String>,
  /// Poll cursor: only comments with `id` strictly greater are returned.
  pub since_id: u64,
  pub limit: Option<Number1_500>,
}
