// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.engagement"))]
pub struct PrivateReplyResponse {
  /// Platform message id; the DM itself lands in the conversation via the
  /// echo webhook.
  pub mid: String,
  /// The conversation the reply opened, when the hub can name it: on the
  /// official channels the platform returns the recipient; on the gateway
  /// channels it is the commenter's existing conversation by username.
  /// `null` until the platform's echo creates it.
  pub conversation_uid: Option<Uid>,
}
