// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_100000::Number1_100000;
use crate::types::primitives::number1_3600::Number1_3600;
use crate::types::types::rate_limit_action::RateLimitAction;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct ActionRateLimitRule {
  pub uid: Uid,
  pub action: RateLimitAction,
  pub max_requests: Number1_100000,
  pub window_seconds: Number1_3600,
  pub created_at: Timestamp,
  pub updated_at: Timestamp,
}
