// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::database::api_key_permissions::ApiKeyPermissions;
use crate::types::primitives::name::Name;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct ApiKey {
  pub uid: Uid,
  pub group_uid: Option<Uid>,
  pub name: Name,
  pub permissions: ApiKeyPermissions,
  pub enabled: bool,
  pub created_by: Uid,
  pub revoked_at: Option<Timestamp>,
  pub revoked_by: Option<Uid>,
  pub created_at: Timestamp,
  pub updated_at: Timestamp,
}
