// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::audit_action::AuditAction;
use crate::types::types::audit_resource::AuditResource;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct AuditLog {
  pub user_uid: Option<Uid>,
  pub api_key_uid: Option<Uid>,
  pub group_uid: Option<Uid>,
  pub action: AuditAction,
  pub resource: AuditResource,
  pub resource_uid: String,
  pub success: bool,
  pub details: String,
  pub socket_addr: String,
  pub recorded_at: Timestamp,
}
