// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::call_direction::CallDirection;
use crate::types::types::call_outcome::CallOutcome;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// One WhatsApp voice or video call, from the moment it rings (or is placed)
/// until the platform says it ended. A live call has `ended_at` and `outcome`
/// null; both are stamped together, exactly once.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct Call {
  /// Strictly increasing insert order.
  pub id: u64,
  pub uid: Uid,
  pub group_uid: Uid,
  pub social_account_uid: Uid,
  pub conversation_uid: Uid,
  /// The platform's id for this call — how bridge events find the row.
  pub wa_call_id: String,
  pub direction: CallDirection,
  /// Started as a video call, as opposed to upgrading to one mid-call.
  pub video: bool,
  /// Video was active at some point, from either side.
  pub had_video: bool,
  /// The operator who claimed the call; `None` while it is still ringing, and
  /// forever on a call nobody here took.
  pub answered_by_uid: Option<Uid>,
  pub started_at: Timestamp,
  pub answered_at: Option<Timestamp>,
  pub ended_at: Option<Timestamp>,
  pub outcome: Option<CallOutcome>,
  pub created_at: Timestamp,
}
