// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::campaign_recipient_status::CampaignRecipientStatus;
use crate::types::types::campaign_skip_reason::CampaignSkipReason;
use crate::types::primitives::name::Name;
use crate::types::primitives::phone::Phone;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// One audience entry — a number, the account assigned to reach it — and its
/// outcome. The `pending` rows of a campaign, per account in `id` order, are
/// that account's queue: the message-table pattern, so a restart resumes the
/// drip from the table itself.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct CampaignRecipient {
  pub id: u64,
  pub campaign_uid: Uid,
  /// E.164, the audience key: one row per number per campaign.
  pub phone: Phone,
  /// The name known for the number at build — an import's name column, or
  /// an existing conversation's — for `{{nome}}` on a conversation that has
  /// none yet, and applied as its alias when it is discovered.
  pub alias: Option<Name>,
  /// The account assigned to send, by the balanced-with-affinity
  /// distribution at build.
  pub social_account_uid: Uid,
  /// The conversation on that account; `None` until the dispatcher
  /// discovers it — a "new conversation" for the operator.
  pub conversation_uid: Option<Uid>,
  pub status: CampaignRecipientStatus,
  pub skip_reason: Option<CampaignSkipReason>,
  /// The wheel's pick, recorded at dispatch.
  pub template_uid: Option<Uid>,
  pub message_uid: Option<Uid>,
  pub error: Option<String>,
  pub dispatched_at: Option<Timestamp>,
}
