// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct Comment {
  /// Strictly increasing insert order — the polling cursor.
  pub id: u64,
  pub uid: Uid,
  pub social_account_uid: Uid,
  /// Local post row when the commented post was published through the hub.
  pub post_uid: Option<Uid>,
  pub external_id: String,
  pub external_post_id: String,
  pub external_parent_id: Option<String>,
  pub from_id: String,
  pub from_name: Option<String>,
  /// The account's own comments (our replies or comments made natively).
  pub from_account: bool,
  pub text: String,
  pub hidden: bool,
  pub deleted: bool,
  pub sent_at: Timestamp,
  pub created_at: Timestamp,
}
