// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::message_content_kind::MessageContentKind;
use crate::types::types::message_direction::MessageDirection;
use crate::types::types::message_sent_by::MessageSentBy;
use crate::types::types::message_status::MessageStatus;
use crate::types::types::referral::Referral;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct Conversation {
  pub uid: Uid,
  pub social_account_uid: Uid,
  /// Platform participant id (PSID / IGSID / whatsapp wa_id) — scoped to the
  /// account.
  pub participant_id: String,
  /// Best-effort profile fetched from Meta on first contact.
  pub participant_name: Option<String>,
  pub participant_username: Option<String>,
  pub participant_avatar_url: Option<String>,
  pub last_message_at: Timestamp,
  /// Last inbound (participant) message — anchors whatsapp's 24h window.
  pub last_inbound_at: Option<Timestamp>,
  /// Inbound messages sent at or before this instant were marked seen on the
  /// platform. Unread detection: `last_inbound_at > seen_up_to`.
  pub seen_up_to: Option<Timestamp>,
  /// Inbound messages since the conversation was last read (hub-local; a
  /// platform mark-seen also clears it).
  pub unread_count: u32,
  /// Denormalized newest-message preview — what a chat-list line renders.
  pub last_message_uid: Option<Uid>,
  pub last_message_kind: Option<MessageContentKind>,
  pub last_message_text: Option<String>,
  pub last_message_direction: Option<MessageDirection>,
  pub last_message_status: Option<MessageStatus>,
  /// Sender attribution of the previewed message (outbound only) — lets list
  /// consumers detect human takeovers without fetching messages.
  pub last_message_sent_by: Option<MessageSentBy>,
  /// The ad the conversation last arrived from (click-to-whatsapp) — the
  /// newest message-level referral, rolled up here like the last_message_*
  /// columns so a chat list answers "where did this come from" directly.
  pub referral: Option<Referral>,
  /// When that referral arrived (the message's sent_at).
  pub referral_at: Option<Timestamp>,
  pub created_at: Timestamp,
  pub updated_at: Timestamp,
}
