// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::email_kind::EmailKind;
use crate::types::types::email_queue_status::EmailQueueStatus;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct EmailQueueItem {
  pub id: u64,
  pub to_email: String,
  pub to_name: Option<String>,
  pub subject: String,
  pub template_name: String,
  pub status: EmailQueueStatus,
  pub kind: EmailKind,
  pub target_uid: Option<Uid>,
  pub attempts: u8,
  /// When set, the worker won't retry this row until `next_retry_at <= now`.
  /// `NULL` means "ready immediately" (fresh enqueue or operator-triggered retry).
  pub next_retry_at: Option<Timestamp>,
  pub error_message: Option<String>,
  pub created_at: Timestamp,
  pub sent_at: Option<Timestamp>,
}
