// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct Mention {
  /// Strictly increasing insert order — the polling cursor.
  pub id: u64,
  pub uid: Uid,
  pub social_account_uid: Uid,
  /// The media where the account was mentioned (caption or comment).
  pub external_media_id: String,
  /// Set when the mention happened inside a comment.
  pub external_comment_id: Option<String>,
  pub created_at: Timestamp,
}
