// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::message_content::MessageContent;
use crate::types::types::message_direction::MessageDirection;
use crate::types::types::message_reaction::MessageReaction;
use crate::types::types::message_sent_by::MessageSentBy;
use crate::types::types::message_status::MessageStatus;
use crate::types::types::referral::Referral;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct Message {
  /// Strictly increasing insert order — the polling cursor.
  pub id: u64,
  pub uid: Uid,
  pub conversation_uid: Uid,
  pub social_account_uid: Uid,
  pub participant_id: String,
  pub direction: MessageDirection,
  pub content: MessageContent,
  pub reactions: Vec<MessageReaction>,
  /// Local uid of the message this one replies to, when we hold it.
  pub reply_to_uid: Option<Uid>,
  /// The ad this message arrived from (whatsapp: official reports it as
  /// `referral`, the session-backed flavors as `contextInfo.externalAdReply`).
  /// Set only on the first message after an ad tap.
  pub referral: Option<Referral>,
  pub status: MessageStatus,
  pub error: Option<String>,
  pub external_mid: Option<String>,
  /// Client-supplied dedup key: a keyed retry of a failed send updates this
  /// row in place instead of inserting a sibling.
  pub idempotency_key: Option<String>,
  /// Who produced this outbound row: a machine client through the api, a hub
  /// operator, or a platform echo (paired phone / whatsapp web / meta
  /// business inbox, incl. history imports). `None` on inbound rows and rows
  /// stored before the field existed.
  pub sent_by: Option<MessageSentBy>,
  /// The api key / user uid behind `sent_by`, when it names one.
  pub sent_by_uid: Option<Uid>,
  /// Set when the message text was edited on the platform.
  pub edited_at: Option<Timestamp>,
  /// Set when the message was revoked on the platform; the row stays.
  pub deleted_at: Option<Timestamp>,
  pub sent_at: Timestamp,
  pub created_at: Timestamp,
}
