// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::post_content::PostContent;
use crate::types::types::post_status::PostStatus;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct Post {
  pub uid: Uid,
  pub social_account_uid: Uid,
  pub content: PostContent,
  pub status: PostStatus,
  pub error: Option<String>,
  /// Hub-side schedule instant for `scheduled` posts.
  pub scheduled_at: Option<Timestamp>,
  /// Instagram media container awaiting Meta-side processing.
  pub container_id: Option<String>,
  /// Carousel child containers (comma-separated) still processing.
  pub container_children: Option<String>,
  pub external_id: Option<String>,
  pub permalink: Option<String>,
  pub created_by: Option<Uid>,
  pub created_at: Timestamp,
  pub updated_at: Timestamp,
}
