// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct PulseDiskInventoryRow {
  pub recorded_at: i64,
  pub name: String,
  pub mount_point: String,
  pub fs_type: String,
  pub total_bytes: u64,
  pub removed: bool,
}
