// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct PulseGpuInventoryRow {
  pub recorded_at: i64,
  pub gpu_index: u32,
  pub name: String,
  pub vendor: String,
  pub vram_total_bytes: u64,
  pub power_limit_watts: f32,
  pub removed: bool,
}
