// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct PulseNetworkInventoryRow {
  pub recorded_at: i64,
  pub interface: String,
  pub mac_address: String,
  pub ipv4_addresses: Vec<String>,
  pub ipv6_addresses: Vec<String>,
  pub link_speed_mbps: Option<u32>,
  pub is_physical: bool,
  pub removed: bool,
}
