// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

/// One account's share of the queue.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct RecipientLoad {
  pub social_account_uid: Uid,
  /// Queued rows assigned to the account.
  pub pending: u32,
  /// Of those, the numbers it has no conversation with yet — each one is a
  /// discovery (a number check and a new thread) before the send.
  pub new_conversations: u32,
}
