// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::provider::Provider;
use crate::types::types::session_ban_reason::SessionBanReason;
use crate::types::types::session_incident_kind::SessionIncidentKind;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct SocialAccount {
  pub uid: Uid,
  pub group_uid: Uid,
  /// The account's kind — the registry's axis. Messaging providers project
  /// onto a [`Channel`] via [`Self::channel`]; non-messaging ones (calendar)
  /// onto none.
  pub provider: Provider,
  /// Platform identity webhooks address: page id (facebook), ig user id
  /// (instagram), or the provider's stable subject. Unique together with
  /// `provider`.
  pub external_id: String,
  /// Backing Facebook Page — the send/publish path for both channels.
  pub page_id: String,
  /// What the platform calls this account, refreshed from the platform. Never
  /// operator-supplied — that is [`Self::alias`].
  pub name: String,
  /// An operator's own label for the account, when they set one. Independent
  /// of [`Self::name`]: renaming the account on the platform does not disturb
  /// it, and clearing it falls back to the platform name.
  pub alias: Option<String>,
  /// The account's own picture, as the platform serves it.
  pub avatar_url: Option<String>,
  /// When [`Self::name`] and [`Self::avatar_url`] were last read from the
  /// platform. `None` means never — which the refresh sweep treats as due now.
  pub profile_refreshed_at: Option<Timestamp>,
  pub username: Option<String>,
  /// OAuth-refresh providers only: scopes actually granted on the last connect.
  pub scope: Option<String>,
  /// OAuth-refresh providers only: the stored grant died (revoked or
  /// expired) — the account must be reconnected; cleared by a reconnect.
  pub needs_reauth: bool,
  pub enabled: bool,
  /// Why this account's session last stopped working, for the session-backed
  /// whatsapp channels. Survives restarts and outlives the live connection
  /// state, which only ever reports the socket as it is right now — an
  /// operator needs to know the account was banned an hour ago, not just that
  /// it is currently down. Cleared on a successful (re)connect.
  pub session_incident: Option<SessionIncidentKind>,
  /// When [`Self::session_incident`] happened.
  pub session_incident_at: Option<Timestamp>,
  /// The platform's technical detail behind the incident — for operators and
  /// logs, never a user-facing message.
  pub session_incident_detail: Option<String>,
  /// When a temporary ban lifts, as the platform reported it; `None` for every
  /// other incident.
  pub session_incident_expires_at: Option<Timestamp>,
  /// Which behaviour earned a temporary ban; `None` for every other incident.
  pub session_incident_ban_reason: Option<SessionBanReason>,
  pub connected_by: Uid,
  pub created_at: Timestamp,
  pub updated_at: Timestamp,
}
