// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::email::Email;
use crate::types::types::membership_role::MembershipRole;
use crate::types::primitives::name::Name;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;
use crate::types::types::user_invite_email_status::UserInviteEmailStatus;

/// `group_uid` and `role` are a tied pair the DB CHECK enforces: both set means
/// accepting joins that group with that role, both NULL means a platform invite
/// that lands the new user in no group at all.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.database"))]
pub struct UserInvite {
  pub uid: Uid,
  pub email: Email,
  pub name: Name,
  pub invited_by: Uid,
  pub group_uid: Option<Uid>,
  pub role: Option<MembershipRole>,
  pub expires_at: Timestamp,
  pub accepted_at: Option<Timestamp>,
  pub email_status: UserInviteEmailStatus,
  pub created_at: Timestamp,
}
