// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::membership_role::MembershipRole;
use crate::types::primitives::uid::Uid;
use crate::types::types::user_permission::UserPermission;

/// One group the caller belongs to, with the authority its role carries there
/// already materialized. The catalog lists every role explicitly precisely so
/// these sets ship resolved: mapping a role onto permissions is never the
/// frontend's job.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user"))]
pub struct MembershipResponse {
  pub group_uid: Uid,
  pub role: MembershipRole,
  /// What the caller may do inside this group, and nowhere else by virtue of
  /// this entry.
  pub permissions: Vec<UserPermission>,
  /// The membership roles the caller may hand out in this group — an admin of
  /// one group assigns nothing in another.
  pub assignable_roles: Vec<MembershipRole>,
}
