// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::user::membership_response::MembershipResponse;
use crate::types::database::user::User;
use crate::types::types::user_permission::UserPermission;

/// The caller's own account plus everything a gating decision reads: the
/// platform-wide permission set the `super_admin` flag carries, and one entry
/// per group they belong to. A user who belongs to nowhere is ordinary — both
/// lists are simply empty.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user"))]
pub struct UserSelfResponse {
  #[serde(flatten)]
  pub user: User,
  /// Held everywhere, in every group and outside all of them: the whole
  /// catalog for platform staff, empty for everyone else, whose authority
  /// lives entirely in `memberships`.
  pub permissions: Vec<UserPermission>,
  pub memberships: Vec<MembershipResponse>,
}
