// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::password8_128__f__f__t__f::Password8_128_F_F_T_F;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user"))]
pub struct UserChangePasswordRequest {
  pub current_password: String,
  pub new_password: Password8_128_F_F_T_F,
}
