// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::message_chime::MessageChime;

/// The caller's own notification choices that are not tied to one account.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user"))]
pub struct UserNotificationResponse {
  pub message_chime: MessageChime,
}
