// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::database::pulse_disk_metric_row::PulseDiskMetricRow;
use crate::types::database::pulse_gpu_metric_row::PulseGpuMetricRow;
use crate::types::pulse::pulse_history_query::PulseHistoryQuery;
use crate::types::database::pulse_host_metric_row::PulseHostMetricRow;
use crate::types::database::pulse_network_metric_row::PulseNetworkMetricRow;

/// List historical disk metrics within a time window.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn disk(__client: &crate::runtime::Client, __query: &PulseHistoryQuery) -> crate::runtime::ApiResult<Vec<PulseDiskMetricRow>> {
  let mut __path = String::from("/pulse/history/disk");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List historical GPU metrics within a time window.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn gpu(__client: &crate::runtime::Client, __query: &PulseHistoryQuery) -> crate::runtime::ApiResult<Vec<PulseGpuMetricRow>> {
  let mut __path = String::from("/pulse/history/gpu");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List historical host metrics within a time window.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn host(__client: &crate::runtime::Client, __query: &PulseHistoryQuery) -> crate::runtime::ApiResult<Vec<PulseHostMetricRow>> {
  let mut __path = String::from("/pulse/history/host");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List historical network metrics within a time window.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn network(__client: &crate::runtime::Client, __query: &PulseHistoryQuery) -> crate::runtime::ApiResult<Vec<PulseNetworkMetricRow>> {
  let mut __path = String::from("/pulse/history/network");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
