// This file was generated by tapir. Do not edit this file manually.
pub mod pulse_cpu_snapshot;
pub mod pulse_disk_snapshot;
pub mod pulse_gpu_snapshot;
pub mod pulse_gpu_vendor;
pub mod pulse_network_snapshot;
pub mod pulse_process_snapshot;
pub mod pulse_process_status;
pub mod pulse_ram_snapshot;
pub mod pulse_snapshot;
pub mod pulse_system_info;
pub mod pulse_temperature_reading;
