// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::pulse_sys::pulse_gpu_vendor::PulseGpuVendor;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse_sys"))]
pub struct PulseGpuSnapshot {
  pub index: u32,
  pub name: String,
  pub vendor: PulseGpuVendor,
  pub vram_total_bytes: u64,
  pub vram_used_bytes: u64,
  pub vram_usage_percent: f32,
  pub utilization_percent: u32,
  pub memory_utilization_percent: u32,
  pub clock_graphics_mhz: u32,
  pub clock_memory_mhz: u32,
  pub temperature_celsius: u32,
  pub power_watts: f32,
  pub power_limit_watts: f32,
}
