// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::pulse_sys::pulse_cpu_snapshot::PulseCpuSnapshot;
use crate::types::pulse_sys::pulse_disk_snapshot::PulseDiskSnapshot;
use crate::types::pulse_sys::pulse_gpu_snapshot::PulseGpuSnapshot;
use crate::types::pulse_sys::pulse_network_snapshot::PulseNetworkSnapshot;
use crate::types::pulse_sys::pulse_process_snapshot::PulseProcessSnapshot;
use crate::types::pulse_sys::pulse_ram_snapshot::PulseRamSnapshot;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse_sys"))]
pub struct PulseSnapshot {
  pub timestamp_ms: i64,
  pub uptime_secs: u64,
  pub cpu: PulseCpuSnapshot,
  pub ram: PulseRamSnapshot,
  pub disks: Vec<PulseDiskSnapshot>,
  pub networks: Vec<PulseNetworkSnapshot>,
  pub processes: Vec<PulseProcessSnapshot>,
  pub gpus: Vec<PulseGpuSnapshot>,
}
