// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse_sys"))]
pub struct PulseNetworkSnapshot {
  pub interface: String,
  pub mac_address: String,
  pub ipv4_addresses: Vec<String>,
  pub ipv6_addresses: Vec<String>,
  pub link_speed_mbps: Option<u32>,
  pub is_physical: bool,
  pub received_bytes: u64,
  pub transmitted_bytes: u64,
  pub total_received_bytes: u64,
  pub total_transmitted_bytes: u64,
  pub received_bytes_per_sec: f64,
  pub transmitted_bytes_per_sec: f64,
  pub received_packets: u64,
  pub transmitted_packets: u64,
  pub received_errors: u64,
  pub transmitted_errors: u64,
}
