// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::pulse_sys::pulse_temperature_reading::PulseTemperatureReading;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse_sys"))]
pub struct PulseCpuSnapshot {
  pub global_usage: f32,
  pub per_core_usage: Vec<f32>,
  pub frequency_mhz: u64,
  pub per_core_frequency_mhz: Vec<u64>,
  pub physical_cores: usize,
  pub logical_cores: usize,
  pub load_avg_one: f64,
  pub load_avg_five: f64,
  pub load_avg_fifteen: f64,
  pub temperatures: Vec<PulseTemperatureReading>,
}
