// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::pulse_sys::pulse_process_status::PulseProcessStatus;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse_sys"))]
pub struct PulseProcessSnapshot {
  pub pid: u32,
  pub name: String,
  pub cpu_usage: f32,
  pub memory_bytes: u64,
  pub virtual_memory_bytes: u64,
  pub disk_read_bytes: u64,
  pub disk_written_bytes: u64,
  pub status: PulseProcessStatus,
  pub run_time_secs: u64,
}
