// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::pulse_sys::pulse_temperature_reading::PulseTemperatureReading;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse_sys"))]
pub struct PulseRamSnapshot {
  pub total_bytes: u64,
  pub used_bytes: u64,
  pub available_bytes: u64,
  pub usage_percent: f32,
  pub swap_total_bytes: u64,
  pub swap_used_bytes: u64,
  pub swap_usage_percent: f32,
  pub page_in_bytes_per_sec: f64,
  pub page_out_bytes_per_sec: f64,
  pub swap_in_bytes_per_sec: f64,
  pub swap_out_bytes_per_sec: f64,
  pub temperatures: Vec<PulseTemperatureReading>,
}
