// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::issue_category::IssueCategory;
use crate::types::domain::issue_severity::IssueSeverity;
use crate::types::primitives::text0_2048::Text0_2048;
use crate::types::primitives::text0_8000::Text0_8000;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.issue"))]
pub struct CreateIssueForm {
  pub category: IssueCategory,
  pub severity: IssueSeverity,
  pub description: Text0_8000,
  pub url: Option<Text0_2048>,
  pub screenshots: Vec<Vec<u8>>,
}
