// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::user_mfa::user_mfa_enroll_confirm_request::UserMfaEnrollConfirmRequest;
use crate::types::user_mfa::user_mfa_mgmt_email_start_response::UserMfaMgmtEmailStartResponse;

/// Confirm self-service email-factor enrollment with a code.
///
/// Authenticated user acting on their own factors; no permission required.
pub async fn confirm(__client: &crate::runtime::Client, __body: &UserMfaEnrollConfirmRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/user-mfa/factor/email/confirm");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Begin self-service email-factor enrollment, emailing a one-time code and returning an enrollment token.
///
/// Authenticated user acting on their own factors; no permission required.
pub async fn start(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<UserMfaMgmtEmailStartResponse> {
  let mut __path = String::from("/user-mfa/factor/email/start");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
