// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::database::audit_log::AuditLog;
use crate::types::audit_log::audit_log_query::AuditLogQuery;
use crate::types::database::audit_log_stats::AuditLogStats;

/// Count audit log entries matching the given filters and time window.
///
/// Requires `ViewAuditLogs`; platform staff count every entry, any other holder only entries stamped with a group where they hold it — an entry carrying no group is staff-only.
pub async fn count(__client: &crate::runtime::Client, __query: &AuditLogQuery) -> crate::runtime::ApiResult<u64> {
  let mut __path = String::from("/audit-log/count");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List audit log entries matching the given filters and time window.
///
/// Requires `ViewAuditLogs`; platform staff read every entry, any other holder only entries stamped with a group where they hold it — an entry carrying no group is staff-only.
pub async fn list(__client: &crate::runtime::Client, __query: &AuditLogQuery) -> crate::runtime::ApiResult<Vec<AuditLog>> {
  let mut __path = String::from("/audit-log");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Aggregate audit log statistics for the given filters and time window.
///
/// Requires `ViewAuditLogs`; platform staff aggregate every entry, any other holder only entries stamped with a group where they hold it — an entry carrying no group is staff-only.
pub async fn stats(__client: &crate::runtime::Client, __query: &AuditLogQuery) -> crate::runtime::ApiResult<AuditLogStats> {
  let mut __path = String::from("/audit-log/stat");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
