// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::domain::call::Call;
use crate::types::domain::conversation::Conversation;
use crate::types::message::conversation_action_request::ConversationActionRequest;
use crate::types::message::conversation_avatar::ConversationAvatar;
use crate::types::call::conversation_calls_query::ConversationCallsQuery;
use crate::types::message::conversation_message_count_query::ConversationMessageCountQuery;
use crate::types::message::conversation_messages_query::ConversationMessagesQuery;
use crate::types::message::create_conversation_request::CreateConversationRequest;
use crate::types::message::list_conversations_query::ListConversationsQuery;
use crate::types::domain::message::Message;
use crate::types::message::set_conversation_alias_request::SetConversationAliasRequest;

/// Send a presence signal into a conversation: mark_seen, typing_on, or
/// typing_off. The payload is channel-tagged and the `channel` must match the
/// conversation's account; official whatsapp has no typing_off (its indicator
/// auto-dismisses), so that channel's shape cannot express one. Mark-seen
/// receipts every inbound message still unread (the latest 50 on the
/// session-backed whatsapp channels, the latest one on official whatsapp) and
/// advances the conversation's `seen_up_to` watermark (`last_inbound_at >
/// seen_up_to` = unread); with nothing unread it is a no-op.
///
/// Requires `SendMessages` in the conversation's group.
pub async fn action(__client: &crate::runtime::Client, conversation_uid: &str, __body: &ConversationActionRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}/action");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Set or clear the operator's label for the contact. Independent of the
/// platform-fetched participant name, which profile refreshes keep updating;
/// clearing the alias falls back to it.
///
/// Requires `SendMessages` in the conversation's group.
pub async fn alias(__client: &crate::runtime::Client, conversation_uid: &str, __body: &SetConversationAliasRequest) -> crate::runtime::ApiResult<Conversation> {
  let mut __path = String::from("/conversation/{conversation_uid}/alias");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// The participant's full-size profile picture, fetched from the platform on
/// first request and kept until the platform reports a picture change; a
/// request that finds none is not retried for ten minutes. Channels without a
/// full-size picture answer with the picture the hub already holds.
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn avatar(__client: &crate::runtime::Client, conversation_uid: &str) -> crate::runtime::ApiResult<ConversationAvatar> {
  let mut __path = String::from("/conversation/{conversation_uid}/avatar");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List a conversation's calls, newest first; `before_id` pages older history.
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn calls(__client: &crate::runtime::Client, conversation_uid: &str, __query: &ConversationCallsQuery) -> crate::runtime::ApiResult<Vec<Call>> {
  let mut __path = String::from("/conversation/{conversation_uid}/call");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Erase the conversation's stored history on the hub, keeping the
/// conversation: its messages go, the preview and unread badge reset, and the
/// 24h-window watermarks stay. Nothing is deleted on the platform.
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn clear(__client: &crate::runtime::Client, conversation_uid: &str) -> crate::runtime::ApiResult<Conversation> {
  let mut __path = String::from("/conversation/{conversation_uid}/message");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Open (or return) a conversation with a phone number — a channel-tagged
/// request whose declared channel must match the account's; only
/// whatsapp_stevo / whatsapp_native can verify a number on the platform,
/// so no other channel's shape deserializes. A number the account already
/// talks to returns its conversation with no platform lookup at all; a new
/// one is checked first (an unrecognized number or failed check creates
/// nothing), the platform's canonical id keys the conversation, and the
/// initial profile (name, picture) is stored best-effort and refreshed at
/// most every 30 days.
///
/// Requires `SendMessages` in the account's group.
pub async fn create(__client: &crate::runtime::Client, __body: &CreateConversationRequest) -> crate::runtime::ApiResult<Conversation> {
  let mut __path = String::from("/conversation");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Delete the conversation and its whole stored history from the hub.
/// Nothing is deleted on the platform: a later inbound message from the same
/// participant opens a fresh conversation.
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn delete(__client: &crate::runtime::Client, conversation_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// List conversations, newest activity first, optionally filtered by group or
/// social account; `before_activity_at`+`before_uid` page older activity
/// (keyset cursor). Rows carry the denormalized chat-list summary (unread
/// badge + last-message preview). `q` narrows to conversations whose
/// participant (alias, name, username, phone) contains it — a term under 2
/// characters answers with no rows; not combinable with `uids`.
///
/// Requires `ViewMessages`; the list covers only conversations of groups where the caller holds it.
pub async fn list(__client: &crate::runtime::Client, __query: &ListConversationsQuery) -> crate::runtime::ApiResult<Vec<Conversation>> {
  let mut __path = String::from("/conversation");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// How many messages the conversation holds, narrowed by `kinds` like the
/// list — what a media gallery shows as its total.
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn message_count(__client: &crate::runtime::Client, conversation_uid: &str, __query: &ConversationMessageCountQuery) -> crate::runtime::ApiResult<u64> {
  let mut __path = String::from("/conversation/{conversation_uid}/message/count");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List a conversation's messages, newest first; `before_id` pages older
/// history. `after_id` pages newer history from an anchored message: each
/// page is the oldest `limit` rows above the cursor, still newest-first on
/// the wire (never both cursors).
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn messages(__client: &crate::runtime::Client, conversation_uid: &str, __query: &ConversationMessagesQuery) -> crate::runtime::ApiResult<Vec<Message>> {
  let mut __path = String::from("/conversation/{conversation_uid}/message");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Clear the conversation's unread badge (hub-local read state, shared by
/// every operator). Never sends a platform read receipt — that stays the
/// explicit `mark_seen` conversation action.
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn read(__client: &crate::runtime::Client, conversation_uid: &str) -> crate::runtime::ApiResult<Conversation> {
  let mut __path = String::from("/conversation/{conversation_uid}/read");
  __path = __path.replace("{conversation_uid}", &crate::runtime::encode_path(conversation_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, None::<&()>).await
}
/// How many conversations hold unread messages, across every group where the
/// caller holds `ViewMessages` — the inbox badge.
///
/// Requires `ViewMessages`; the count covers every group where the caller holds it.
pub async fn unread_count(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<u64> {
  let mut __path = String::from("/conversation/unread");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
