// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::database::conversation::Conversation;
use crate::types::message::conversation_action_request::ConversationActionRequest;
use crate::types::message::conversation_messages_query::ConversationMessagesQuery;
use crate::types::message::create_conversation_request::CreateConversationRequest;
use crate::types::message::list_conversations_query::ListConversationsQuery;
use crate::types::database::message::Message;

/// Send a presence signal into a conversation: mark_seen, typing_on, or
/// typing_off. The payload is channel-tagged and the `channel` must match the
/// conversation's account; official whatsapp has no typing_off (its indicator
/// auto-dismisses), so that channel's shape cannot express one. Mark-seen
/// advances the conversation's `seen_up_to` watermark (`last_inbound_at >
/// seen_up_to` = unread).
///
/// Requires `SendMessages` in the conversation's group.
pub async fn action(client: &Client, conversation_uid: &str, body: &ConversationActionRequest) -> ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}/action");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Erase the conversation's stored history on the hub, keeping the
/// conversation: its messages go, the preview and unread badge reset, and the
/// 24h-window watermarks stay. Nothing is deleted on the platform.
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn clear(client: &Client, conversation_uid: &str) -> ApiResult<Conversation> {
  let mut __path = String::from("/conversation/{conversation_uid}/message");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Open (or return) a conversation with a phone number — a channel-tagged
/// request whose declared channel must match the account's; only
/// whatsapp_stevo / whatsapp_native can verify a number on the platform,
/// so no other channel's shape deserializes. The number is checked first
/// (an unrecognized number or failed check creates nothing), the platform's
/// canonical id keys the conversation, and the initial profile (name,
/// picture) is stored best-effort.
///
/// Requires `SendMessages` in the account's group.
pub async fn create(client: &Client, body: &CreateConversationRequest) -> ApiResult<Conversation> {
  let mut __path = String::from("/conversation");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Delete the conversation and its whole stored history from the hub.
/// Nothing is deleted on the platform: a later inbound message from the same
/// participant opens a fresh conversation.
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn delete(client: &Client, conversation_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// List conversations, newest activity first, optionally filtered by group or
/// social account; `before_activity_at`+`before_uid` page older activity
/// (keyset cursor). Rows carry the denormalized chat-list summary (unread
/// badge + last-message preview).
///
/// Requires `ViewMessages`; the list covers only conversations of groups where the caller holds it.
pub async fn list(client: &Client, query: &ListConversationsQuery) -> ApiResult<Vec<Conversation>> {
  let mut __path = String::from("/conversation");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// List a conversation's messages, newest first; `before_id` pages older
/// history.
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn messages(client: &Client, conversation_uid: &str, query: &ConversationMessagesQuery) -> ApiResult<Vec<Message>> {
  let mut __path = String::from("/conversation/{conversation_uid}/message");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Clear the conversation's unread badge (hub-local read state, shared by
/// every operator). Never sends a platform read receipt — that stays the
/// explicit `mark_seen` conversation action.
///
/// Requires `ViewMessages` in the conversation's group.
pub async fn read(client: &Client, conversation_uid: &str) -> ApiResult<Conversation> {
  let mut __path = String::from("/conversation/{conversation_uid}/read");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  client.request(Method::PUT, &__path, None::<&()>, None::<&()>).await
}
