// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::database::comment::Comment;
use crate::types::engagement::comment_message_request::CommentMessageRequest;
use crate::types::engagement::create_comment_request::CreateCommentRequest;
use crate::types::engagement::list_comments_query::ListCommentsQuery;
use crate::types::engagement::private_reply_request::PrivateReplyRequest;
use crate::types::engagement::private_reply_response::PrivateReplyResponse;
use crate::types::engagement::set_comment_hidden_request::SetCommentHiddenRequest;

/// Comment on a post/media as the account named in the path (top-level
/// comment). The payload is channel-tagged and must match the account's
/// channel — only facebook and instagram carry a comment surface, so no
/// other channel's shape deserializes.
///
/// Requires `ReplyComments` in the account's group.
pub async fn create(__client: &crate::runtime::Client, social_account_uid: &str, __body: &CreateCommentRequest) -> crate::runtime::ApiResult<Comment> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Delete a comment from the platform; the row is kept with `deleted` set.
///
/// Requires `ModerateComments` in the account's group.
pub async fn delete(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch a single comment of the account. A comment uid outside the named
/// account reads as not found.
///
/// Requires `ViewComments` in the account's group.
pub async fn get(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str) -> crate::runtime::ApiResult<Comment> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Like a comment as the page (Facebook only — Instagram's API has no
/// comment likes).
///
/// Requires `ReplyComments` in the account's group.
pub async fn like(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/like");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Poll the unified comment feed: comments with `id` greater than `since_id`,
/// oldest first, optionally filtered by group, account, or post.
///
/// Requires `ViewComments`; the feed covers only comments of groups where the caller holds it.
pub async fn list(__client: &crate::runtime::Client, __query: &ListCommentsQuery) -> crate::runtime::ApiResult<Vec<Comment>> {
  let mut __path = String::from("/comment");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Answer a comment privately with a DM (allowed once per comment; the
/// message lands in the conversation via the echo webhook). The account's
/// own comments are refused.
///
/// Requires `SendMessages` in the account's group (the reply is a DM, not a comment).
pub async fn private_reply(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str, __body: &PrivateReplyRequest) -> crate::runtime::ApiResult<PrivateReplyResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/private-reply");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Reply to a comment as the account (threaded reply).
///
/// Requires `ReplyComments` in the account's group.
pub async fn reply(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str, __body: &CommentMessageRequest) -> crate::runtime::ApiResult<Comment> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/reply");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Hide or unhide a comment on the platform.
///
/// Requires `ModerateComments` in the account's group.
pub async fn set_hidden(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str, __body: &SetCommentHiddenRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/hidden");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Remove the page's like from a comment (Facebook only).
///
/// Requires `ReplyComments` in the account's group.
pub async fn unlike(__client: &crate::runtime::Client, social_account_uid: &str, comment_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/like");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &crate::runtime::encode_path(comment_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
