// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::database::comment::Comment;
use crate::types::engagement::comment_message_request::CommentMessageRequest;
use crate::types::engagement::create_comment_request::CreateCommentRequest;
use crate::types::engagement::list_comments_query::ListCommentsQuery;
use crate::types::engagement::private_reply_request::PrivateReplyRequest;
use crate::types::engagement::private_reply_response::PrivateReplyResponse;
use crate::types::engagement::set_comment_hidden_request::SetCommentHiddenRequest;

/// Comment on a post/media as the account named in the path (top-level
/// comment; Facebook and Instagram only).
///
/// Requires `ReplyComments` in the account's group.
pub async fn create(client: &Client, social_account_uid: &str, body: &CreateCommentRequest) -> ApiResult<Comment> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Delete a comment from the platform; the row is kept with `deleted` set.
///
/// Requires `ModerateComments` in the account's group.
pub async fn delete(client: &Client, social_account_uid: &str, comment_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch a single comment of the account. A comment uid outside the named
/// account reads as not found.
///
/// Requires `ViewComments` in the account's group.
pub async fn get(client: &Client, social_account_uid: &str, comment_uid: &str) -> ApiResult<Comment> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Like a comment as the page (Facebook only — Instagram's API has no
/// comment likes).
///
/// Requires `ReplyComments` in the account's group.
pub async fn like(client: &Client, social_account_uid: &str, comment_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/like");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Poll the unified comment feed: comments with `id` greater than `since_id`,
/// oldest first, optionally filtered by group, account, or post.
///
/// Requires `ViewComments`; the feed covers only comments of groups where the caller holds it.
pub async fn list(client: &Client, query: &ListCommentsQuery) -> ApiResult<Vec<Comment>> {
  let mut __path = String::from("/comment");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Answer a comment privately with a DM (allowed once per comment; the
/// message lands in the conversation via the echo webhook). The account's
/// own comments are refused.
///
/// Requires `SendMessages` in the account's group (the reply is a DM, not a comment).
pub async fn private_reply(client: &Client, social_account_uid: &str, comment_uid: &str, body: &PrivateReplyRequest) -> ApiResult<PrivateReplyResponse> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/private-reply");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Reply to a comment as the account (threaded reply).
///
/// Requires `ReplyComments` in the account's group.
pub async fn reply(client: &Client, social_account_uid: &str, comment_uid: &str, body: &CommentMessageRequest) -> ApiResult<Comment> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/reply");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Hide or unhide a comment on the platform.
///
/// Requires `ModerateComments` in the account's group.
pub async fn set_hidden(client: &Client, social_account_uid: &str, comment_uid: &str, body: &SetCommentHiddenRequest) -> ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/hidden");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Remove the page's like from a comment (Facebook only).
///
/// Requires `ReplyComments` in the account's group.
pub async fn unlike(client: &Client, social_account_uid: &str, comment_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/comment/{comment_uid}/like");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{comment_uid}", &encode_path(comment_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
