// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::post::create_post_request::CreatePostRequest;
use crate::types::meta::insight::Insight;
use crate::types::insight::insight_history_query::InsightHistoryQuery;
use crate::types::insight::insight_series::InsightSeries;
use crate::types::post::list_posts_query::ListPostsQuery;
use crate::types::database::post::Post;
use crate::types::post::post_insights_query::PostInsightsQuery;
use crate::types::post::set_post_comments_request::SetPostCommentsRequest;
use crate::types::post::set_post_hidden_request::SetPostHiddenRequest;
use crate::types::post::set_post_pinned_request::SetPostPinnedRequest;
use crate::types::post::update_post_request::UpdatePostRequest;

/// Publish (or schedule) a post through a social account; the channel-tagged
/// content must match the account's channel.
///
/// Requires `PublishPosts` in the account's group.
pub async fn create(client: &Client, body: &CreatePostRequest) -> ApiResult<Post> {
  let mut __path = String::from("/post");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Delete a post: published posts are removed from the platform (Instagram
/// carousels are deleted as a whole). A scheduled or pending post is
/// cancelled hub-side — it is never published, and its unpublished Instagram
/// container is left to expire on Meta's side rather than deleted. The row is
/// kept with a `deleted` status.
///
/// Requires `DeletePosts` in the post's group.
pub async fn delete(client: &Client, post_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch a single post by uid.
///
/// Requires `ViewPosts` in the post's group.
pub async fn get(client: &Client, post_uid: &str) -> ApiResult<Post> {
  let mut __path = String::from("/post/{post_uid}");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Fetch platform metrics for a published post (impressions, reach, clicks,
/// reactions, views, … — overridable via `metrics`).
///
/// Requires `ViewInsights` in the post's group.
pub async fn insights(client: &Client, post_uid: &str, query: &PostInsightsQuery) -> ApiResult<Vec<Insight>> {
  let mut __path = String::from("/post/{post_uid}/insight");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Day-by-day history of a post's collected metrics, grouped per metric —
/// the charting companion to the live `post.insights` passthrough. Posts are
/// collected for 30 days after publishing (stories for 48h, after which their
/// insights stop resolving), so the series flatlines after that window.
///
/// Requires `ViewInsights` in the post's group.
pub async fn insights_history(client: &Client, post_uid: &str, query: &InsightHistoryQuery) -> ApiResult<Vec<InsightSeries>> {
  let mut __path = String::from("/post/{post_uid}/insight/history");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// List posts, newest first, optionally filtered by group or social account.
///
/// Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
pub async fn list(client: &Client, query: &ListPostsQuery) -> ApiResult<Vec<Post>> {
  let mut __path = String::from("/post");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Enable or disable comments on a published post (Instagram only — Facebook
/// has no per-post comment toggle in the API).
///
/// Requires `UpdatePosts` in the post's group.
pub async fn set_comments(client: &Client, post_uid: &str, body: &SetPostCommentsRequest) -> ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}/comment");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Hide or unhide a published post from the Page timeline — it stays
/// reachable by direct link (Facebook only, non-video posts).
///
/// Requires `UpdatePosts` in the post's group.
pub async fn set_hidden(client: &Client, post_uid: &str, body: &SetPostHiddenRequest) -> ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}/hidden");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Pin or unpin a published post to the top of the Page timeline (Facebook
/// only, non-video posts).
///
/// Requires `UpdatePosts` in the post's group.
pub async fn set_pinned(client: &Client, post_uid: &str, body: &SetPostPinnedRequest) -> ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}/pinned");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Edit a published post's text on the platform (Facebook only — the
/// Instagram API cannot edit captions; stories carry no text).
///
/// Requires `UpdatePosts` in the post's group.
pub async fn update(client: &Client, post_uid: &str, body: &UpdatePostRequest) -> ApiResult<Post> {
  let mut __path = String::from("/post/{post_uid}");
  __path = __path.replace("{post_uid}", &encode_path(post_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
