// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::post::create_post_request::CreatePostRequest;
use crate::types::meta::insight::Insight;
use crate::types::insight::insight_history_query::InsightHistoryQuery;
use crate::types::insight::insight_series::InsightSeries;
use crate::types::post::list_posts_query::ListPostsQuery;
use crate::types::database::post::Post;
use crate::types::post::post_insights_query::PostInsightsQuery;
use crate::types::post::set_post_comments_request::SetPostCommentsRequest;
use crate::types::post::set_post_hidden_request::SetPostHiddenRequest;
use crate::types::post::set_post_pinned_request::SetPostPinnedRequest;
use crate::types::post::update_post_request::UpdatePostRequest;

/// Publish (or schedule) a post through a social account; the channel-tagged
/// content must match the account's channel.
///
/// Requires `PublishPosts` in the account's group.
pub async fn create(__client: &crate::runtime::Client, __body: &CreatePostRequest) -> crate::runtime::ApiResult<Post> {
  let mut __path = String::from("/post");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Delete a post: published posts are removed from the platform (Instagram
/// carousels are deleted as a whole). A scheduled or pending post is
/// cancelled hub-side — it is never published, and its unpublished Instagram
/// container is left to expire on Meta's side rather than deleted. The row is
/// kept with a `deleted` status.
///
/// Requires `DeletePosts` in the post's group.
pub async fn delete(__client: &crate::runtime::Client, post_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch a single post by uid.
///
/// Requires `ViewPosts` in the post's group.
pub async fn get(__client: &crate::runtime::Client, post_uid: &str) -> crate::runtime::ApiResult<Post> {
  let mut __path = String::from("/post/{post_uid}");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Fetch platform metrics for a published post (impressions, reach, clicks,
/// reactions, views, … — overridable via `metrics`).
///
/// Requires `ViewInsights` in the post's group.
pub async fn insights(__client: &crate::runtime::Client, post_uid: &str, __query: &PostInsightsQuery) -> crate::runtime::ApiResult<Vec<Insight>> {
  let mut __path = String::from("/post/{post_uid}/insight");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Day-by-day history of a post's collected metrics, grouped per metric —
/// the charting companion to the live `post.insights` passthrough. Posts are
/// collected for 30 days after publishing (stories for 48h, after which their
/// insights stop resolving), so the series flatlines after that window.
///
/// Requires `ViewInsights` in the post's group.
pub async fn insights_history(__client: &crate::runtime::Client, post_uid: &str, __query: &InsightHistoryQuery) -> crate::runtime::ApiResult<Vec<InsightSeries>> {
  let mut __path = String::from("/post/{post_uid}/insight/history");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List posts, newest first, optionally filtered by group or social account.
///
/// Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
pub async fn list(__client: &crate::runtime::Client, __query: &ListPostsQuery) -> crate::runtime::ApiResult<Vec<Post>> {
  let mut __path = String::from("/post");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Enable or disable comments on a published post. The payload is
/// channel-tagged and must match the post's channel — instagram only
/// (Facebook has no per-post comment toggle in the API), so no other
/// channel's shape deserializes.
///
/// Requires `UpdatePosts` in the post's group.
pub async fn set_comments(__client: &crate::runtime::Client, post_uid: &str, __body: &SetPostCommentsRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}/comment");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Hide or unhide a published post from the Page timeline — it stays
/// reachable by direct link. The payload is channel-tagged and must match
/// the post's channel — facebook only, non-video posts — so no other
/// channel's shape deserializes.
///
/// Requires `UpdatePosts` in the post's group.
pub async fn set_hidden(__client: &crate::runtime::Client, post_uid: &str, __body: &SetPostHiddenRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}/hidden");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Pin or unpin a published post to the top of the Page timeline. The
/// payload is channel-tagged and must match the post's channel — facebook
/// only, non-video posts — so no other channel's shape deserializes.
///
/// Requires `UpdatePosts` in the post's group.
pub async fn set_pinned(__client: &crate::runtime::Client, post_uid: &str, __body: &SetPostPinnedRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/post/{post_uid}/pinned");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Edit a published post's text on the platform. The payload is
/// channel-tagged and must match the post's channel — only facebook can edit
/// (the Instagram API cannot edit captions; stories carry no text), so no
/// other channel's shape deserializes.
///
/// Requires `UpdatePosts` in the post's group.
pub async fn update(__client: &crate::runtime::Client, post_uid: &str, __body: &UpdatePostRequest) -> crate::runtime::ApiResult<Post> {
  let mut __path = String::from("/post/{post_uid}");
  __path = __path.replace("{post_uid}", &crate::runtime::encode_path(post_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
