// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::insight::conversation_counts::ConversationCounts;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct AccountConversationInsight {
  pub social_account_uid: Uid,
  /// The whole period for this account.
  pub counts: ConversationCounts,
}
