// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::facebook_account_series::FacebookAccountSeries;
use crate::types::domain::facebook_alt_account_series::FacebookAltAccountSeries;
use crate::types::domain::instagram_account_series::InstagramAccountSeries;
use crate::types::domain::instagram_alt_account_series::InstagramAltAccountSeries;

/// An account's collected metrics, day by day, in the vocabulary of its
/// channel: each channel names only the metrics it reports.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum AccountInsightHistory {
  Facebook {
    series: Vec<FacebookAccountSeries>,
  },
  Instagram {
    series: Vec<InstagramAccountSeries>,
  },
  FacebookAlt {
    series: Vec<FacebookAltAccountSeries>,
  },
  InstagramAlt {
    series: Vec<InstagramAltAccountSeries>,
  },
}
