// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::facebook_account_metric::FacebookAccountMetric;
use crate::types::domain::facebook_alt_account_metric::FacebookAltAccountMetric;
use crate::types::domain::instagram_account_metric::InstagramAccountMetric;
use crate::types::domain::instagram_alt_account_metric::InstagramAltAccountMetric;

/// Which account metrics to aggregate; the channel decides the vocabulary, and
/// only accounts of that channel take part.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum AccountMetricQuery {
  Facebook {
    metrics: Vec<FacebookAccountMetric>,
  },
  Instagram {
    metrics: Vec<InstagramAccountMetric>,
  },
  FacebookAlt {
    metrics: Vec<FacebookAltAccountMetric>,
  },
  InstagramAlt {
    metrics: Vec<InstagramAltAccountMetric>,
  },
}
