// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::insight::conversation_counts::ConversationCounts;
use crate::types::primitives::timestamp::Timestamp;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct ConversationBucket {
  /// Start of the period (unix ms), aligned to the requested offset.
  pub period_start: Timestamp,
  /// End of the period (unix ms), exclusive; it may pass `until`.
  pub period_end: Timestamp,
  /// The query covers only part of the period.
  pub partial: bool,
  pub counts: ConversationCounts,
}
