// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::insight::reply_bands::ReplyBands;
use crate::types::insight::typical_wait::TypicalWait;

/// What a scope's conversations did in one period.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct ConversationCounts {
  /// Conversations whose first message ever falls in the period and came
  /// from the customer.
  pub new_by_customer: i64,
  /// Conversations whose first message ever falls in the period and came
  /// from the account.
  pub new_by_account: i64,
  /// Distinct conversations where the customer wrote in the period.
  pub customers_writing: i64,
  /// Messages received.
  pub inbound: i64,
  /// Messages the account sent, whoever or whatever sent them.
  pub outbound: i64,
  /// Requests that open an atendimento: the customer writes first, or after
  /// 24 hours of silence in the conversation, answered or not.
  pub openings: i64,
  /// First reply to each atendimento, over the answered ones.
  pub first_reply: ReplyBands,
  pub first_reply_typical: TypicalWait,
  /// Replies to requests inside an ongoing atendimento, over the answered
  /// ones.
  pub later_reply: ReplyBands,
  pub later_reply_typical: TypicalWait,
  /// Account messages that start contact: the first message of the
  /// conversation, or one after 24 hours of silence while no customer request
  /// waits.
  pub outreach: i64,
  /// Of those, the ones the customer answered within 24 hours.
  pub outreach_replied: i64,
  /// Of those, the ones younger than 24 hours still without an answer.
  pub outreach_open: i64,
}
