// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::insight::reply_bands::ReplyBands;

/// Atendimentos opened in one hour of the week across the period.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct HourOfWeek {
  /// 1 is Monday and 7 is Sunday, in the requested offset.
  pub weekday: i64,
  /// Hour of the day, 0 to 23, in the requested offset.
  pub hour: i64,
  pub openings: i64,
  pub first_reply: ReplyBands,
}
