// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::facebook_account_bucket::FacebookAccountBucket;
use crate::types::domain::facebook_alt_account_bucket::FacebookAltAccountBucket;
use crate::types::domain::facebook_alt_post_bucket::FacebookAltPostBucket;
use crate::types::domain::facebook_post_bucket::FacebookPostBucket;
use crate::types::domain::instagram_account_bucket::InstagramAccountBucket;
use crate::types::domain::instagram_alt_account_bucket::InstagramAltAccountBucket;
use crate::types::domain::instagram_alt_post_bucket::InstagramAltPostBucket;
use crate::types::domain::instagram_post_bucket::InstagramPostBucket;

/// Aggregated periods, in the vocabulary the request declared.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum InsightQueryResponse {
  FacebookAccount {
    buckets: Vec<FacebookAccountBucket>,
  },
  InstagramAccount {
    buckets: Vec<InstagramAccountBucket>,
  },
  FacebookAltAccount {
    buckets: Vec<FacebookAltAccountBucket>,
  },
  InstagramAltAccount {
    buckets: Vec<InstagramAltAccountBucket>,
  },
  FacebookPost {
    buckets: Vec<FacebookPostBucket>,
  },
  InstagramPost {
    buckets: Vec<InstagramPostBucket>,
  },
  FacebookAltPost {
    buckets: Vec<FacebookAltPostBucket>,
  },
  InstagramAltPost {
    buckets: Vec<InstagramAltPostBucket>,
  },
}
