// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::insight_value::InsightValue;
use crate::types::primitives::timestamp::Timestamp;

/// One snapshot day's value. The newest day is usually still partial — the
/// collector keeps re-capturing it until the UTC day rolls over.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct InsightPoint {
  /// UTC midnight of the snapshot day.
  pub captured_on: Timestamp,
  pub value: InsightValue,
}
