// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::activity_granularity::ActivityGranularity;
use crate::types::domain::channel::Channel;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct PostingInsightQuery {
  /// Narrow to one group; omit for everything the caller may see.
  pub group_uid: Option<Uid>,
  /// Narrow to these accounts; each must be in scope.
  pub social_account_uids: Option<Vec<Uid>>,
  /// Narrow to these channels.
  pub channels: Option<Vec<Channel>>,
  /// Start of the period (unix ms), inclusive.
  pub since: Timestamp,
  /// End of the period (unix ms), exclusive.
  pub until: Timestamp,
  pub granularity: ActivityGranularity,
  /// Minutes east of UTC that periods align to; 0 when omitted.
  pub utc_offset_minutes: Option<i32>,
}
