// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::facebook_alt_post_metric::FacebookAltPostMetric;
use crate::types::domain::facebook_post_metric::FacebookPostMetric;
use crate::types::domain::instagram_alt_post_metric::InstagramAltPostMetric;
use crate::types::domain::instagram_post_metric::InstagramPostMetric;

/// Which post metrics to aggregate, over every platform post of the accounts
/// in scope.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum PostMetricQuery {
  Facebook {
    metrics: Vec<FacebookPostMetric>,
  },
  Instagram {
    metrics: Vec<InstagramPostMetric>,
  },
  FacebookAlt {
    metrics: Vec<FacebookAltPostMetric>,
  },
  InstagramAlt {
    metrics: Vec<InstagramAltPostMetric>,
  },
}
