// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Answered requests by how long the customer waited, from the request's
/// first message to the account's reply.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.insight"))]
pub struct ReplyBands {
  /// Answered within 5 minutes.
  pub up_to_5m: i64,
  /// Answered after 5 minutes and within an hour.
  pub up_to_1h: i64,
  /// Answered after an hour and within 24 hours.
  pub up_to_24h: i64,
  /// Answered after more than 24 hours.
  pub over_24h: i64,
}
