// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::gif::gif_search_response::GifSearchResponse;
use crate::types::gif::search_gifs_query::SearchGifsQuery;

/// One page of the gif catalog: Giphy's trending feed when `q` is blank, else
/// a search for it. 24 entries a page, rated pg-13 at most; answers 503 while
/// the hub has no Giphy key.
///
/// Any authenticated caller — the route proxies a public catalog and touches no group data.
pub async fn search(__client: &crate::runtime::Client, __query: &SearchGifsQuery) -> crate::runtime::ApiResult<GifSearchResponse> {
  let mut __path = String::from("/gif");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
