// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::issue::create_issue_form::CreateIssueForm;
use crate::types::issue::create_issue_response::CreateIssueResponse;
use crate::types::database::issue::Issue;
use crate::types::issue::set_issue_status_request::SetIssueStatusRequest;

/// Count issues.
///
/// Requires `ViewIssues`, which only platform staff hold.
pub async fn count(client: &Client) -> ApiResult<u64> {
  let mut __path = String::from("/issue/count");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Report a new issue (severity, description, details, and 1–10 screenshots) recorded under the caller's own user.
///
/// Any authenticated user. Rejected when the platform is at its open-issue cap, and — when screenshots are attached — when the caller trips the per-user file-upload throttle.
pub async fn create(client: &Client, form: reqwest::multipart::Form) -> ApiResult<CreateIssueResponse> {
  let mut __path = String::from("/issue");
  client.request_multipart(Method::POST, &__path, None::<&()>, form).await
}
/// Fetch a single issue by uid.
///
/// Requires `ViewIssues`, which only platform staff hold.
pub async fn get(client: &Client, issue_uid: &str) -> ApiResult<Issue> {
  let mut __path = String::from("/issue/{issue_uid}");
  __path = __path.replace("{issue_uid}", &encode_path(issue_uid));
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List issues.
///
/// Requires `ViewIssues`, which only platform staff hold.
pub async fn list(client: &Client) -> ApiResult<Vec<Issue>> {
  let mut __path = String::from("/issue");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Serve a screenshot file attached to an issue.
///
/// Requires `ViewIssues`, which only platform staff hold.
pub async fn screenshot(client: &Client, issue_uid: &str, screenshot_uid: &str) -> ApiResult<Vec<u8>> {
  let mut __path = String::from("/issue/{issue_uid}/screenshot/{screenshot_uid}");
  __path = __path.replace("{issue_uid}", &encode_path(issue_uid));
  __path = __path.replace("{screenshot_uid}", &encode_path(screenshot_uid));
  client.request_bytes(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Update the status of an issue.
///
/// Requires `ManageIssues`, which only platform staff hold.
pub async fn set_status(client: &Client, issue_uid: &str, body: &SetIssueStatusRequest) -> ApiResult<()> {
  let mut __path = String::from("/issue/{issue_uid}/status");
  __path = __path.replace("{issue_uid}", &encode_path(issue_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
