// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::event::get_webhook_query::GetWebhookQuery;
use crate::types::event::set_webhook_request::SetWebhookRequest;
use crate::types::event::set_webhook_response::SetWebhookResponse;
use crate::types::database::webhook::Webhook;

/// Remove the group's outbound webhook, dropping its pending deliveries.
///
/// Requires `ManageWebhook` in the webhook's group.
pub async fn delete(client: &Client, webhook_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/event/webhook/{webhook_uid}");
  __path = __path.replace("{webhook_uid}", &encode_path(webhook_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch the group's outbound webhook configuration (the secret is never
/// returned here).
///
/// Requires `ViewWebhook` in the target group; group-scoped API keys read their own group, others must name it.
pub async fn get(client: &Client, query: &GetWebhookQuery) -> ApiResult<Option<Webhook>> {
  let mut __path = String::from("/event/webhook");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Configure (create or replace) the group's outbound webhook: the group's
/// events (optionally narrowed by kind/channel filters) are POSTed to the
/// URL in signed batches.
///
/// Requires `ManageWebhook` in the target group; group-scoped API keys configure their own group, others must name it.
pub async fn set(client: &Client, body: &SetWebhookRequest) -> ApiResult<SetWebhookResponse> {
  let mut __path = String::from("/event/webhook");
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
