// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::event::get_webhook_query::GetWebhookQuery;
use crate::types::event::set_webhook_request::SetWebhookRequest;
use crate::types::event::set_webhook_response::SetWebhookResponse;
use crate::types::database::webhook::Webhook;

/// Remove the group's outbound webhook, dropping its pending deliveries.
///
/// Requires `ManageWebhook` in the webhook's group.
pub async fn delete(__client: &crate::runtime::Client, webhook_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/event/webhook/{webhook_uid}");
  __path = __path.replace("{webhook_uid}", &crate::runtime::encode_path(webhook_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch the group's outbound webhook configuration (the secret is never
/// returned here).
///
/// Requires `ViewWebhook` in the target group; group-scoped API keys read their own group, others must name it.
pub async fn get(__client: &crate::runtime::Client, __query: &GetWebhookQuery) -> crate::runtime::ApiResult<Option<Webhook>> {
  let mut __path = String::from("/event/webhook");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Configure (create or replace) the group's outbound webhook: the group's
/// events (optionally narrowed by kind/channel filters) are POSTed to the
/// URL in signed batches.
///
/// Requires `ManageWebhook` in the target group; group-scoped API keys configure their own group, others must name it.
pub async fn set(__client: &crate::runtime::Client, __body: &SetWebhookRequest) -> crate::runtime::ApiResult<SetWebhookResponse> {
  let mut __path = String::from("/event/webhook");
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
