// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::engagement::comment_message_request::CommentMessageRequest;
use crate::types::engagement::list_mentions_query::ListMentionsQuery;
use crate::types::database::mention::Mention;

/// Poll the mention feed: mentions with `id` greater than `since_id`, oldest
/// first (Instagram only — the account mentioned in captions or comments).
///
/// Requires `ViewComments`; the feed covers only mentions of groups where the caller holds it.
pub async fn list(client: &Client, query: &ListMentionsQuery) -> ApiResult<Vec<Mention>> {
  let mut __path = String::from("/mention");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Reply to an Instagram mention (in the mentioned media's comments).
///
/// Requires `ReplyComments` in the account's group.
pub async fn reply(client: &Client, social_account_uid: &str, mention_uid: &str, body: &CommentMessageRequest) -> ApiResult<()> {
  let mut __path = String::from("/social-account/{social_account_uid}/mention/{mention_uid}/reply");
  __path = __path.replace("{social_account_uid}", &encode_path(social_account_uid));
  __path = __path.replace("{mention_uid}", &encode_path(mention_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
