// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::insight::insight_query_request::InsightQueryRequest;
use crate::types::insight::insight_query_response::InsightQueryResponse;

/// Aggregate collected metrics over many accounts of one channel, by day,
/// week or month. Only accounts of the declared channel take part; a named
/// account of another channel is refused. Breakdown metrics (demographics)
/// cannot be aggregated.
///
/// Requires `ViewInsights` in every group the query reaches; accounts the caller may not see are refused.
pub async fn query(__client: &crate::runtime::Client, __body: &InsightQueryRequest) -> crate::runtime::ApiResult<InsightQueryResponse> {
  let mut __path = String::from("/insight/query");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
