// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_200::Number1_200;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.post"))]
pub struct ListPostsQuery {
  pub group_uid: Option<Uid>,
  pub social_account_uid: Option<Uid>,
  pub limit: Option<Number1_200>,
}
