// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_200::Number1_200;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.post"))]
pub struct ListSocialPostsQuery {
  pub group_uid: Option<Uid>,
  pub social_account_uid: Option<Uid>,
  /// The platform post of one hub post.
  pub post_uid: Option<Uid>,
  /// Only posts with at least one third-party comment the account has not answered.
  pub unanswered_only: bool,
  /// Page cursor: only posts published strictly before this instant (ms).
  pub before: Option<Timestamp>,
  pub limit: Option<Number1_200>,
}
