// This file was generated by tapir. Do not edit this file manually.
pub mod create_post_request;
pub mod list_posts_query;
pub mod list_social_posts_query;
pub mod set_post_comments_request;
pub mod set_post_hidden_request;
pub mod set_post_pinned_request;
pub mod social_post_summary_query;
pub mod update_post_request;
