// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.post"))]
pub struct PostInsightsQuery {
  /// Meta metric names (comma-separated); defaults per media kind.
  pub metrics: Option<String>,
  pub period: Option<String>,
}
