// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Channel-tagged comment toggle — the one edit Instagram's API supports;
/// facebook has no per-post comment toggle, so its shape does not
/// deserialize. The `channel` must match the post's.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.post"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum SetPostCommentsRequest {
  Instagram {
    enabled: bool,
  },
}
