// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Channel-tagged pin toggle — only facebook Page timelines have a pin
/// surface, so no other channel's shape deserializes. The `channel` must
/// match the post's.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.post"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum SetPostPinnedRequest {
  Facebook {
    pinned: bool,
  },
}
