// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.uptime"))]
pub struct ServerUptimeRangeQuery {
  pub since: Timestamp,
  pub until: Timestamp,
}
