// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Row counts by verdict — always derived from the rows, never stored, so
/// they cannot drift from the ledger they summarize.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.contact_import"))]
pub struct ContactImportCounts {
  pub total: u32,
  pub pending: u32,
  pub missing_phone: u32,
  pub invalid_phone: u32,
  pub invalid_name: u32,
  pub duplicate_in_file: u32,
  pub imported: u32,
  pub not_on_whatsapp: u32,
  pub check_failed: u32,
  pub skipped: u32,
}
