// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::name::Name;
use crate::types::primitives::text1_255::Text1_255;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.contact_import"))]
pub struct UploadContactImportForm {
  /// The operator's name for the batch.
  pub name: Name,
  /// The file's own name, for provenance — the multipart layer deliberately
  /// keeps client filenames out of the stored part, so it rides as a field.
  pub filename: Text1_255,
  /// The accounts the load distributes over, comma-separated uids. Every one
  /// must be a native whatsapp account of one same group, which becomes the
  /// import's group.
  pub social_account_uids: String,
  /// 0-based index of the phone column in the header row.
  pub phone_column: String,
  /// 0-based index of the name column; omit for no name column.
  pub name_column: Option<String>,
  /// Country calling code bare numbers are read against; defaults to `55`.
  pub default_calling_code: Option<String>,
  #[cfg_attr(feature = "tapir", tapir(type = "File", rust = "Vec<u8>"))]
  pub file: Vec<u8>,
}
