// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct BusinessCallsQuery {
  /// The location's v1 name, `locations/{id}`.
  pub location: String,
  pub page_token: Option<String>,
}
