// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct BusinessPerformanceQuery {
  /// The location's v1 name, `locations/{id}`.
  pub location: String,
  /// Comma-separated metric names (see `DAILY_METRICS` in the bindings); at
  /// most 10 per call. Omitted = the core set (impressions, conversations,
  /// direction requests, call clicks, website clicks).
  pub metrics: Option<String>,
  /// Range bounds, inclusive, resolved to UTC calendar dates.
  pub start: Timestamp,
  pub end: Timestamp,
}
