// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::busy_period::BusyPeriod;

/// A calendar's free/busy outcome. `error` present means the calendar could
/// not be read — never treat it as free.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct CalendarBusy {
  pub calendar_id: String,
  pub busy: Vec<BusyPeriod>,
  pub error: Option<String>,
}
