// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::media_item::MediaItem;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct CreateBusinessMediaRequest {
  /// The location's v4 name, `accounts/{id}/locations/{id}`.
  pub location: String,
  pub item: MediaItem,
}
