// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct FreeBusyRequest {
  pub calendar_ids: Vec<String>,
  pub time_min: Timestamp,
  pub time_max: Timestamp,
  /// IANA name for the response intervals; UTC when omitted.
  pub time_zone: Option<String>,
}
