// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google_account::calendar_busy::CalendarBusy;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct FreeBusyResponse {
  /// One outcome per requested calendar, in request order.
  pub calendars: Vec<CalendarBusy>,
}
