// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google_account::google_capability::GoogleCapability;

/// What a stashed Google grant covers, for the capability-selection screen.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct GoogleReview {
  pub email: String,
  pub name: String,
  pub avatar_url: Option<String>,
  /// The account is already registered in the target group — confirming
  /// refreshes its grant and replaces its enabled capabilities.
  pub connected: bool,
  /// Capabilities the grant covers — the selectable set. Incremental auth
  /// unions grants, so this may exceed what was just requested.
  pub granted: Vec<GoogleCapability>,
  /// Capabilities the admin asked for when starting the flow — the
  /// pre-checked set.
  pub requested: Vec<GoogleCapability>,
}
