// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct ListBusinessReviewsQuery {
  /// The location's v4 name, `accounts/{id}/locations/{id}`.
  pub location: String,
  /// Page size; capped at 50 (Google's limit), default 50.
  pub page_size: Option<u32>,
  pub page_token: Option<String>,
  /// `update_time desc` (default), `rating` or `rating desc`.
  pub order_by: Option<String>,
}
