// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_2500::Number1_2500;
use crate::types::primitives::timestamp::Timestamp;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct ListCalendarEventsQuery {
  /// The calendar to list (its id — usually an email address).
  pub calendar_id: String,
  pub time_min: Timestamp,
  pub time_max: Timestamp,
  /// Free-text search over the events.
  pub q: Option<String>,
  /// Continues a previous page (`next_page_token`).
  pub page_token: Option<String>,
  /// Page size; capped at 2500 (Google's limit), default 250.
  /// Bounded by the type like every other page size, rather than silently
  /// clamped: a caller asking for more than Google's own 2500 ceiling gets
  /// told so. `Number` deserialization enforces it.
  pub max_results: Option<Number1_2500>,
}
