// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::local_post::LocalPost;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google_account"))]
pub struct UpdateBusinessPostRequest {
  /// The post's v4 name, `accounts/{id}/locations/{id}/localPosts/{id}`.
  pub post: String,
  /// The new values for the masked fields.
  pub update: LocalPost,
  /// Comma-separated camelCase fields to write (e.g. `summary,callToAction`).
  pub update_mask: String,
}
