// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::google_account::connect_google_request::ConnectGoogleRequest;
use crate::types::google_account::connect_google_response::ConnectGoogleResponse;
use crate::types::google_account::google_callback_query::GoogleCallbackQuery;
use crate::types::google_account::google_confirm_request::GoogleConfirmRequest;
use crate::types::google_account::google_review::GoogleReview;
use crate::types::google_account::google_review_query::GoogleReviewQuery;

/// Google OAuth redirect target: consumes the state, exchanges the code, and
/// stashes the grant snapshot for review — nothing is registered yet; always
/// redirects the browser back to the frontend, with a review token on
/// success.
///
/// Public — no authentication required; authorization comes from the one-shot state token issued by `google.connect`.
pub async fn callback(client: &Client, query: &GoogleCallbackQuery) -> ApiResult<()> {
  let mut __path = String::from("/google/callback");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Start the Google OAuth flow for a group with the chosen capabilities
/// (calendar, business profile), returning the consent dialog URL; the
/// granted account is connected to the group by the callback.
///
/// Requires `ConnectSocialAccounts` in the named group.
pub async fn connect(client: &Client, body: &ConnectGoogleRequest) -> ApiResult<ConnectGoogleResponse> {
  let mut __path = String::from("/google/connect");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Register (or refresh) the account from a stashed grant, enabling exactly
/// the chosen capabilities (one-shot). A granted-but-unchosen capability
/// stays out of the hub until a future connect enables it.
///
/// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
pub async fn connect_confirm(client: &Client, body: &GoogleConfirmRequest) -> ApiResult<()> {
  let mut __path = String::from("/google/connect/confirm");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Load a stashed Google grant for the capability-selection screen: the
/// account's identity plus which capabilities the grant covers and which
/// were requested. Repeatable; only confirm consumes the stash.
///
/// Requires `ConnectSocialAccounts` in the group the stashed grant targets.
pub async fn connect_review(client: &Client, query: &GoogleReviewQuery) -> ApiResult<GoogleReview> {
  let mut __path = String::from("/google/connect/review");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
