// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::insight::insight_history_query::InsightHistoryQuery;
use crate::types::post::list_social_posts_query::ListSocialPostsQuery;
use crate::types::domain::social_post::SocialPost;
use crate::types::insight::social_post_insight_history::SocialPostInsightHistory;
use crate::types::domain::social_post_summary::SocialPostSummary;
use crate::types::post::social_post_summary_query::SocialPostSummaryQuery;

/// Fetch one platform post by uid.
///
/// Requires `ViewPosts` in the post's group.
pub async fn get(__client: &crate::runtime::Client, social_post_uid: &str) -> crate::runtime::ApiResult<SocialPost> {
  let mut __path = String::from("/social-post/{social_post_uid}");
  __path = __path.replace("{social_post_uid}", &crate::runtime::encode_path(social_post_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Day-by-day history of a platform post's collected metrics, in its channel's
/// own vocabulary. Posts are re-read on a schedule that slows with age (every
/// 5 minutes in the first day, every 3 hours after a month), so the newest day
/// is often still partial.
///
/// Requires `ViewInsights` in the group of the post's account.
pub async fn insights_history(__client: &crate::runtime::Client, social_post_uid: &str, __query: &InsightHistoryQuery) -> crate::runtime::ApiResult<SocialPostInsightHistory> {
  let mut __path = String::from("/social-post/{social_post_uid}/insight/history");
  __path = __path.replace("{social_post_uid}", &crate::runtime::encode_path(social_post_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List the posts that stand on the platforms, newest first: every post the
/// hub knows about an account, published through it or not, with the
/// platform's comment and like counts and how many third-party comments the
/// account has not answered. `until` pages backwards.
///
/// Requires `ViewPosts`; the list covers only posts of groups where the caller holds it.
pub async fn list(__client: &crate::runtime::Client, __query: &ListSocialPostsQuery) -> crate::runtime::ApiResult<Vec<SocialPost>> {
  let mut __path = String::from("/social-post");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Totals over the platform posts in scope: how many there are, their
/// comments and the ones still unanswered. The list's pages never add up to
/// these; this does.
///
/// Requires `ViewPosts`; counts only posts of groups where the caller holds it, narrowed by the named groups and accounts when given.
pub async fn summary(__client: &crate::runtime::Client, __query: &SocialPostSummaryQuery) -> crate::runtime::ApiResult<SocialPostSummary> {
  let mut __path = String::from("/social-post/summary");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
