// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// What still acts on an account from inside its group, and so has to travel
/// with it when the account changes group. Finished work stays behind: a
/// canceled campaign, or a contact import that is done or canceled, is not
/// counted.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct AccountReferences {
  /// GoHighLevel locations delivering into this account.
  pub ghl_locations: u64,
  /// Campaigns sending only from this account.
  pub campaigns: u64,
  /// Contact imports loading only into this account.
  pub contact_imports: u64,
  /// Campaigns that also send from other accounts of the group, which cannot follow it.
  pub shared_campaigns: u64,
  /// Contact imports that also load into other accounts of the group, which cannot follow it.
  pub shared_contact_imports: u64,
}
