// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// How activity over time is bucketed: weeks start on Monday and months on
/// their first day, both in the query's own offset.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum ActivityGranularity {
  Hour,
  Day,
  Week,
  Month,
}
