// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Where a campaign stands in its lifecycle. Config, wheel, accounts and
/// queue are editable while `Draft`, `Paused` or `Done`; `start` moves it to
/// `Running`, and the dispatcher advances each participating account of a
/// `Running` campaign by at most one send per tick.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum CampaignStatus {
  /// Being assembled; nothing has been sent.
  Draft,
  /// The dispatcher is dripping sends inside the configured window.
  Running,
  /// Held: queued recipients stay queued, the dispatcher skips it.
  Paused,
  /// Every recipient settled, or `ends_at` passed. A rest, not an end:
  /// editable again, and a new start runs whatever queue is left.
  Done,
  /// Canceled by the operator; queued recipients became `canceled`. Terminal.
  Canceled,
}
