// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Why a recipient was ruled out — the safety rails, exhaustively. A rail
/// that merely *defers* a recipient (its account offline or day-capped) is
/// not here: those rows stay `pending` and come back.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum CampaignSkipReason {
  /// Another campaign (or this one) messaged the number within the
  /// cooldown.
  InCooldown,
  /// The rendered template still carried an unresolved `{{variável}}` — no
  /// name is known for the number.
  MissingVariable,
  /// The campaign's end date passed with the recipient still queued.
  CampaignEnded,
}
