// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// The platform behind a channel, which fixes what a conversation allows:
/// Messenger rules for `facebook`, Instagram messaging rules for
/// `instagram`, WhatsApp rules for `whatsapp` (the linked-device transport
/// lifts the window and template rules).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum ChannelFamily {
  Facebook,
  Instagram,
  Whatsapp,
}
