// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::email_queue_status::EmailQueueStatus;
use crate::types::domain::email_template_name::EmailTemplateName;
use crate::types::primitives::timestamp::Timestamp;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct EmailQueueItem {
  pub id: u64,
  pub to_email: String,
  pub to_name: Option<String>,
  pub subject: String,
  pub template_name: EmailTemplateName,
  pub status: EmailQueueStatus,
  pub attempts: u8,
  /// When set, the worker won't retry this row until `next_retry_at <= now`.
  /// `NULL` means "ready immediately" (fresh enqueue or operator-triggered retry).
  pub next_retry_at: Option<Timestamp>,
  pub error_message: Option<String>,
  pub created_at: Timestamp,
  pub sent_at: Option<Timestamp>,
}
