// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// The kind of a [`HubEvent`], named exactly as its `event` tag.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum EventKind {
  MessageReceived,
  MessageSent,
  MessageQueued,
  MessageCanceled,
  MessageReaction,
  MessageDelivered,
  MessageRead,
  MessageFailed,
  MessageUpdated,
  MessageDeleted,
  ParticipantPresence,
  CommentReceived,
  CommentUpdated,
  CommentDeleted,
  SocialPostUpdated,
  PostPublished,
  PostFailed,
  ConversationUpdated,
  ConversationCleared,
  ConversationRemoved,
  ContactPresence,
  CallRinging,
  CallUpdated,
  CallEnded,
  AccountUpdated,
  AccountRemoved,
  ReviewReceived,
}
