// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Facebook Page account metrics as the alternate gateway reports them.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum FacebookAltAccountMetric {
  Followers,
  PageMediaView,
  PageViewsTotal,
  PagePostEngagements,
  PageVideoViews,
  PageVideoViewTime,
  PageFollows,
  FollowersGained,
  FollowersLost,
}
