// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::facebook_post_metric::FacebookPostMetric;
use crate::types::domain::insight_point::InsightPoint;

/// One metric as a day-by-day series.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct FacebookPostSeries {
  pub metric: FacebookPostMetric,
  pub points: Vec<InsightPoint>,
}
