// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// The kinds a Facebook Page post can be, as the hub published it.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum FacebookMediaKind {
  Text,
  Link,
  Photos,
  Video,
  Reel,
  PhotoStory,
  VideoStory,
}
