// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::insight_point::InsightPoint;
use crate::types::domain::instagram_post_metric::InstagramPostMetric;

/// One metric as a day-by-day series.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct InstagramPostSeries {
  pub metric: InstagramPostMetric,
  pub points: Vec<InsightPoint>,
}
