// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::instagram_alt_post_metric::InstagramAltPostMetric;
use crate::types::primitives::timestamp::Timestamp;

/// One aggregated period of one metric across the queried subjects.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct InstagramAltPostBucket {
  pub period_start: Timestamp,
  pub metric: InstagramAltPostMetric,
  pub value: f64,
  /// How many subjects — accounts, or posts — contributed rows to the period.
  pub subjects: i64,
}
