// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::instagram_user_tag::InstagramUserTag;
use crate::types::domain::media_ref::MediaRef;

/// One carousel item: exactly one of `image` / `video`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct InstagramCarouselItem {
  pub image: Option<MediaRef>,
  pub video: Option<MediaRef>,
  pub user_tags: Vec<InstagramUserTag>,
}
