// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::instagram_carousel_item::InstagramCarouselItem;
use crate::types::meta::instagram_user_tag::InstagramUserTag;
use crate::types::domain::media_ref::MediaRef;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum InstagramMedia {
  Image {
    image: MediaRef,
    user_tags: Vec<InstagramUserTag>,
    alt_text: Option<String>,
  },
  /// 2–10 items shown as a swipeable carousel; items may be images or videos
  /// (video items process asynchronously before the album can publish).
  Carousel {
    items: Vec<InstagramCarouselItem>,
  },
  Reel {
    video: MediaRef,
    /// Also show the reel in the profile feed grid (defaults to Meta's own
    /// default when omitted).
    share_to_feed: Option<bool>,
    /// A custom cover image.
    cover: Option<MediaRef>,
  },
  /// A 24h story: exactly one of `image` / `video`.
  Story {
    image: Option<MediaRef>,
    video: Option<MediaRef>,
  },
}
