// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::text0_2048::Text0_2048;
use crate::types::primitives::text0_255::Text0_255;
use crate::types::primitives::text0_8000::Text0_8000;

/// Per-category detail payload. The shape is strict (the variant is keyed on
/// `category` and known fields are typed), but submission is lenient: every
/// field is optional and the `extra` object holds any additional keys the
/// reporter wants to attach — "as much detail as he wants".
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "category")]
#[serde(rename_all = "snake_case")]
pub enum IssueDetails {
  Bug {
    page_url: Option<Text0_2048>,
    steps_to_reproduce: Option<Text0_8000>,
    expected: Option<Text0_8000>,
    actual: Option<Text0_8000>,
    #[cfg_attr(feature = "tapir", tapir(type = "Record<string, unknown>"))]
    extra: std::collections::HashMap<String, serde_json::Value>,
  },
  Performance {
    page_url: Option<Text0_2048>,
    duration_ms: Option<u64>,
    #[cfg_attr(feature = "tapir", tapir(type = "Record<string, unknown>"))]
    extra: std::collections::HashMap<String, serde_json::Value>,
  },
  Suggestion {
    page_url: Option<Text0_2048>,
    #[cfg_attr(feature = "tapir", tapir(type = "Record<string, unknown>"))]
    extra: std::collections::HashMap<String, serde_json::Value>,
  },
  Ui {
    page_url: Option<Text0_2048>,
    component: Option<Text0_255>,
    #[cfg_attr(feature = "tapir", tapir(type = "Record<string, unknown>"))]
    extra: std::collections::HashMap<String, serde_json::Value>,
  },
  Other {
    #[cfg_attr(feature = "tapir", tapir(type = "Record<string, unknown>"))]
    extra: std::collections::HashMap<String, serde_json::Value>,
  },
}
