// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::channel::Channel;
use crate::types::domain::message::Message;
use crate::types::primitives::uid::Uid;

/// A message enriched with its channel/group context — the squashed shape
/// CRMs consume from both the polling feed and the webhook fan-out.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct MessageWithContext {
  #[serde(flatten)]
  pub message: Message,
  pub channel: Channel,
  pub group_uid: Uid,
}
