// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::message_tag::MessageTag;
use crate::types::domain::messenger_content::MessengerContent;
use crate::types::domain::quick_reply::QuickReply;

/// Messenger/Instagram DM payload (Send API). Attachments carry no captions;
/// quick replies may attach to any content.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct MessengerSend {
  pub content: MessengerContent,
  /// A message tag that lifts the response window where the channel honors
  /// it (`GET /channel`, `response_window.lift`); refused on any other
  /// channel.
  pub tag: Option<MessageTag>,
  /// Up to 13 quick-reply chips.
  pub quick_replies: Option<Vec<QuickReply>>,
}
