// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// A reaction attached to a message. `reactor_id` is the platform participant
/// id (or the page/account id when the reaction came from the business side).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct MessageReaction {
  pub reactor_id: String,
  /// The unicode emoji; a Meta reaction name (e.g. `love`) is stored as its
  /// glyph. `None` when the platform sent neither a glyph nor a known name.
  pub emoji: Option<String>,
}
