// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::message_direction::MessageDirection;
use crate::types::domain::snippet_part::SnippetPart;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// One message matched by its text, with enough of its conversation to draw a
/// chat-list line without a second fetch.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct MessageSearchHit {
  pub uid: Uid,
  /// The thread's cursor — what an anchored load pages from.
  pub id: u64,
  pub conversation_uid: Uid,
  pub social_account_uid: Uid,
  /// The conversation's alias, the contact's name or their username, in that
  /// order; `None` when the contact carries none of them.
  pub conversation_name: Option<String>,
  /// The contact's platform id (wa_id, PSID, IGSID) and username, so a
  /// nameless conversation still reads as its phone or handle.
  pub participant_id: String,
  pub participant_username: Option<String>,
  pub participant_avatar_url: Option<String>,
  pub direction: MessageDirection,
  pub sent_at: Timestamp,
  /// The matched passage, split where the index found the terms.
  pub snippet: Vec<SnippetPart>,
}
