// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Which sound a new message plays in the operator's browser, if any. The
/// sounds themselves ship with the frontend; the choice is personal to the
/// operator and follows them across devices.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum MessageChime {
  SoundOne,
  SoundTwo,
  SoundThree,
  SoundFour,
  /// New messages make no sound.
  Off,
}
