// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::contact_card::ContactCard;
use crate::types::domain::template_button::TemplateButton;
use crate::types::domain::template_card::TemplateCard;
use crate::types::meta::whatsapp_template_send_component::WhatsappTemplateSendComponent;

/// Content the hub can send — the kinds a message is composed from. Most
/// kinds also arrive inbound (a received text is `Text` too); shapes that can
/// only arrive are [`InboundContent`]. Attachment URLs are public URLs the
/// caller supplies (out) or the CDN links the platform provides (in).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum OutboundContent {
  Text {
    text: String,
  },
  /// `caption` is whatsapp-only in both directions (facebook/instagram
  /// attachments carry no text).
  Image {
    url: String,
    caption: Option<String>,
  },
  /// A whatsapp sticker: a webp with no caption, told apart from a photo so a
  /// client can render it as one. Arrives on every whatsapp flavour; no
  /// channel has a send shape for it yet, so a forward is refused.
  Sticker {
    url: String,
  },
  Audio {
    url: String,
  },
  Video {
    url: String,
    caption: Option<String>,
  },
  /// A short looping clip played inline without sound — an mp4 the phone
  /// draws as a GIF bubble rather than a video. Sendable natively; the other
  /// channels have no gif shape, so a caller sends the same file to them as a
  /// plain video.
  Gif {
    url: String,
  },
  File {
    url: String,
    caption: Option<String>,
    filename: Option<String>,
  },
  /// A geographic point (whatsapp only).
  Location {
    latitude: f64,
    longitude: f64,
    name: Option<String>,
    address: Option<String>,
  },
  /// Shared contact cards (whatsapp only).
  Contacts {
    contacts: Vec<ContactCard>,
  },
  /// Whatsapp-only: a pre-approved message template — the only content
  /// deliverable outside the 24h customer-service window. `components` fills
  /// the approved definition's placeholders; a template with none takes `None`.
  Template {
    name: String,
    language: String,
    components: Option<Vec<WhatsappTemplateSendComponent>>,
  },
  /// Structured message: text with up to three buttons.
  Buttons {
    text: String,
    buttons: Vec<TemplateButton>,
  },
  /// Structured message: a horizontal carousel of cards (facebook/instagram
  /// only).
  Cards {
    cards: Vec<TemplateCard>,
  },
}
