// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// How a native whatsapp account announces itself online. An online presence
/// silences the paired phone's notifications and stamps every delivery
/// receipt as active, so the default follows the people actually looking.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum PresencePolicy {
  /// Online while an operator has one of the account's conversations open in
  /// the inbox; offline five minutes after the last one closes, on shutdown
  /// and when the account is disabled.
  FollowsOperator,
  /// Never announces online or typing: delivery receipts read as inactive
  /// and the paired phone keeps every notification. For accounts that only send
  /// through the api or campaigns.
  AlwaysInvisible,
}
