// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// What one bucket stands for: the thing a rule counts against, one counter
/// per distinct value. A rule may draw from several — a login attempt spends
/// from the caller's IP bucket *and* the e-mail's bucket, and is refused when
/// either runs dry.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum RateLimitBucket {
  /// One bucket per source IP address.
  Ip,
  /// One bucket per signed-in user.
  User,
  /// One bucket per api key.
  ApiKey,
  /// One bucket per e-mail address named in the request, whoever sends it.
  Email,
  /// One bucket per pending MFA challenge.
  UserMfaToken,
  /// One bucket per social account.
  SocialAccount,
  /// One bucket per group.
  Group,
  /// One bucket for the whole platform, shared by every caller.
  Platform,
}
