// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum RateLimitAction {
  /// A sign-in attempt; counted per source IP and per e-mail address.
  LoginAttempt,
  /// A password-reset request; counted per source IP and per e-mail address.
  UserPasswordReset,
  /// An MFA code check; counted per source IP and per pending challenge.
  UserMfaVerify,
  /// An MFA code sent by e-mail; counted per source IP and per pending
  /// challenge.
  UserMfaDispatchEmail,
  /// A file upload; counted per signed-in user.
  FileUpload,
  /// A connect, reconnect or re-enable of one whatsapp account; counted per
  /// account.
  SessionStart,
  /// A native whatsapp pairing started in a group; counted per group.
  NativePairing,
  /// A manual re-read of one social account's name and picture from its
  /// platform; counted per account.
  ProfileRefresh,
}
