// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

/// The tier a rule sits in, stored as tagged JSON in `rate_limit_rule.scope`.
/// For a group the per-caller tiers resolve top-down: its own rule, else the
/// override platform staff set for it, else the global default. "Global" is
/// the default every group runs under, not one shared bucket — buckets stay
/// per caller in those three tiers.
///
/// `shared` sits outside that chain: one bucket for the whole platform that
/// every caller draws from, checked on top of whatever per-caller tier is in
/// force. A target may carry both a shared rule and per-caller rules.
///
/// A group's own rule can only tighten what applies to it. A write above the
/// ceiling is refused, and should the ceiling later drop beneath an existing
/// own rule, resolution ignores that rule until it is brought back under.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "tier")]
#[serde(rename_all = "snake_case")]
pub enum RateLimitScope {
  /// One bucket for the whole platform, shared by every caller; set by
  /// platform staff.
  Shared,
  /// The default for every group; set by platform staff.
  Global,
  /// Platform staff replacing the default for one group.
  Override {
    group_uid: Uid,
  },
  /// The group tightening its own limit, at or below its ceiling.
  Own {
    group_uid: Uid,
  },
}
