// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::facebook_alt_social_post::FacebookAltSocialPost;
use crate::types::domain::facebook_social_post::FacebookSocialPost;
use crate::types::domain::instagram_alt_social_post::InstagramAltSocialPost;
use crate::types::domain::instagram_social_post::InstagramSocialPost;

/// What a channel knows about a post on its platform beyond the columns every
/// channel shares. Channel-tagged like `PostContent`: each variant is owned by
/// its channel and evolves alone.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum SocialPostDetail {
  Facebook(FacebookSocialPost),
  Instagram(InstagramSocialPost),
  FacebookAlt(FacebookAltSocialPost),
  InstagramAlt(InstagramAltSocialPost),
}
