// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::template_button::TemplateButton;

/// One card of a generic template carousel.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct TemplateCard {
  pub title: String,
  pub subtitle: Option<String>,
  pub image_url: Option<String>,
  pub buttons: Vec<TemplateButton>,
}
