// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// How the hub reaches a channel's platform.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(rename_all = "snake_case")]
pub enum Transport {
  /// Meta's own APIs with the hub's app: the official channels.
  Meta,
  /// The alternate gateway, standing in for the hub's app while it awaits
  /// review; same platform rules as [`Transport::Meta`].
  Gateway,
  /// A linked-device session (whatsmeow): a regular account, no platform
  /// business rules.
  Native,
}
