// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// One operator's notification choices on one social account, personal to
/// them: muting a line for oneself never silences a colleague. An account
/// without an entry rings both.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
pub struct UserAccountNotification {
  pub social_account_uid: Uid,
  /// New messages on the account ring the message sound.
  pub message_sound: bool,
  /// Incoming calls on the account raise the call alert: popup and ringtone.
  pub call_alert: bool,
  pub updated_at: Timestamp,
}
