// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::contact_card::ContactCard;
use crate::types::domain::quick_reply::QuickReply;
use crate::types::domain::template_button::TemplateButton;
use crate::types::meta::whatsapp_template_send_component::WhatsappTemplateSendComponent;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum WhatsappContent {
  Text {
    text: String,
  },
  /// Text with quick-reply chips riding an interactive message: 1–3 chips
  /// become reply buttons, 4–10 a list.
  QuickReplies {
    text: String,
    quick_replies: Vec<QuickReply>,
  },
  Image {
    url: String,
    caption: Option<String>,
  },
  /// `voice` sends it as a voice note (push-to-talk); the file must then be
  /// ogg/opus, which WhatsApp draws with the waveform. A plain audio file
  /// arrives as an attachment.
  Audio {
    url: String,
    voice: bool,
  },
  Video {
    url: String,
    caption: Option<String>,
  },
  File {
    url: String,
    caption: Option<String>,
    filename: Option<String>,
  },
  Location {
    latitude: f64,
    longitude: f64,
    name: Option<String>,
    address: Option<String>,
  },
  Contacts {
    contacts: Vec<ContactCard>,
  },
  /// A pre-approved template. `components` fills the approved definition's
  /// placeholders.
  Template {
    name: String,
    language: String,
    components: Option<Vec<WhatsappTemplateSendComponent>>,
  },
  /// Reply buttons (all postback, 1–3) or exactly one URL button (CTA) —
  /// WhatsApp has no mixed sets.
  Buttons {
    text: String,
    buttons: Vec<TemplateButton>,
  },
}
