// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::message_tag::MessageTag;

/// What a send may carry to pass a closed [`ResponseWindow`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.domain"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum WindowLift {
  /// Nothing: the hub waits for the contact.
  None,
  /// An approved template.
  Template,
  /// A message tag, honored for `hours` after the contact's last message.
  Tag {
    tag: MessageTag,
    hours: u32,
  },
}
