// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::email::Email;
use crate::types::types::membership_role::MembershipRole;
use crate::types::primitives::name::Name;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// One membership, carrying the identity fields needed to recognize the person
/// behind it — never the user record itself, which answers to `ViewUsers` and
/// is platform staff's alone.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.group"))]
pub struct GroupMemberResponse {
  pub user_uid: Uid,
  pub email: Email,
  pub name: Name,
  pub enabled: bool,
  pub last_seen: Option<Timestamp>,
  pub role: MembershipRole,
  pub member_since: Timestamp,
}
