// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.group"))]
pub struct SetGroupLogoResponse {
  /// The stored logo, now `Group.logo_uid`.
  pub logo_uid: Uid,
}
