// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::database::email_queue_item::EmailQueueItem;
use crate::types::mailing::email_queue_list_query::EmailQueueListQuery;

/// List queued emails, optionally filtered by delivery status.
///
/// Requires `ManageEmailQueue`, which only platform staff hold.
pub async fn list(client: &Client, query: &EmailQueueListQuery) -> ApiResult<Vec<EmailQueueItem>> {
  let mut __path = String::from("/mail-queue");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Remove a queued email from the delivery queue. An email that carried a
/// subscriber and had not been sent flips that record's email status to
/// failed. An email already handed to the mail server is refused — it settles
/// on its own.
///
/// Requires `ManageEmailQueue`, which only platform staff hold.
pub async fn remove(client: &Client, id: &str) -> ApiResult<()> {
  let mut __path = String::from("/mail-queue/{id}");
  __path = __path.replace("{id}", &encode_path(id));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Reset a failed queued email so the worker attempts delivery again. A
/// subscriber record goes back to pending-send.
///
/// Requires `ManageEmailQueue`, which only platform staff hold.
pub async fn retry(client: &Client, id: &str) -> ApiResult<()> {
  let mut __path = String::from("/mail-queue/{id}/retry");
  __path = __path.replace("{id}", &encode_path(id));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
