// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::database::action_rate_limit_rule::ActionRateLimitRule;
use crate::types::rate_limit::create_action_rate_limit_request::CreateActionRateLimitRequest;
use crate::types::rate_limit::create_action_rate_limit_response::CreateActionRateLimitResponse;
use crate::types::rate_limit::update_action_rate_limit_request::UpdateActionRateLimitRequest;

/// Create a platform-wide action rate-limit rule for a given limited action.
///
/// Requires `CreateRateLimits`, which only platform staff hold.
pub async fn create(__client: &crate::runtime::Client, __body: &CreateActionRateLimitRequest) -> crate::runtime::ApiResult<CreateActionRateLimitResponse> {
  let mut __path = String::from("/rate-limit/action");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Delete an action rate-limit rule by uid.
///
/// Requires `DeleteRateLimits`, which only platform staff hold.
pub async fn delete(__client: &crate::runtime::Client, rule_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/rate-limit/action/{rule_uid}");
  __path = __path.replace("{rule_uid}", &crate::runtime::encode_path(rule_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch a single action rate-limit rule by uid.
///
/// Requires `ViewRateLimits`, which only platform staff hold.
pub async fn get(__client: &crate::runtime::Client, rule_uid: &str) -> crate::runtime::ApiResult<ActionRateLimitRule> {
  let mut __path = String::from("/rate-limit/action/{rule_uid}");
  __path = __path.replace("{rule_uid}", &crate::runtime::encode_path(rule_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List all action rate-limit rules.
///
/// Requires `ViewRateLimits`, which only platform staff hold.
pub async fn list(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<Vec<ActionRateLimitRule>> {
  let mut __path = String::from("/rate-limit/action");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Update the limits of an existing action rate-limit rule.
///
/// Requires `UpdateRateLimits`, which only platform staff hold.
pub async fn update(__client: &crate::runtime::Client, rule_uid: &str, __body: &UpdateActionRateLimitRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/rate-limit/action/{rule_uid}");
  __path = __path.replace("{rule_uid}", &crate::runtime::encode_path(rule_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
