// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::campaign_recipient_status::CampaignRecipientStatus;
use crate::types::domain::message_status::MessageStatus;

/// One recipient-status × message-status cell of the stats join.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.campaign"))]
pub struct CampaignStatRow {
  pub recipient_status: CampaignRecipientStatus,
  /// The pointed message's own status; `null` for never-dispatched rows.
  pub message_status: Option<MessageStatus>,
  pub count: u32,
}
