// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::name::Name;
use crate::types::types::outbound_content::OutboundContent;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// A template as the API shows it: the stored JSON decoded into its parts.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.campaign"))]
pub struct CampaignTemplateResponse {
  pub uid: Uid,
  pub campaign_uid: Uid,
  /// The linear rotation order.
  pub position: u32,
  pub label: Option<Name>,
  pub parts: Vec<OutboundContent>,
  pub created_at: Timestamp,
}
