// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::name::Name;
use crate::types::primitives::uid::Uid;

/// A new draft: identity only. The schedule starts from workable defaults
/// (30–90s, 09:00–18:00 seg–sáb, BRT) and is edited in place.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.campaign"))]
pub struct CreateCampaignRequest {
  /// Required for users and platform keys; group-bound keys imply their group.
  pub group_uid: Option<Uid>,
  pub name: Name,
}
