// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::campaign_recipient_status::CampaignRecipientStatus;
use crate::types::primitives::number1_500::Number1_500;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.campaign"))]
pub struct ListRecipientsQuery {
  pub status: Option<CampaignRecipientStatus>,
  /// Keyset cursor: only rows with `id` strictly greater are returned.
  pub after_id: Option<u64>,
  pub limit: Option<Number1_500>,
}
