// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Queued recipients to drop. Rows that already ran (sent, failed, skipped,
/// canceled) are history and stay.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.campaign"))]
pub struct RemoveRecipientsRequest {
  pub recipient_ids: Vec<u64>,
}
