// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.campaign"))]
pub struct TestSendRequest {
  pub template_uid: Uid,
  /// A conversation of the campaign's group, on a whatsapp account, to
  /// receive the rendered template, now, outside any schedule.
  pub conversation_uid: Uid,
}
