// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::date::Date;
use crate::types::google::hourly_call_metrics::HourlyCallMetrics;
use crate::types::google::weekday_call_metrics::WeekdayCallMetrics;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct AggregateCallMetrics {
  pub missed_calls_count: u32,
  pub answered_calls_count: u32,
  #[cfg_attr(feature = "tapir", tapir(optional))]
  pub hourly_metrics: Vec<HourlyCallMetrics>,
  #[cfg_attr(feature = "tapir", tapir(optional))]
  pub weekday_metrics: Vec<WeekdayCallMetrics>,
  pub start_date: Option<Date>,
  pub end_date: Option<Date>,
}
