// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// A Business Profile account (`accounts/{id}`) — personal, location group or
/// organization. The account is the v4 path root for reviews/posts/media.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct BusinessAccount {
  /// Resource name, `accounts/{account_id}`.
  pub name: String,
  pub account_name: Option<String>,
  #[serde(rename = "type")]
  pub account_type: Option<String>,
  pub role: Option<String>,
  pub verification_state: Option<String>,
}
