// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Post button: `action_type` is `BOOK`, `ORDER`, `SHOP`, `LEARN_MORE`,
/// `SIGN_UP` or `CALL` (the latter needs no url).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct CallToAction {
  pub action_type: Option<String>,
  pub url: Option<String>,
}
