// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::dated_value::DatedValue;

/// One metric's day-by-day series, flattened from Google's nested envelope.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct DailyMetricSeries {
  pub daily_metric: String,
  pub dated_values: Vec<DatedValue>,
}
