// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Calendar date (proto3 `google.type.Date`): zero-valued components are
/// omitted from the JSON, hence the defaults.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct Date {
  pub year: i32,
  pub month: u32,
  pub day: u32,
}
