// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::event_attendee::EventAttendee;
use crate::types::google::event_date_time::EventDateTime;
use crate::types::google::extended_properties::ExtendedProperties;

/// Mutable event payload for insert/patch. Only set fields are sent — which
/// also means a PATCH can never *clear* a field.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct EventInput {
  pub summary: Option<String>,
  pub description: Option<String>,
  pub location: Option<String>,
  pub start: Option<EventDateTime>,
  pub end: Option<EventDateTime>,
  pub attendees: Option<Vec<EventAttendee>>,
  pub extended_properties: Option<ExtendedProperties>,
}
