// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// App-private key/value labels carried on an event. `private` is visible only
/// to the connected account's grant, so it is where a caller stamps its own
/// identifier for whoever booked the event — that label can then be filtered
/// server-side, making Google the source of truth instead of a local mirror.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct ExtendedProperties {
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub private: std::collections::HashMap<String, String>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub shared: std::collections::HashMap<String, String>,
}
