// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Read-only facts Google derives about the location — links out to Maps and
/// the public review form, and which surfaces apply (food menus).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct LocationMetadata {
  pub place_id: Option<String>,
  pub maps_uri: Option<String>,
  pub new_review_uri: Option<String>,
  pub can_have_food_menus: Option<bool>,
}
