// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Offer extras layered on an `OFFER` post's event window.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct LocalPostOffer {
  pub coupon_code: Option<String>,
  pub redeem_online_url: Option<String>,
  pub terms_conditions: Option<String>,
}
