// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::menu_item::MenuItem;
use crate::types::google::menu_label::MenuLabel;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct MenuSection {
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub labels: Vec<MenuLabel>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub items: Vec<MenuItem>,
}
