// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Localized display text used across menus, sections and items.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct MenuLabel {
  pub display_name: Option<String>,
  pub description: Option<String>,
  pub language_code: Option<String>,
}
