// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct PhoneNumbers {
  pub primary_phone: Option<String>,
  #[cfg_attr(feature = "tapir", tapir(optional))]
  pub additional_phones: Vec<String>,
}
