// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::question::Question;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct QuestionPage {
  pub questions: Vec<Question>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub total_size: Option<u32>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub next_page_token: Option<String>,
}
