// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::review::Review;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct ReviewPage {
  pub reviews: Vec<Review>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub average_rating: Option<f64>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub total_review_count: Option<u32>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub next_page_token: Option<String>,
}
