// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::google::search_keyword_count::SearchKeywordCount;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.google"))]
#[serde(rename_all = "camelCase")]
pub struct SearchKeywordPage {
  pub search_keywords_counts: Vec<SearchKeywordCount>,
  #[cfg_attr(feature = "tapir", tapir(optional = nullable))]
  pub next_page_token: Option<String>,
}
