// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::social_account::channel_rule::ChannelRule;

/// List every channel with the platform rules the hub enforces on it, so a
/// client offers only what a send will pass.
///
/// Any authenticated caller; no permission or scope applies.
pub async fn list(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<Vec<ChannelRule>> {
  let mut __path = String::from("/channel");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
