// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::message::webhook_verify_query::WebhookVerifyQuery;

/// Meta webhook receiver: verifies the payload signature, stores normalized
/// messages (deduplicating redeliveries), and enqueues CRM fan-out events.
///
/// Public — no authentication required; authorization comes from the `X-Hub-Signature-256` HMAC over the raw body.
pub async fn receive(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/webhook/meta");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Meta webhook verification handshake: echoes `hub.challenge` when
/// `hub.verify_token` matches the configured token.
///
/// Public — no authentication required; authorization comes from the configured webhook verify token.
pub async fn verify(__client: &crate::runtime::Client, __query: &WebhookVerifyQuery) -> crate::runtime::ApiResult<String> {
  let mut __path = String::from("/webhook/meta");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
