// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::user_mfa::user_mfa_admin_reset_response::UserMfaAdminResetResponse;

/// Remove all MFA factors for another user as an administrative recovery action.
///
/// Requires `ResetUserMfa`, which only platform staff hold; resetting your own factors is forbidden.
pub async fn reset(client: &Client, user_uid: &str) -> ApiResult<UserMfaAdminResetResponse> {
  let mut __path = String::from("/user/{user_uid}/mfa/reset");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
