// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;
use crate::types::types::user_mfa_kind::UserMfaKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user_mfa"))]
pub struct UserMfaFactorRow {
  pub kind: UserMfaKind,
  pub confirmed_at: Option<Timestamp>,
  pub last_used_at: Option<Timestamp>,
}
