// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user_mfa"))]
pub struct UserMfaEnrollTotpStartResponse {
  pub secret_base32: String,
  pub otpauth_uri: String,
  pub qr_svg: String,
}
