// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::audit_action::AuditAction;
use crate::types::database::audit_log_window::AuditLogWindow;
use crate::types::types::audit_resource::AuditResource;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.audit_log"))]
pub struct AuditLogQuery {
  #[serde(flatten)]
  pub window: AuditLogWindow,
  pub group_uid: Option<Uid>,
  pub user_uid: Option<Uid>,
  pub action: Option<AuditAction>,
  pub resource: Option<AuditResource>,
  pub resource_uid: Option<String>,
}
