// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]

/// Alternate-gateway webhook receiver for the alt channels: verifies the
/// payload signature and hands every message, receipt, reaction, edit,
/// revoke, comment, post outcome and account event to the feature that owns
/// it, which stores it (deduplicating redeliveries) and enqueues consumer fan-out
/// events.
///
/// Public — no authentication required; authorization comes from the gateway's signature header, an HMAC over the raw body.
pub async fn receive(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/webhook/gateway");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
