// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// A signed grant on the media URL: the hub mints one for a platform that has
/// to fetch a file it is about to deliver. Absent on an ordinary fetch.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.media"))]
pub struct MediaGrantQuery {
  pub exp: Option<i64>,
  pub sig: Option<String>,
}
