// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.media"))]
pub struct UploadMediaForm {
  /// Required for users and platform keys; group-bound keys imply their group.
  pub group_uid: Option<Uid>,
  #[cfg_attr(feature = "tapir", tapir(type = "File"))]
  pub file: Vec<u8>,
}
