// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

use crate::types::validate::{check, check_all, Constraint, Preprocess, ValidationSpec, Value, Violation};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.primitives"))]
#[serde(transparent)]
pub struct Email(String);

const SPEC: ValidationSpec = ValidationSpec { preprocess: Preprocess::TrimLowercase, constraints: &[Constraint::MinLen(5), Constraint::MaxLen(254), Constraint::Regex { source: "^[a-zA-Z0-9_%+-]+(\\.[a-zA-Z0-9_%+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*\\.[a-zA-Z]{2,}$", hint: None }] };

impl Email {
  /// The only producer: validates input, returns the value or the first violation.
  pub fn parse(value: impl Into<String>) -> Result<Self, Violation> {
    let value = value.into();
    match check(&SPEC, Value::Str(&value)) { Some(v) => Err(v), None => Ok(Self(value)) }
  }
  /// Every unmet rule, for a live checklist / strength meter.
  pub fn parse_all(value: &str) -> Vec<Violation> { check_all(&SPEC, Value::Str(value)) }
  pub fn value(&self) -> &str { &self.0 }
  pub fn spec() -> &'static ValidationSpec { &SPEC }
}

#[cfg(feature = "tapir")]
static TAPIR_REGEX_0: std::sync::LazyLock<tapir::regex::Regex> = std::sync::LazyLock::new(|| tapir::regex::Regex::new("^[a-zA-Z0-9_%+-]+(\\.[a-zA-Z0-9_%+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*\\.[a-zA-Z]{2,}$").unwrap());

#[cfg(feature = "tapir")]
static TAPIR_SPEC: tapir::validation::ValidationSpec = tapir::validation::ValidationSpec { preprocess: tapir::validation::Preprocess::TrimLowercase, constraints: &[tapir::validation::Constraint::MinLen(5), tapir::validation::Constraint::MaxLen(254), tapir::validation::Constraint::Regex { source: "^[a-zA-Z0-9_%+-]+(\\.[a-zA-Z0-9_%+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*\\.[a-zA-Z]{2,}$", compiled: || &TAPIR_REGEX_0, hint: None }] };

#[cfg(feature = "tapir")]
impl tapir::validation::Validated for Email {
  fn spec() -> &'static tapir::validation::ValidationSpec { &TAPIR_SPEC }
}

