// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// A bounded integer. `MIN`/`MAX` are inclusive `i64` bounds (width-agnostic, so
/// they flow to the frontend as one `number(min, max)` spec regardless of `B`);
/// `B` is the backing primitive the value is stored as and (de)serialized through
/// — pick it to match the DB column so the newtype is the type end-to-end.
use crate::types::validate::{check, check_all, Constraint, Preprocess, ValidationSpec, Value, Violation};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.primitives"))]
#[serde(transparent)]
pub struct Number1_200(i64);

const SPEC: ValidationSpec = ValidationSpec { preprocess: Preprocess::None, constraints: &[Constraint::Min(1), Constraint::Max(200)] };

impl Number1_200 {
  /// The only producer: validates input, returns the value or the first violation.
  pub fn parse(value: i64) -> Result<Self, Violation> {
    match check(&SPEC, Value::Int(value)) { Some(v) => Err(v), None => Ok(Self(value)) }
  }
  /// Every unmet rule, for a live checklist / strength meter.
  pub fn parse_all(value: i64) -> Vec<Violation> { check_all(&SPEC, Value::Int(value)) }
  pub fn value(&self) -> i64 { self.0 }
  pub fn spec() -> &'static ValidationSpec { &SPEC }
}

#[cfg(feature = "tapir")]
static TAPIR_SPEC: tapir::validation::ValidationSpec = tapir::validation::ValidationSpec { preprocess: tapir::validation::Preprocess::None, constraints: &[tapir::validation::Constraint::Min(1), tapir::validation::Constraint::Max(200)] };

#[cfg(feature = "tapir")]
impl tapir::validation::Validated for Number1_200 {
  fn spec() -> &'static tapir::validation::ValidationSpec { &TAPIR_SPEC }
}

