// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

use crate::types::validate::{check, check_all, Constraint, Preprocess, ValidationSpec, Value, Violation};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.primitives"))]
#[serde(transparent)]
pub struct Password8_128_F_F_T_F(String);

const SPEC: ValidationSpec = ValidationSpec { preprocess: Preprocess::None, constraints: &[Constraint::MinLen(8), Constraint::MaxLen(128), Constraint::RequireDigit] };

impl Password8_128_F_F_T_F {
  /// The only producer: validates input, returns the value or the first violation.
  pub fn parse(value: impl Into<String>) -> Result<Self, Violation> {
    let value = value.into();
    match check(&SPEC, Value::Str(&value)) { Some(v) => Err(v), None => Ok(Self(value)) }
  }
  /// Every unmet rule, for a live checklist / strength meter.
  pub fn parse_all(value: &str) -> Vec<Violation> { check_all(&SPEC, Value::Str(value)) }
  pub fn value(&self) -> &str { &self.0 }
  pub fn spec() -> &'static ValidationSpec { &SPEC }
}

#[cfg(feature = "tapir")]
static TAPIR_SPEC: tapir::validation::ValidationSpec = tapir::validation::ValidationSpec { preprocess: tapir::validation::Preprocess::None, constraints: &[tapir::validation::Constraint::MinLen(8), tapir::validation::Constraint::MaxLen(128), tapir::validation::Constraint::RequireDigit] };

#[cfg(feature = "tapir")]
impl tapir::validation::Validated for Password8_128_F_F_T_F {
  fn spec() -> &'static tapir::validation::ValidationSpec { &TAPIR_SPEC }
}

