// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

use crate::types::validate::{check, check_all, Constraint, Preprocess, ValidationSpec, Value, Violation};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.primitives"))]
#[serde(transparent)]
pub struct Phone(String);

static SPEC_REGEX_0: std::sync::LazyLock<regex::Regex> = std::sync::LazyLock::new(|| regex::Regex::new("^\\+[1-9]\\d{6,14}$").unwrap());

const SPEC: ValidationSpec = ValidationSpec { preprocess: Preprocess::Trim, constraints: &[Constraint::MinDigits(7), Constraint::MaxDigits(15), Constraint::Regex { source: "^\\+[1-9]\\d{6,14}$", compiled: || &SPEC_REGEX_0, hint: Some("esperado E.164: +<código do país><número>") }] };

impl Phone {
  /// The only producer: validates input, returns the value or the first violation.
  pub fn parse(value: impl Into<String>) -> Result<Self, Violation> {
    let value = value.into();
    match check(&SPEC, Value::Str(&value)) { Some(v) => Err(v), None => Ok(Self(value)) }
  }
  /// Every unmet rule, for a live checklist / strength meter.
  pub fn parse_all(value: &str) -> Vec<Violation> { check_all(&SPEC, Value::Str(value)) }
  pub fn value(&self) -> &str { &self.0 }
  pub fn spec() -> &'static ValidationSpec { &SPEC }
}

#[cfg(feature = "tapir")]
static TAPIR_REGEX_0: std::sync::LazyLock<tapir::regex::Regex> = std::sync::LazyLock::new(|| tapir::regex::Regex::new("^\\+[1-9]\\d{6,14}$").unwrap());

#[cfg(feature = "tapir")]
static TAPIR_SPEC: tapir::validation::ValidationSpec = tapir::validation::ValidationSpec { preprocess: tapir::validation::Preprocess::Trim, constraints: &[tapir::validation::Constraint::MinDigits(7), tapir::validation::Constraint::MaxDigits(15), tapir::validation::Constraint::Regex { source: "^\\+[1-9]\\d{6,14}$", compiled: || &TAPIR_REGEX_0, hint: Some("esperado E.164: +<código do país><número>") }] };

#[cfg(feature = "tapir")]
impl tapir::validation::Validated for Phone {
  fn spec() -> &'static tapir::validation::ValidationSpec { &TAPIR_SPEC }
}

