// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

use crate::types::validate::{check, check_all, Constraint, Preprocess, ValidationSpec, Value, Violation};

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.primitives"))]
#[serde(transparent)]
pub struct Pin6(String);

const SPEC: ValidationSpec = ValidationSpec { preprocess: Preprocess::Trim, constraints: &[Constraint::ExactLen(6), Constraint::AsciiDigitsOnly] };

impl Pin6 {
  /// The only producer: validates input, returns the value or the first violation.
  pub fn parse(value: impl Into<String>) -> Result<Self, Violation> {
    let value = value.into();
    match check(&SPEC, Value::Str(&value)) { Some(v) => Err(v), None => Ok(Self(value)) }
  }
  /// Every unmet rule, for a live checklist / strength meter.
  pub fn parse_all(value: &str) -> Vec<Violation> { check_all(&SPEC, Value::Str(value)) }
  pub fn value(&self) -> &str { &self.0 }
  pub fn spec() -> &'static ValidationSpec { &SPEC }
}

impl TryFrom<String> for Pin6 {
  type Error = Violation;
  fn try_from(value: String) -> Result<Self, Violation> { Self::parse(value) }
}

impl std::str::FromStr for Pin6 {
  type Err = Violation;
  fn from_str(value: &str) -> Result<Self, Violation> { Self::parse(value) }
}

impl AsRef<str> for Pin6 {
  fn as_ref(&self) -> &str { &self.0 }
}

impl std::fmt::Display for Pin6 {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(&self.0) }
}

#[cfg(feature = "tapir")]
static TAPIR_SPEC: tapir::validation::ValidationSpec = tapir::validation::ValidationSpec { preprocess: tapir::validation::Preprocess::Trim, constraints: &[tapir::validation::Constraint::ExactLen(6), tapir::validation::Constraint::AsciiDigitsOnly] };

#[cfg(feature = "tapir")]
impl tapir::validation::Validated for Pin6 {
  fn spec() -> &'static tapir::validation::ValidationSpec { &TAPIR_SPEC }
}

