// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Free text with its length bounds in the type, read as a range: `Text<2, 8000>`
/// is "2..=8000", matching [`crate::Number`]'s parameter order. Neither bound
/// defaults — an unbounded-below field spells its `0` — so a length is never
/// silently the wrong end of the range. Both reach the emitted TypeScript
/// through [`Validated`], so a consumer sees the same rule the server enforces.
use crate::types::validate::{check, check_all, Constraint, Preprocess, ValidationSpec, Value, Violation};

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.primitives"))]
#[serde(transparent)]
pub struct Text0_8000(String);

const SPEC: ValidationSpec = ValidationSpec { preprocess: Preprocess::Trim, constraints: &[Constraint::MinLen(0), Constraint::MaxLen(8000)] };

impl Text0_8000 {
  /// The only producer: validates input, returns the value or the first violation.
  pub fn parse(value: impl Into<String>) -> Result<Self, Violation> {
    let value = value.into();
    match check(&SPEC, Value::Str(&value)) { Some(v) => Err(v), None => Ok(Self(value)) }
  }
  /// Every unmet rule, for a live checklist / strength meter.
  pub fn parse_all(value: &str) -> Vec<Violation> { check_all(&SPEC, Value::Str(value)) }
  pub fn value(&self) -> &str { &self.0 }
  pub fn spec() -> &'static ValidationSpec { &SPEC }
}

impl TryFrom<String> for Text0_8000 {
  type Error = Violation;
  fn try_from(value: String) -> Result<Self, Violation> { Self::parse(value) }
}

impl std::str::FromStr for Text0_8000 {
  type Err = Violation;
  fn from_str(value: &str) -> Result<Self, Violation> { Self::parse(value) }
}

impl AsRef<str> for Text0_8000 {
  fn as_ref(&self) -> &str { &self.0 }
}

impl std::fmt::Display for Text0_8000 {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(&self.0) }
}

#[cfg(feature = "tapir")]
static TAPIR_SPEC: tapir::validation::ValidationSpec = tapir::validation::ValidationSpec { preprocess: tapir::validation::Preprocess::Trim, constraints: &[tapir::validation::Constraint::MinLen(0), tapir::validation::Constraint::MaxLen(8000)] };

#[cfg(feature = "tapir")]
impl tapir::validation::Validated for Text0_8000 {
  fn spec() -> &'static tapir::validation::ValidationSpec { &TAPIR_SPEC }
}

