// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::rate_limit::create_rate_limit_rule_request::CreateRateLimitRuleRequest;
use crate::types::rate_limit::create_rate_limit_rule_response::CreateRateLimitRuleResponse;
use crate::types::database::rate_limit_rule::RateLimitRule;
use crate::types::rate_limit::update_rate_limit_rule_request::UpdateRateLimitRuleRequest;

/// Create a rate-limit rule for any target kind (HTTP scope, action, email dispatch, or channel pacing).
///
/// Requires `CreateRateLimits`, which only platform staff hold.
pub async fn create(__client: &crate::runtime::Client, __body: &CreateRateLimitRuleRequest) -> crate::runtime::ApiResult<CreateRateLimitRuleResponse> {
  let mut __path = String::from("/rate-limit");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Delete a rate-limit rule by uid.
///
/// Requires `DeleteRateLimits`, which only platform staff hold.
pub async fn delete(__client: &crate::runtime::Client, rule_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/rate-limit/{rule_uid}");
  __path = __path.replace("{rule_uid}", &crate::runtime::encode_path(rule_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Fetch a single rate-limit rule by uid.
///
/// Requires `ViewRateLimits`, which only platform staff hold.
pub async fn get(__client: &crate::runtime::Client, rule_uid: &str) -> crate::runtime::ApiResult<RateLimitRule> {
  let mut __path = String::from("/rate-limit/{rule_uid}");
  __path = __path.replace("{rule_uid}", &crate::runtime::encode_path(rule_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List every rate-limit rule.
///
/// Requires `ViewRateLimits`, which only platform staff hold.
pub async fn list(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<Vec<RateLimitRule>> {
  let mut __path = String::from("/rate-limit");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Update an existing rate-limit rule's budget; the rule's target is immutable.
///
/// Requires `UpdateRateLimits`, which only platform staff hold.
pub async fn update(__client: &crate::runtime::Client, rule_uid: &str, __body: &UpdateRateLimitRuleRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/rate-limit/{rule_uid}");
  __path = __path.replace("{rule_uid}", &crate::runtime::encode_path(rule_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
