// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::message_content_kind::MessageContentKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct ConversationMessageCountQuery {
  /// Only messages of these content kinds — the same narrowing as the list.
  pub kinds: Option<Vec<MessageContentKind>>,
}
