// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::message::presence_signal::PresenceSignal;
use crate::types::message::whatsapp_presence_signal::WhatsappPresenceSignal;

/// A presence signal, tagged by channel so a signal the channel has no call
/// for does not deserialize. The `channel` must match the conversation's
/// account.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum ConversationActionRequest {
  Facebook(PresenceSignal),
  Instagram(PresenceSignal),
  Whatsapp(WhatsappPresenceSignal),
  WhatsappStevo(PresenceSignal),
  WhatsappNative(PresenceSignal),
}
