// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// The largest picture the channel offers for the conversation's participant,
/// hosted by the hub. `None` when the participant has none, hides it, or the
/// platform could not be asked.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct ConversationAvatar {
  pub url: Option<String>,
}
