// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::phone::Phone;
use crate::types::primitives::uid::Uid;

/// Channel-tagged conversation creation — only the channels that can verify
/// a number on the platform can initiate, so no other channel's shape
/// deserializes.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum CreateConversationRequest {
  WhatsappStevo {
    /// A whatsapp_stevo social account.
    social_account_uid: Uid,
    /// The recipient's phone in E.164 (`+<country code><number>`).
    phone: Phone,
  },
  WhatsappNative {
    /// A whatsapp_native social account.
    social_account_uid: Uid,
    /// The recipient's phone in E.164 (`+<country code><number>`).
    phone: Phone,
  },
}
