// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;
use crate::types::meta::whatsapp_template_category::WhatsappTemplateCategory;
use crate::types::meta::whatsapp_template_component::WhatsappTemplateComponent;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct CreateTemplateRequest {
  /// Any whatsapp account of the WABA whose templates are managed.
  pub social_account_uid: Uid,
  /// Lowercase letters, digits and underscores (Meta's rule), e.g.
  /// `order_update`.
  pub name: String,
  /// Locale code, e.g. `pt_BR`.
  pub language: String,
  pub category: WhatsappTemplateCategory,
  /// The template's blocks. Meta validates the assembled definition and owns
  /// the verdict — a rejection comes back as its own message.
  pub components: Vec<WhatsappTemplateComponent>,
}
