// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Why one target was refused. A closed set the caller renders — per-target
/// prose never rides a success body.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(rename_all = "snake_case")]
pub enum ForwardRejection {
  /// No such conversation, or the caller cannot send in its group. The two are
  /// one answer on purpose: which it was would report whether a conversation
  /// the caller cannot reach exists.
  Unreachable,
  /// The account behind the target conversation is disabled.
  AccountDisabled,
  /// The target's channel cannot express this content (a place on instagram, a
  /// carousel on whatsapp, a multi-card contact on a one-vcard gateway).
  UnsupportedContent,
  /// Outside the channel's response window (`GET /channel`): free-form
  /// content needs an inbound message within the window's hours, and past
  /// that only what the window lifts by passes — a template on official and
  /// alt whatsapp. The native flavor has no window.
  WindowExpired,
  /// The send could not be queued.
  Failed,
}
