// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::message::forward_rejection::ForwardRejection;
use crate::types::message::message_with_context::MessageWithContext;
use crate::types::primitives::uid::Uid;

/// What forwarding did for one target. Tagged rather than a nullable pair: a
/// queued forward carries its message and a refused one carries why, and
/// neither shape can express the other.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "outcome")]
#[serde(rename_all = "snake_case")]
pub enum ForwardOutcome {
  Queued {
    conversation_uid: Uid,
    message: MessageWithContext,
  },
  Rejected {
    conversation_uid: Uid,
    reason: ForwardRejection,
  },
}
