// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_200::Number1_200;
use crate::types::primitives::text0_8000::Text0_8000;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct ListConversationsQuery {
  /// Narrow to these groups, each one the caller may see; omit for everything the caller may see.
  pub group_uids: Option<Vec<Uid>>,
  /// Narrow to these accounts, each one in scope; naming any account overrides the groups.
  pub social_account_uids: Option<Vec<Uid>>,
  /// Narrow to conversations whose participant matches — alias, platform
  /// name, username or phone, as a substring. A term under 2 characters
  /// answers with no rows. Composes with the cursor; not with `uids`.
  pub q: Option<Text0_8000>,
  /// Exact conversations to return (≤200), for decorating rows a consumer already
  /// holds by uid. Mutually exclusive with the keyset cursor; ordering follows
  /// activity like the plain list.
  pub uids: Option<Vec<Uid>>,
  /// Keyset cursor: the previous page's last `(last_message_at, uid)` pair.
  /// Both halves together or neither — the list reorders under live traffic,
  /// so offsets would skip rows.
  pub before_activity_at: Option<i64>,
  pub before_uid: Option<Uid>,
  pub limit: Option<Number1_200>,
}
