// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::message_tag::MessageTag;
use crate::types::message::messenger_content::MessengerContent;
use crate::types::types::quick_reply::QuickReply;

/// Messenger/Instagram DM payload (Send API). Attachments carry no captions;
/// quick replies may attach to any content.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct MessengerSend {
  pub content: MessengerContent,
  /// Lifts the standard 24h response window (`human_agent` = 7 days; the
  /// Meta app must hold the `human_agent` permission).
  pub tag: Option<MessageTag>,
  /// Up to 13 quick-reply chips.
  pub quick_replies: Option<Vec<QuickReply>>,
}
