// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// The replacement text, shared by both editing flavors.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct MessageEdit {
  /// The new text: replaces the body of text messages, the caption of media
  /// messages.
  pub text: String,
}
