// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::contact_card::ContactCard;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum NativeContent {
  Text {
    text: String,
  },
  Image {
    url: String,
    caption: Option<String>,
  },
  /// `voice` sends it as a voice note (push-to-talk) rather than an audio
  /// file. Only the sender knows which it meant, so it is stated rather than
  /// guessed from the codec; WhatsApp draws nothing at all for a mismatch.
  Audio {
    url: String,
    voice: bool,
  },
  Video {
    url: String,
    caption: Option<String>,
  },
  File {
    url: String,
    caption: Option<String>,
    filename: Option<String>,
  },
  Location {
    latitude: f64,
    longitude: f64,
    name: Option<String>,
    address: Option<String>,
  },
  Contact {
    contact: ContactCard,
  },
}
