// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::message::native_content::NativeContent;
use crate::types::primitives::uid::Uid;

/// Native (whatsmeow) payload: text, media, locations and one contact card —
/// the bridge sends no interactive shapes.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct NativeSend {
  pub content: NativeContent,
  /// Send as a reply to this message (must belong to the same conversation).
  pub reply_to_uid: Option<Uid>,
}
