// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::sender_action::SenderAction;

/// Presence on a channel with a real typing state: `typing_off` is a signal
/// of its own.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct PresenceSignal {
  pub action: SenderAction,
}
