// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Channel-tagged reaction payload — the Messenger Send API has no reaction
/// support, so no facebook variant exists. Must match the message's channel.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum ReactToMessageRequest {
  Instagram {
    /// Meta reaction name; omitted or empty selects `love`.
    reaction: Option<String>,
  },
  Whatsapp {
    /// The emoji itself; omitted or empty selects ❤️.
    emoji: Option<String>,
  },
  WhatsappStevo {
    /// The emoji itself; omitted or empty selects ❤️.
    emoji: Option<String>,
  },
  WhatsappNative {
    /// The emoji itself; omitted or empty selects ❤️.
    emoji: Option<String>,
  },
}
