// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::message::self_clearing_sender_action::SelfClearingSenderAction;

/// Official whatsapp and the gateway channels have no `typing_off` call —
/// their indicator clears on its own — so the shape cannot express one.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct SelfClearingPresenceSignal {
  pub action: SelfClearingSenderAction,
}
