// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::message::messenger_send::MessengerSend;
use crate::types::message::native_send::NativeSend;
use crate::types::message::stevo_send::StevoSend;
use crate::types::message::whatsapp_send::WhatsappSend;

/// Channel-tagged send payload: each variant carries exactly the fields and
/// content kinds its channel can deliver, so a send the channel cannot
/// express does not even deserialize. The `channel` must match the
/// conversation's account.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum SendContent {
  Facebook(MessengerSend),
  Instagram(MessengerSend),
  Whatsapp(WhatsappSend),
  WhatsappStevo(StevoSend),
  WhatsappNative(NativeSend),
}
