// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::contact_card::ContactCard;
use crate::types::types::quick_reply::QuickReply;
use crate::types::types::template_button::TemplateButton;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
pub enum StevoContent {
  Text {
    text: String,
  },
  /// Text with quick-reply chips riding an interactive message: 1–3 chips
  /// become reply buttons, 4–10 a list.
  QuickReplies {
    text: String,
    quick_replies: Vec<QuickReply>,
  },
  Image {
    url: String,
    caption: Option<String>,
  },
  Audio {
    url: String,
  },
  Video {
    url: String,
    caption: Option<String>,
  },
  File {
    url: String,
    caption: Option<String>,
    filename: Option<String>,
  },
  Location {
    latitude: f64,
    longitude: f64,
    name: Option<String>,
    address: Option<String>,
  },
  Contact {
    contact: ContactCard,
  },
  /// Text with up to three buttons (mixed URL/postback sets allowed).
  Buttons {
    text: String,
    buttons: Vec<TemplateButton>,
  },
}
