// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::whatsapp_template_send_component::WhatsappTemplateSendComponent;

/// An approved template reference, the same shape the `template` send
/// content takes: `components` fills the approved definition's placeholders.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct TemplateOpener {
  pub name: String,
  pub language: String,
  pub components: Option<Vec<WhatsappTemplateSendComponent>>,
}
