// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::meta::whatsapp_template_category::WhatsappTemplateCategory;
use crate::types::meta::whatsapp_template_component::WhatsappTemplateComponent;
use crate::types::meta::whatsapp_template_status::WhatsappTemplateStatus;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.message"))]
pub struct TemplateResponse {
  pub id: String,
  pub name: String,
  pub language: String,
  pub category: WhatsappTemplateCategory,
  /// Only `approved` templates are sendable.
  pub status: WhatsappTemplateStatus,
  pub components: Vec<WhatsappTemplateComponent>,
}
