// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::database::user_invite::UserInvite;
use crate::types::user_invite::user_invite_accept_request::UserInviteAcceptRequest;
use crate::types::user_invite::user_invite_accept_response::UserInviteAcceptResponse;
use crate::types::user_invite::user_invite_send_request::UserInviteSendRequest;
use crate::types::user_invite::user_invite_send_response::UserInviteSendResponse;

/// Accept an invitation by its token, creating the user account with the chosen
/// password and, in the same transaction, the membership the invitation carries.
///
/// Public — no authentication required; authorization comes from the invitation token in the request body.
pub async fn accept(__client: &crate::runtime::Client, __body: &UserInviteAcceptRequest) -> crate::runtime::ApiResult<UserInviteAcceptResponse> {
  let mut __path = String::from("/user-invite/accept");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Count pending (unaccepted) user invitations.
///
/// Requires `ViewInvites`; the count covers only invites into groups where the caller holds it, and platform invites only for platform staff.
pub async fn count(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<u64> {
  let mut __path = String::from("/user-invite/count");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List pending (unaccepted) user invitations.
///
/// Requires `ViewInvites`; the list covers only invites into groups where the caller holds it, and platform invites only for platform staff.
pub async fn list(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<Vec<UserInvite>> {
  let mut __path = String::from("/user-invite");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Refresh a pending user invitation's expiry and re-send its email.
///
/// Requires `InviteUsers` in the invitation's group plus a role there that may hand out the invited one, or `OperatePlatformScope` for an invitation naming no group.
pub async fn resend(__client: &crate::runtime::Client, invite_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/user-invite/{invite_uid}/resend");
  __path = __path.replace("{invite_uid}", &crate::runtime::encode_path(invite_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Revoke a pending user invitation so its registration link can no longer be used.
///
/// Requires `InviteUsers` in the invitation's group plus a role there that may hand out the invited one, or `OperatePlatformScope` for an invitation naming no group.
pub async fn revoke(__client: &crate::runtime::Client, invite_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/user-invite/{invite_uid}");
  __path = __path.replace("{invite_uid}", &crate::runtime::encode_path(invite_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Send an invitation that lets the recipient register a user account, joining
/// the named group with the named role once accepted. Naming neither invites to
/// the platform alone; naming only one of the two is refused.
///
/// Requires `InviteUsers` in the named group plus a role there that may hand out the named one, or `OperatePlatformScope` when no group is named.
pub async fn send(__client: &crate::runtime::Client, __body: &UserInviteSendRequest) -> crate::runtime::ApiResult<UserInviteSendResponse> {
  let mut __path = String::from("/user-invite");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
