// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::campaign::campaign_template_response::CampaignTemplateResponse;
use crate::types::campaign::template_request::TemplateRequest;

/// Append a template to the wheel. Draft, paused and done only.
///
/// Requires `ManageCampaigns` in the campaign's group.
pub async fn add(__client: &crate::runtime::Client, campaign_uid: &str, __body: &TemplateRequest) -> crate::runtime::ApiResult<CampaignTemplateResponse> {
  let mut __path = String::from("/campaign/{campaign_uid}/template");
  __path = __path.replace("{campaign_uid}", &crate::runtime::encode_path(campaign_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Remove a template from the wheel. Draft, paused and done only.
///
/// Requires `ManageCampaigns` in the campaign's group.
pub async fn delete(__client: &crate::runtime::Client, campaign_uid: &str, template_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/campaign/{campaign_uid}/template/{template_uid}");
  __path = __path.replace("{campaign_uid}", &crate::runtime::encode_path(campaign_uid));
  __path = __path.replace("{template_uid}", &crate::runtime::encode_path(template_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// The template wheel, in rotation order.
///
/// Requires `ViewCampaigns` in the campaign's group.
pub async fn list(__client: &crate::runtime::Client, campaign_uid: &str) -> crate::runtime::ApiResult<Vec<CampaignTemplateResponse>> {
  let mut __path = String::from("/campaign/{campaign_uid}/template");
  __path = __path.replace("{campaign_uid}", &crate::runtime::encode_path(campaign_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Rewrite a template in place, keeping its position in the wheel. Draft,
/// paused and done only; the same checks as adding one.
///
/// Requires `ManageCampaigns` in the campaign's group.
pub async fn update(__client: &crate::runtime::Client, campaign_uid: &str, template_uid: &str, __body: &TemplateRequest) -> crate::runtime::ApiResult<CampaignTemplateResponse> {
  let mut __path = String::from("/campaign/{campaign_uid}/template/{template_uid}");
  __path = __path.replace("{campaign_uid}", &crate::runtime::encode_path(campaign_uid));
  __path = __path.replace("{template_uid}", &crate::runtime::encode_path(template_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
