// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// One catalog entry, in the renditions the composer needs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.gif"))]
pub struct Gif {
  pub id: String,
  pub title: String,
  /// The picker tile: an animated webp, or a gif when Giphy has no webp.
  pub preview_url: String,
  pub preview_width: u32,
  pub preview_height: u32,
  /// The clip the bubble plays — sent as `gif` natively and as a plain video
  /// on the channels without a gif shape.
  pub mp4_url: String,
  /// The .gif itself, for the channels that animate an image attachment.
  pub gif_url: String,
}
