// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::gif::gif::Gif;
use crate::types::primitives::number0_4999::Number0_4999;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.gif"))]
pub struct GifSearchResponse {
  pub items: Vec<Gif>,
  /// The `offset` of the page after this one; absent on the last page.
  pub next_offset: Option<Number0_4999>,
}
