// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::rate_limit_rule_kind::RateLimitRuleKind;
use crate::types::domain::rate_limit_scope::RateLimitScope;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.rate_limit"))]
pub struct CreateRateLimitRuleRequest {
  /// The tier the rule sits in. `shared`, `global` and `override` need
  /// platform standing; `own` needs `CreateRateLimits` in that group, and the
  /// rule must stay within the ceiling that applies to the group (its
  /// override, else the global default).
  pub scope: RateLimitScope,
  /// Target and budget. Only targets whose caller belongs to a group accept a
  /// group tier; only request budgets (not pacing) accept `shared`, and email
  /// dispatch accepts nothing else.
  pub rule: RateLimitRuleKind,
}
