// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.rate_limit"))]
pub struct ListRateLimitRulesQuery {
  /// Narrow to the rules that reach these groups, each one the caller may see:
  /// the shared buckets, the global defaults and those groups' override and
  /// own tiers. Without it, platform staff get every rule and everyone else the
  /// rules reaching the groups where they may view limits.
  pub group_uids: Option<Vec<Uid>>,
}
