// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number0_3600000::Number0_3600000;
use crate::types::primitives::number0_600000::Number0_600000;
use crate::types::primitives::number1_100000::Number1_100000;
use crate::types::axumy::optional_update::OptionalUpdate;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.rate_limit"))]
pub struct UpdateChannelPacingRequest {
  pub min_delay_ms: OptionalUpdate<Number0_600000>,
  pub max_delay_ms: OptionalUpdate<Number0_600000>,
  pub batch_size: OptionalUpdate<Option<Number1_100000>>,
  pub batch_pause_ms: OptionalUpdate<Number0_3600000>,
}
