// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::rate_limit_rule_kind::RateLimitRuleKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.rate_limit"))]
pub struct UpdateRateLimitRuleRequest {
  /// Replacement rule payload — target *and* budget, so it is sent whole
  /// rather than as a field mask. Must keep the same target (`kind` plus its
  /// identity fields); only the budget may change.
  pub rule: RateLimitRuleKind,
}
