// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::database::pulse_disk_inventory_row::PulseDiskInventoryRow;
use crate::types::database::pulse_gpu_inventory_row::PulseGpuInventoryRow;
use crate::types::database::pulse_network_inventory_row::PulseNetworkInventoryRow;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.pulse"))]
pub struct PulseInventoryResponse {
  pub disks: Vec<PulseDiskInventoryRow>,
  pub networks: Vec<PulseNetworkInventoryRow>,
  pub gpus: Vec<PulseGpuInventoryRow>,
}
