// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::database::api_key::ApiKey;
use crate::types::api_key::create_api_key_request::CreateApiKeyRequest;
use crate::types::api_key::create_api_key_response::CreateApiKeyResponse;
use crate::types::api_key::list_api_keys_query::ListApiKeysQuery;
use crate::types::api_key::rotate_api_key_response::RotateApiKeyResponse;
use crate::types::api_key::update_api_key_permissions_request::UpdateApiKeyPermissionsRequest;
use crate::types::api_key::update_api_key_request::UpdateApiKeyRequest;

/// Count API keys, optionally filtered by group.
///
/// Requires `ViewApiKeys`; the count covers only keys of groups where the caller holds it, and platform keys only for platform staff.
pub async fn count(__client: &crate::runtime::Client, __query: &ListApiKeysQuery) -> crate::runtime::ApiResult<u64> {
  let mut __path = String::from("/api-key/count");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Create an API key bound to a group or to the platform. A platform key (no
/// group) automatically carries `operate_platform_scope`; a group-bound key may
/// never carry it. Every granted permission must be one the caller itself holds
/// in the key's scope, and must bring along whatever that permission requires.
///
/// Requires `CreateApiKeys` and `GrantApiKeyPermissions` in the named group, or `OperatePlatformScope` plus both when no group is named.
pub async fn create(__client: &crate::runtime::Client, __body: &CreateApiKeyRequest) -> crate::runtime::ApiResult<CreateApiKeyResponse> {
  let mut __path = String::from("/api-key");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Fetch a single API key by uid.
///
/// Requires `ViewApiKeys` in the key's group, or `OperatePlatformScope` plus `ViewApiKeys` for a platform key.
pub async fn get(__client: &crate::runtime::Client, api_key_uid: &str) -> crate::runtime::ApiResult<ApiKey> {
  let mut __path = String::from("/api-key/{api_key_uid}");
  __path = __path.replace("{api_key_uid}", &crate::runtime::encode_path(api_key_uid));
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List API keys, optionally filtered by group.
///
/// Requires `ViewApiKeys`; the list covers only keys of groups where the caller holds it, and platform keys only for platform staff.
pub async fn list(__client: &crate::runtime::Client, __query: &ListApiKeysQuery) -> crate::runtime::ApiResult<Vec<ApiKey>> {
  let mut __path = String::from("/api-key");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Revoke an API key, permanently disabling it.
///
/// Requires `RevokeApiKeys` in the key's group, or `OperatePlatformScope` plus `RevokeApiKeys` for a platform key.
pub async fn revoke(__client: &crate::runtime::Client, api_key_uid: &str) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/api-key/{api_key_uid}/revoke");
  __path = __path.replace("{api_key_uid}", &crate::runtime::encode_path(api_key_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Rotate an API key's secret, returning the new key.
///
/// Requires `RotateApiKeys` in the key's group, or `OperatePlatformScope` plus `RotateApiKeys` for a platform key.
pub async fn rotate(__client: &crate::runtime::Client, api_key_uid: &str) -> crate::runtime::ApiResult<RotateApiKeyResponse> {
  let mut __path = String::from("/api-key/{api_key_uid}/rotate");
  __path = __path.replace("{api_key_uid}", &crate::runtime::encode_path(api_key_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Update an API key's name or enabled flag.
///
/// Requires `UpdateApiKeys` in the key's group, or `OperatePlatformScope` plus `UpdateApiKeys` for a platform key.
pub async fn update(__client: &crate::runtime::Client, api_key_uid: &str, __body: &UpdateApiKeyRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/api-key/{api_key_uid}");
  __path = __path.replace("{api_key_uid}", &crate::runtime::encode_path(api_key_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Replace the granted permission set of an API key. `operate_platform_scope`
/// stays bound to the key's group binding and cannot be granted to a group key;
/// every other granted permission must be one the caller itself holds in the
/// key's scope, and must bring along whatever that permission requires.
///
/// Requires `GrantApiKeyPermissions` in the key's group, or `OperatePlatformScope` plus `GrantApiKeyPermissions` for a platform key.
pub async fn update_permissions(__client: &crate::runtime::Client, api_key_uid: &str, __body: &UpdateApiKeyPermissionsRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/api-key/{api_key_uid}/permission");
  __path = __path.replace("{api_key_uid}", &crate::runtime::encode_path(api_key_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
