// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::database::api_key::ApiKey;
use crate::types::api_key::create_api_key_request::CreateApiKeyRequest;
use crate::types::api_key::create_api_key_response::CreateApiKeyResponse;
use crate::types::api_key::list_api_keys_query::ListApiKeysQuery;
use crate::types::api_key::rotate_api_key_response::RotateApiKeyResponse;
use crate::types::api_key::update_api_key_permissions_request::UpdateApiKeyPermissionsRequest;
use crate::types::api_key::update_api_key_request::UpdateApiKeyRequest;

/// Count API keys, optionally filtered by group.
///
/// Requires `ViewApiKeys`; the count covers only keys of groups where the caller holds it, and platform keys only for platform staff.
pub async fn count(client: &Client, query: &ListApiKeysQuery) -> ApiResult<u64> {
  let mut __path = String::from("/api-key/count");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Create an API key bound to a group or to the platform. A platform key (no
/// group) automatically carries `operate_platform_scope`; a group-bound key may
/// never carry it. Every granted permission must be one the caller itself holds
/// in the key's scope, and must bring along whatever that permission requires.
///
/// Requires `CreateApiKeys` and `GrantApiKeyPermissions` in the named group, or `OperatePlatformScope` plus both when no group is named.
pub async fn create(client: &Client, body: &CreateApiKeyRequest) -> ApiResult<CreateApiKeyResponse> {
  let mut __path = String::from("/api-key");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Fetch a single API key by uid.
///
/// Requires `ViewApiKeys` in the key's group, or `OperatePlatformScope` plus `ViewApiKeys` for a platform key.
pub async fn get(client: &Client, api_key_uid: &str) -> ApiResult<ApiKey> {
  let mut __path = String::from("/api-key/{api_key_uid}");
  __path = __path.replace("{api_key_uid}", &encode_path(api_key_uid));
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List API keys, optionally filtered by group.
///
/// Requires `ViewApiKeys`; the list covers only keys of groups where the caller holds it, and platform keys only for platform staff.
pub async fn list(client: &Client, query: &ListApiKeysQuery) -> ApiResult<Vec<ApiKey>> {
  let mut __path = String::from("/api-key");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// Revoke an API key, permanently disabling it.
///
/// Requires `RevokeApiKeys` in the key's group, or `OperatePlatformScope` plus `RevokeApiKeys` for a platform key.
pub async fn revoke(client: &Client, api_key_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/api-key/{api_key_uid}/revoke");
  __path = __path.replace("{api_key_uid}", &encode_path(api_key_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Rotate an API key's secret, returning the new key.
///
/// Requires `RotateApiKeys` in the key's group, or `OperatePlatformScope` plus `RotateApiKeys` for a platform key.
pub async fn rotate(client: &Client, api_key_uid: &str) -> ApiResult<RotateApiKeyResponse> {
  let mut __path = String::from("/api-key/{api_key_uid}/rotate");
  __path = __path.replace("{api_key_uid}", &encode_path(api_key_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Update an API key's name or enabled flag.
///
/// Requires `UpdateApiKeys` in the key's group, or `OperatePlatformScope` plus `UpdateApiKeys` for a platform key.
pub async fn update(client: &Client, api_key_uid: &str, body: &UpdateApiKeyRequest) -> ApiResult<()> {
  let mut __path = String::from("/api-key/{api_key_uid}");
  __path = __path.replace("{api_key_uid}", &encode_path(api_key_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Replace the granted permission set of an API key. `operate_platform_scope`
/// stays bound to the key's group binding and cannot be granted to a group key;
/// every other granted permission must be one the caller itself holds in the
/// key's scope, and must bring along whatever that permission requires.
///
/// Requires `GrantApiKeyPermissions` in the key's group, or `OperatePlatformScope` plus `GrantApiKeyPermissions` for a platform key.
pub async fn update_permissions(client: &Client, api_key_uid: &str, body: &UpdateApiKeyPermissionsRequest) -> ApiResult<()> {
  let mut __path = String::from("/api-key/{api_key_uid}/permission");
  __path = __path.replace("{api_key_uid}", &encode_path(api_key_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
