// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};

/// Return a 400 — probe for the client's bad-request handling.
///
/// Public — no authentication required.
pub async fn bad_request(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/bad-request");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a 409 — probe for the client's conflict handling.
///
/// Public — no authentication required.
pub async fn conflict(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/conflict");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a 403 — probe for the client's permission-denied handling.
///
/// Public — no authentication required.
pub async fn forbidden(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/forbidden");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a 500 — probe for the client's server-error handling.
///
/// Public — no authentication required.
pub async fn internal(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/internal");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a 404 — probe for the client's missing-resource handling.
///
/// Public — no authentication required.
pub async fn not_found(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/not-found");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a success envelope — the happy-path probe for client error handling.
///
/// Public — no authentication required.
pub async fn ok(client: &Client) -> ApiResult<String> {
  let mut __path = String::from("/test/ok");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Panic — probe that the panic layer answers 500 instead of dropping the connection.
///
/// Public — no authentication required.
pub async fn panic(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/panic");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a 401 — probe for the client's session-expiry handling.
///
/// Public — no authentication required.
pub async fn unauthorized(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/unauthorized");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Return a 503 — probe for the client's outage handling.
///
/// Public — no authentication required.
pub async fn unavailable(client: &Client) -> ApiResult<()> {
  let mut __path = String::from("/test/unavailable");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
