// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::call_phase::CallPhase;

/// Server → client control frames.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.call"))]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum CallServerMsg {
  /// Where the call is. Sent once when the socket opens, then on every change;
  /// `ended` is always the last frame.
  State {
    phase: CallPhase,
    reason: Option<String>,
  },
  /// The peer's video state changed. `upgrade` means they are *asking* for
  /// video and are waiting on a `video` / `accept`.
  VideoState {
    active: bool,
    upgrade: bool,
    orientation: i32,
  },
  /// The peer's true camera rotation, in clockwise quarter turns, discovered
  /// per-frame. Phones signal rotation instead of rotating pixels, so a
  /// renderer that ignores this shows the caller sideways.
  Orientation {
    orientation: i32,
  },
  /// The peer lost video and needs a keyframe. An encoder that ignores this
  /// keeps sending frames the peer will never decode.
  KeyframeRequest,
  /// An in-call reaction from the peer.
  Reaction {
    sender: String,
    emoji: String,
    removed: bool,
  },
  /// Media discarded because one side could not keep up, counted since the
  /// call began. A rising count is the only symptom a slow link produces.
  Stats {
    audio_dropped: u64,
    video_dropped: u64,
  },
  /// A frame was rejected. The call and the socket are unchanged.
  Error {
    message: String,
  },
}
