// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::call_video_action::CallVideoAction;

/// Client → server control frames. Everything that decides *whether* a call
/// exists — placing, answering, refusing, ending — stays on REST, where it is
/// audited and permission-checked; this socket only carries what a call in
/// progress needs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.call"))]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum CallClientMsg {
  /// Drive the video handshake. `start` asks the peer to upgrade and holds our
  /// video until they agree; `accept` answers their request; `stop` withdraws
  /// video entirely.
  Video {
    action: CallVideoAction,
  },
  /// Turn our camera on or off inside a call that is already video. Ungated —
  /// no handshake is owed — and the correct frame right after `accept`.
  VideoEnabled {
    enabled: bool,
  },
  /// Our camera's rotation in clockwise quarter turns, 0..3.
  Orientation {
    orientation: i32,
  },
  /// Send an in-call reaction.
  Reaction {
    emoji: String,
  },
}
