// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::number1_200::Number1_200;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.call"))]
pub struct ConversationCallsQuery {
  /// Scrollback cursor: only calls with `id` strictly smaller are returned.
  pub before_id: Option<u64>,
  pub limit: Option<Number1_200>,
}
