// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Channel-tagged call placement — only whatsapp_native carries calls, so no
/// other channel's shape deserializes.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.call"))]
#[serde(tag = "channel")]
#[serde(rename_all = "snake_case")]
pub enum PlaceCallRequest {
  WhatsappNative {
    /// Start the call with video. An audio call can still be upgraded later,
    /// over the media socket.
    video: bool,
  },
}
