// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user_session"))]
pub struct UserSessionRow {
  pub uid: Uid,
  pub ip: Option<String>,
  pub user_agent: Option<String>,
  pub country: Option<String>,
  pub city: Option<String>,
  pub last_seen_at: Option<Timestamp>,
  pub expires_at: Timestamp,
  pub created_at: Timestamp,
  pub current: bool,
}
