// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;
use crate::types::types::user_mfa_kind::UserMfaKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.user_session"))]
#[serde(tag = "outcome")]
#[serde(rename_all = "snake_case")]
pub enum UserSessionLoginResponse {
  UserSession {
    token: Uid,
  },
  UserMfaRequired {
    mfa_token: Uid,
    factors: Vec<UserMfaKind>,
  },
  EnrollmentRequired {
    enrollment_token: Uid,
  },
}
