// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::user::create_user_request::CreateUserRequest;
use crate::types::user::create_user_response::CreateUserResponse;
use crate::types::user::set_user_super_admin_request::SetUserSuperAdminRequest;
use crate::types::user::update_user_request::UpdateUserRequest;
use crate::types::user::update_user_self_request::UpdateUserSelfRequest;
use crate::types::database::user::User;
use crate::types::user::user_change_password_request::UserChangePasswordRequest;
use crate::types::user::user_self_response::UserSelfResponse;

/// Reactivate another user, re-enabling their account.
///
/// Requires `ActivateUsers`, which only platform staff hold.
pub async fn activate(client: &Client, user_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/user/{user_uid}/activate");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Change the authenticated user's own password and revoke their other sessions.
///
/// Authenticated user acting on their own account.
pub async fn change_password(client: &Client, body: &UserChangePasswordRequest) -> ApiResult<()> {
  let mut __path = String::from("/user/me/password");
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Count all users.
///
/// Requires `ViewUsers`, which only platform staff hold.
pub async fn count(client: &Client) -> ApiResult<u64> {
  let mut __path = String::from("/user/count");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Create a user, who starts out belonging to no group.
///
/// Requires `ProvisionUsers`, which only platform staff hold.
pub async fn create(client: &Client, body: &CreateUserRequest) -> ApiResult<CreateUserResponse> {
  let mut __path = String::from("/user");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Deactivate another user, disabling their account while preserving sessions.
///
/// Requires `ActivateUsers`, which only platform staff hold; you cannot deactivate yourself.
pub async fn deactivate(client: &Client, user_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/user/{user_uid}/deactivate");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Delete another user.
///
/// Requires `DeleteUsers`, which only platform staff hold; you cannot delete yourself.
pub async fn delete(client: &Client, user_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/user/{user_uid}");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Get a single user by uid.
///
/// Requires `ViewUsers`, which only platform staff hold.
pub async fn get(client: &Client, user_uid: &str) -> ApiResult<User> {
  let mut __path = String::from("/user/{user_uid}");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Get the authenticated user's own account, along with the permissions and memberships every gating decision reads.
///
/// Authenticated user acting on their own account.
pub async fn get_self(client: &Client) -> ApiResult<UserSelfResponse> {
  let mut __path = String::from("/user/me");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// List all users.
///
/// Requires `ViewUsers`, which only platform staff hold.
pub async fn list(client: &Client) -> ApiResult<Vec<User>> {
  let mut __path = String::from("/user");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Grant or revoke another user's platform staff standing.
///
/// Requires `SetSuperAdmin`, which only platform staff hold; you can never change your own flag.
pub async fn set_super_admin(client: &Client, user_uid: &str, body: &SetUserSuperAdminRequest) -> ApiResult<()> {
  let mut __path = String::from("/user/{user_uid}/super-admin");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Update another user's profile.
///
/// Requires `UpdateUsers`, which only platform staff hold.
pub async fn update(client: &Client, user_uid: &str, body: &UpdateUserRequest) -> ApiResult<()> {
  let mut __path = String::from("/user/{user_uid}");
  __path = __path.replace("{user_uid}", &encode_path(user_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Update the authenticated user's own profile.
///
/// Authenticated user acting on their own account.
pub async fn update_self(client: &Client, body: &UpdateUserSelfRequest) -> ApiResult<()> {
  let mut __path = String::from("/user/me");
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
