// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::google::answer::Answer;
use crate::types::google_account::answer_business_question_request::AnswerBusinessQuestionRequest;
use crate::types::google::business_account_page::BusinessAccountPage;
use crate::types::google_account::business_calls_query::BusinessCallsQuery;
use crate::types::google_account::business_keywords_query::BusinessKeywordsQuery;
use crate::types::google_account::business_menus_query::BusinessMenusQuery;
use crate::types::google_account::business_performance_query::BusinessPerformanceQuery;
use crate::types::google_account::business_performance_response::BusinessPerformanceResponse;
use crate::types::google::call_insights_page::CallInsightsPage;
use crate::types::google_account::create_business_media_request::CreateBusinessMediaRequest;
use crate::types::google_account::create_business_post_request::CreateBusinessPostRequest;
use crate::types::google_account::delete_business_answer_query::DeleteBusinessAnswerQuery;
use crate::types::google_account::delete_business_media_query::DeleteBusinessMediaQuery;
use crate::types::google_account::delete_business_post_query::DeleteBusinessPostQuery;
use crate::types::google_account::delete_business_reply_query::DeleteBusinessReplyQuery;
use crate::types::google::food_menus::FoodMenus;
use crate::types::google_account::list_business_accounts_query::ListBusinessAccountsQuery;
use crate::types::google_account::list_business_locations_query::ListBusinessLocationsQuery;
use crate::types::google_account::list_business_media_query::ListBusinessMediaQuery;
use crate::types::google_account::list_business_posts_query::ListBusinessPostsQuery;
use crate::types::google_account::list_business_questions_query::ListBusinessQuestionsQuery;
use crate::types::google_account::list_business_reviews_query::ListBusinessReviewsQuery;
use crate::types::google::local_post::LocalPost;
use crate::types::google::local_post_page::LocalPostPage;
use crate::types::google::location::Location;
use crate::types::google::location_page::LocationPage;
use crate::types::google::media_item::MediaItem;
use crate::types::google::media_page::MediaPage;
use crate::types::google::question_page::QuestionPage;
use crate::types::google_account::reply_business_review_request::ReplyBusinessReviewRequest;
use crate::types::google::review_page::ReviewPage;
use crate::types::google::review_reply::ReviewReply;
use crate::types::google::search_keyword_page::SearchKeywordPage;
use crate::types::google_account::update_business_location_request::UpdateBusinessLocationRequest;
use crate::types::google_account::update_business_menus_request::UpdateBusinessMenusRequest;
use crate::types::google_account::update_business_post_request::UpdateBusinessPostRequest;

/// Create or replace the business's answer on a question (one per account —
/// answering again overwrites).
///
/// Requires `ManageBusiness` in the account's group.
pub async fn answer_question(__client: &crate::runtime::Client, social_account_uid: &str, __body: &AnswerBusinessQuestionRequest) -> crate::runtime::ApiResult<Answer> {
  let mut __path = String::from("/business/{social_account_uid}/question/answer");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Call History insights for a location (answered/missed counts, hourly and
/// weekday breakdowns) — populated only where the merchant enabled Call
/// History.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn calls(__client: &crate::runtime::Client, social_account_uid: &str, __query: &BusinessCallsQuery) -> crate::runtime::ApiResult<CallInsightsPage> {
  let mut __path = String::from("/business/{social_account_uid}/call");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Attach a photo/video to the profile from a publicly fetchable URL, placed
/// under the chosen category (`COVER`, `LOGO`, `INTERIOR`, `ADDITIONAL`, …).
///
/// Requires `ManageBusiness` in the account's group.
pub async fn create_media(__client: &crate::runtime::Client, social_account_uid: &str, __body: &CreateBusinessMediaRequest) -> crate::runtime::ApiResult<MediaItem> {
  let mut __path = String::from("/business/{social_account_uid}/media");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Publish a local post on a location — `STANDARD`, `EVENT`, `OFFER` or
/// `ALERT`, optionally with a call-to-action button and photos (public URLs).
///
/// Requires `ManageBusiness` in the account's group.
pub async fn create_post(__client: &crate::runtime::Client, social_account_uid: &str, __body: &CreateBusinessPostRequest) -> crate::runtime::ApiResult<LocalPost> {
  let mut __path = String::from("/business/{social_account_uid}/post");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Remove the business's answer from a question.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn delete_answer(__client: &crate::runtime::Client, social_account_uid: &str, __query: &DeleteBusinessAnswerQuery) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/business/{social_account_uid}/question/answer");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, Some(__query), None::<&()>).await
}
/// Remove a media item from the profile.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn delete_media(__client: &crate::runtime::Client, social_account_uid: &str, __query: &DeleteBusinessMediaQuery) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/business/{social_account_uid}/media");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, Some(__query), None::<&()>).await
}
/// Delete a local post.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn delete_post(__client: &crate::runtime::Client, social_account_uid: &str, __query: &DeleteBusinessPostQuery) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/business/{social_account_uid}/post");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, Some(__query), None::<&()>).await
}
/// Remove the merchant reply from a review.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn delete_review_reply(__client: &crate::runtime::Client, social_account_uid: &str, __query: &DeleteBusinessReplyQuery) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/business/{social_account_uid}/review/reply");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::DELETE, &__path, Some(__query), None::<&()>).await
}
/// The location's structured food menus (food businesses only —
/// `metadata.can_have_food_menus` on the location says whether it applies).
///
/// Requires `ViewBusiness` in the account's group.
pub async fn get_menus(__client: &crate::runtime::Client, social_account_uid: &str, __query: &BusinessMenusQuery) -> crate::runtime::ApiResult<FoodMenus> {
  let mut __path = String::from("/business/{social_account_uid}/menu");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Monthly search keywords that surfaced the profile, by impression volume.
/// Low-volume keywords report a threshold floor instead of an exact value.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn keywords(__client: &crate::runtime::Client, social_account_uid: &str, __query: &BusinessKeywordsQuery) -> crate::runtime::ApiResult<SearchKeywordPage> {
  let mut __path = String::from("/business/{social_account_uid}/keyword");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List the Business Profile accounts the connected Google user manages —
/// the roots the other business endpoints' resource names hang under.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn list_accounts(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListBusinessAccountsQuery) -> crate::runtime::ApiResult<BusinessAccountPage> {
  let mut __path = String::from("/business/{social_account_uid}/account");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List an account's business locations with their info (title, address,
/// phones, hours, categories, status, links).
///
/// Requires `ViewBusiness` in the account's group.
pub async fn list_locations(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListBusinessLocationsQuery) -> crate::runtime::ApiResult<LocationPage> {
  let mut __path = String::from("/business/{social_account_uid}/location");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List a location's profile media (photos/videos) with view counts.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn list_media(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListBusinessMediaQuery) -> crate::runtime::ApiResult<MediaPage> {
  let mut __path = String::from("/business/{social_account_uid}/media");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List a location's local posts, newest first.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn list_posts(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListBusinessPostsQuery) -> crate::runtime::ApiResult<LocalPostPage> {
  let mut __path = String::from("/business/{social_account_uid}/post");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List the questions customers asked on a location, each with its top
/// answers.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn list_questions(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListBusinessQuestionsQuery) -> crate::runtime::ApiResult<QuestionPage> {
  let mut __path = String::from("/business/{social_account_uid}/question");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// List a location's reviews (newest update first by default), with the
/// running average and total.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn list_reviews(__client: &crate::runtime::Client, social_account_uid: &str, __query: &ListBusinessReviewsQuery) -> crate::runtime::ApiResult<ReviewPage> {
  let mut __path = String::from("/business/{social_account_uid}/review");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Daily performance series for a location — impressions by surface,
/// conversations, direction requests, call and website clicks — over an
/// inclusive date range.
///
/// Requires `ViewBusiness` in the account's group.
pub async fn performance(__client: &crate::runtime::Client, social_account_uid: &str, __query: &BusinessPerformanceQuery) -> crate::runtime::ApiResult<BusinessPerformanceResponse> {
  let mut __path = String::from("/business/{social_account_uid}/performance");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
/// Create or replace the public merchant reply on a review.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn reply_review(__client: &crate::runtime::Client, social_account_uid: &str, __body: &ReplyBusinessReviewRequest) -> crate::runtime::ApiResult<ReviewReply> {
  let mut __path = String::from("/business/{social_account_uid}/review/reply");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Update a location's business info: exactly the masked fields are written.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn update_location(__client: &crate::runtime::Client, social_account_uid: &str, __body: &UpdateBusinessLocationRequest) -> crate::runtime::ApiResult<Location> {
  let mut __path = String::from("/business/{social_account_uid}/location");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PATCH, &__path, None::<&()>, Some(__body)).await
}
/// Replace the location's food menus wholesale.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn update_menus(__client: &crate::runtime::Client, social_account_uid: &str, __body: &UpdateBusinessMenusRequest) -> crate::runtime::ApiResult<FoodMenus> {
  let mut __path = String::from("/business/{social_account_uid}/menu");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
/// Update a local post: exactly the masked fields are written.
///
/// Requires `ManageBusiness` in the account's group.
pub async fn update_post(__client: &crate::runtime::Client, social_account_uid: &str, __body: &UpdateBusinessPostRequest) -> crate::runtime::ApiResult<LocalPost> {
  let mut __path = String::from("/business/{social_account_uid}/post");
  __path = __path.replace("{social_account_uid}", &crate::runtime::encode_path(social_account_uid));
  __client.request(crate::runtime::Method::PATCH, &__path, None::<&()>, Some(__body)).await
}
