// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::message::backfill_request::BackfillRequest;
use crate::types::message::backfill_response::BackfillResponse;
use crate::types::message::edit_message_request::EditMessageRequest;
use crate::types::message::list_messages_query::ListMessagesQuery;
use crate::types::database::message::Message;
use crate::types::message::message_with_context::MessageWithContext;
use crate::types::message::react_to_message_request::ReactToMessageRequest;
use crate::types::message::send_message_request::SendMessageRequest;
use crate::types::primitives::uid::Uid;

/// Import conversation history from Meta's Conversations API for an account
/// — DMs that predate the account's connection (facebook/instagram only;
/// whatsapp exposes no history). Runs only when explicitly invoked;
/// already-imported messages dedup by platform mid.
///
/// Requires `ManageMessages` in the account's group.
pub async fn backfill(client: &Client, body: &BackfillRequest) -> ApiResult<BackfillResponse> {
  let mut __path = String::from("/message/backfill");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Cancel a queued (`pending`) message before it reaches the platform, and
/// with it **every message queued after it in the same conversation** —
/// cancels cascade forward because a conversation's queued messages are one
/// ordered thought: dropping one mid-sequence would deliver the rest out of
/// context. Given messages 1, 2 and 3 queued in one conversation, canceling 2
/// also cancels 3, and canceling 1 cancels 1, 2 and 3. Messages queued for
/// *other* conversations on the same account are never touched and keep
/// sending.
///
/// Only a message still waiting in the queue can be canceled: once it has been
/// handed to the platform there is nothing left to stop, and the call fails
/// with "mensagem não está na fila de envio". Every send passes through
/// `pending`, but without a pacing rule on the channel the queue drains
/// immediately — the window to cancel is real only while a rule holds sends
/// back.
///
/// Returns the canceled message uids in send order, the named message first.
/// Each also emits a `message_canceled` event (`cascaded` false for the named
/// one, true for the messages that went with it).
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn cancel(client: &Client, conversation_uid: &str, message_uid: &str) -> ApiResult<Vec<Uid>> {
  let mut __path = String::from("/conversation/{conversation_uid}/message/{message_uid}/cancel");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  __path = __path.replace("{message_uid}", &encode_path(message_uid));
  client.request(Method::POST, &__path, None::<&()>, None::<&()>).await
}
/// Revoke an own sent message for everyone ("apagar para todos") —
/// whatsapp_stevo and whatsapp_native only; the row stays with `deleted_at`
/// set.
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn delete(client: &Client, conversation_uid: &str, message_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}/message/{message_uid}");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  __path = __path.replace("{message_uid}", &encode_path(message_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Edit an own sent message's text (or media caption) on the platform —
/// whatsapp_stevo and whatsapp_native only; the platform enforces its
/// ~15 minute edit window.
///
/// Requires `ManageMessages` in the conversation's group.
pub async fn edit(client: &Client, conversation_uid: &str, message_uid: &str, body: &EditMessageRequest) -> ApiResult<Message> {
  let mut __path = String::from("/conversation/{conversation_uid}/message/{message_uid}");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  __path = __path.replace("{message_uid}", &encode_path(message_uid));
  client.request(Method::PUT, &__path, None::<&()>, Some(body)).await
}
/// Poll the unified message feed across channels: messages with `id` greater
/// than `since_id`, oldest first, optionally filtered by group or account.
///
/// Requires `ViewMessages`; the feed covers only messages of groups where the caller holds it.
pub async fn list(client: &Client, query: &ListMessagesQuery) -> ApiResult<Vec<MessageWithContext>> {
  let mut __path = String::from("/message");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// React to a message through the platform. The payload is channel-tagged
/// and must match the message's channel; Messenger has no reaction API and
/// no payload variant.
///
/// Requires `SendMessages` in the conversation's group.
pub async fn react(client: &Client, conversation_uid: &str, message_uid: &str, body: &ReactToMessageRequest) -> ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}/message/{message_uid}/reaction");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  __path = __path.replace("{message_uid}", &encode_path(message_uid));
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Send a message into a conversation. The payload is channel-tagged and
/// must match the conversation's channel — each variant accepts exactly the
/// fields and content kinds its channel can deliver. Official WhatsApp
/// free-form sends require an inbound message within 24h; outside the window
/// only `template` content passes (the unofficial flavors have no window).
///
/// Sends are always queued: the message comes back as `pending`, nothing has
/// reached the platform yet, and a `message_queued` event fires. A per-account
/// drainer dispatches it in order — immediately, or spaced by the channel's
/// send-pacing rule when one exists — and only then does it become `sent`
/// (`message_sent`) or `failed` (`message_failed`). A pending message can be
/// called off with `message.cancel` until it goes out.
///
/// An `idempotency_key` makes the send retry-safe: the same key never
/// duplicates history — a failed row is re-queued in place (same `uid`,
/// re-announced via `message_queued`), any other row is returned as-is
/// without a new send.
///
/// Requires `SendMessages` in the conversation's group.
pub async fn send(client: &Client, body: &SendMessageRequest) -> ApiResult<MessageWithContext> {
  let mut __path = String::from("/message");
  client.request(Method::POST, &__path, None::<&()>, Some(body)).await
}
/// Remove the account's reaction from a message (Instagram and the WhatsApp
/// flavors — Messenger has no reaction API).
///
/// Requires `SendMessages` in the conversation's group.
pub async fn unreact(client: &Client, conversation_uid: &str, message_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/conversation/{conversation_uid}/message/{message_uid}/reaction");
  __path = __path.replace("{conversation_uid}", &encode_path(conversation_uid));
  __path = __path.replace("{message_uid}", &encode_path(message_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
