// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::oauth_server::approve_request::ApproveRequest;
use crate::types::oauth_server::approve_response::ApproveResponse;
use crate::types::oauth_server::consent_query::ConsentQuery;
use crate::types::oauth_server::consent_response::ConsentResponse;

/// Grant the OAuth client access as the calling user: mint the authorization code (valid 2 minutes, single use) and answer the redirect that delivers it.
///
/// Authenticated user acting on their own behalf; no permission required. Only a session may approve: an API key or an OAuth token cannot mint grants.
pub async fn approve(__client: &crate::runtime::Client, __body: &ApproveRequest) -> crate::runtime::ApiResult<ApproveResponse> {
  let mut __path = String::from("/oauth/approve");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Describe the OAuth client asking for access, for the consent page, after checking that the request is one this server would honour: registered client, a matching redirect uri, `response_type` code, PKCE `S256`, and a `resource` naming this server's MCP endpoint. A redirect uri matches its registered form exactly, except that a registered loopback http uri (`http://localhost`, `http://127.0.0.1`) matches on scheme, host and path with any port, as RFC 8252 §7.3 asks for native apps. The request is read leniently where there is only one answer: an absent `code_challenge_method` means `S256` (the only method this server supports) and an absent `resource` means this server's MCP endpoint, which is what the code is bound to either way.
///
/// Authenticated user acting on their own behalf; no permission required. Only a session may ask: an API key or an OAuth token cannot reach the consent step.
pub async fn consent(__client: &crate::runtime::Client, __query: &ConsentQuery) -> crate::runtime::ApiResult<ConsentResponse> {
  let mut __path = String::from("/oauth/consent");
  __client.request(crate::runtime::Method::GET, &__path, Some(__query), None::<&()>).await
}
