// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::event::resume_cursor::ResumeCursor;
use crate::types::event::roster_filter::RosterFilter;
use crate::types::primitives::uid::Uid;

/// Client → server protocol frames.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum ClientMsg {
  /// The first frame. `resume` replays everything after the cursor of a
  /// previous connection when still possible; `roster` is the connection's
  /// base subscription (omit for everything visible to the caller).
  Hello {
    resume: Option<ResumeCursor>,
    roster: Option<RosterFilter>,
  },
  /// Replace the base subscription.
  SetRoster {
    roster: RosterFilter,
  },
  /// Replace the focused-conversation set: raw events for these
  /// conversations flow regardless of the roster's kind filter (the open
  /// threads of the UI). Capped at 32.
  SetFocus {
    conversation_uids: Vec<Uid>,
  },
}
