// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::types::channel::Channel;
use crate::types::database::comment::Comment;
use crate::types::database::conversation::Conversation;
use crate::types::database::mention::Mention;
use crate::types::database::message::Message;
use crate::types::database::post::Post;
use crate::types::event::presence_state::PresenceState;
use crate::types::event::reaction_action::ReactionAction;
use crate::types::google::review::Review;
use crate::types::database::social_account::SocialAccount;
use crate::types::primitives::timestamp::Timestamp;
use crate::types::primitives::uid::Uid;

/// Every event the hub emits, in the exact shape delivered to its outbound
/// transports: the group webhook (as the POST body) and the WebSocket stream
/// (as one frame). The `event` tag names the kind. Transient kinds
/// (`is_transient`) reach the socket only — they never enter the replay ring
/// the webhook batcher reads.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
#[serde(tag = "event")]
#[serde(rename_all = "snake_case")]
pub enum HubEvent {
  /// An inbound message was stored.
  MessageReceived {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message: Message,
  },
  /// An outbound message row was stored: a hub send (any status, including
  /// an immediate failure) or an echo of a send made from another surface
  /// (the paired phone, the Meta business inbox).
  MessageSent {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message: Message,
  },
  /// An outbound message entered the paced send queue (`pending`): the
  /// channel carries a pacing rule, so the send waits its turn instead of
  /// going out immediately. A `message_sent` (or `message_failed`) for the
  /// same message follows when the queue drains it — unless it is canceled
  /// first.
  MessageQueued {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message: Message,
  },
  /// A queued message was canceled before the platform ever saw it — either
  /// canceled directly, or by cascade because an earlier pending message in
  /// the same conversation was canceled. Terminal; nothing was sent.
  MessageCanceled {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message_uid: Uid,
    cascaded: bool,
  },
  MessageReaction {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message_uid: Uid,
    reactor_id: String,
    action: ReactionAction,
    reaction: Option<String>,
    emoji: Option<String>,
  },
  /// Outbound messages in the conversation sent up to `watermark` (ms) were
  /// delivered. WhatsApp receipts are per-message: `message_uid` names the
  /// exact message (facebook/instagram send watermarks only).
  MessageDelivered {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    watermark: i64,
    message_uid: Option<Uid>,
  },
  /// Outbound messages in the conversation sent up to `watermark` (ms) were
  /// read. WhatsApp receipts are per-message: `message_uid` names the exact
  /// message (facebook/instagram send watermarks only).
  MessageRead {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    watermark: i64,
    message_uid: Option<Uid>,
  },
  /// An accepted outbound message later failed delivery (whatsapp: policy
  /// rejections like a closed 24h window arrive asynchronously).
  MessageFailed {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message_uid: Uid,
    error: String,
  },
  /// The participant edited their message; `message` carries the rewritten
  /// content and `edited_at`.
  MessageUpdated {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message: Message,
  },
  /// The participant revoked their message; the row stays with `deleted_at`
  /// set.
  MessageDeleted {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    message_uid: Uid,
  },
  /// Transient: the participant is typing/recording. Never persisted;
  /// push-only by nature.
  ParticipantPresence {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    state: PresenceState,
  },
  CommentReceived {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    comment: Comment,
  },
  CommentUpdated {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    comment: Comment,
  },
  CommentDeleted {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    comment_uid: Uid,
    external_id: String,
  },
  MentionReceived {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    mention: Mention,
  },
  PostPublished {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    post: Post,
  },
  PostFailed {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    post: Post,
  },
  /// The conversation's denormalized chat-list summary changed (new message,
  /// receipt, unread/read change, profile, typing) — coalesced to at most
  /// one per conversation per debounce window. `conversation` is the full
  /// row, ready to upsert into a roster; `typing` is a transient overlay,
  /// not storage.
  ConversationUpdated {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation: Conversation,
    typing: bool,
  },
  /// The conversation's stored history was erased on the hub; the
  /// conversation itself stays (an emptied thread, unread badge cleared).
  /// Consumers drop every message they hold under it. A
  /// `conversation_updated` with the emptied summary follows.
  ConversationCleared {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
  },
  /// The conversation was deleted on the hub, history and all — rosters drop
  /// the row. Nothing was deleted on the platform.
  ConversationRemoved {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
  },
  /// Transient: the contact's device came online / went offline (native
  /// channel only — the platform demands a per-contact subscription, which
  /// focusing a conversation establishes). `last_seen_at` is absent when the
  /// contact hides it.
  ContactPresence {
    group_uid: Uid,
    channel: Channel,
    social_account_uid: Uid,
    conversation_uid: Uid,
    online: bool,
    last_seen_at: Option<Timestamp>,
  },
  /// An account (any provider) was connected, reconfigured, enabled,
  /// disabled, or flagged for reauthorization.
  AccountUpdated {
    group_uid: Uid,
    account: SocialAccount,
  },
  /// An account was removed — for messaging providers its conversations are
  /// gone; rosters drop every row under it.
  AccountRemoved {
    group_uid: Uid,
    social_account_uid: Uid,
  },
  /// The business review sweep found a new (or edited — Google bumps the
  /// review's update time on edits) review on one of the account's
  /// locations.
  ReviewReceived {
    group_uid: Uid,
    social_account_uid: Uid,
    location_name: String,
    location_title: String,
    review: Review,
  },
}
