// This file was generated by tapir. Do not edit this file manually.
pub mod client_msg;
pub mod get_webhook_query;
pub mod resume_cursor;
pub mod roster_filter;
pub mod server_msg;
pub mod set_webhook_request;
pub mod set_webhook_response;
