// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Whether a reaction was added or taken back. Platforms report both through
/// one event; the emoji is present only on a `react`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
#[serde(rename_all = "snake_case")]
pub enum ReactionAction {
  React,
  Unreact,
}
