// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]

/// Where a previous connection stopped: the `epoch` from its `welcome` and
/// the `seq` of the last processed `event` frame.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
pub struct ResumeCursor {
  pub epoch: String,
  pub seq: u64,
}
