// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::hub_event::HubEvent;

/// Server → client protocol frames.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
#[serde(tag = "type")]
#[serde(rename_all = "snake_case")]
pub enum ServerMsg {
  /// Handshake result: the stream identity resume cursors pair with.
  /// `resumed` reports whether the requested cursor was replayed; when it is
  /// false after a resume request, a `gap` frame follows.
  Welcome {
    epoch: String,
    seq: u64,
    resumed: bool,
  },
  /// One event; `seq` is the resume cursor after processing it.
  Event {
    seq: u64,
    event: HubEvent,
  },
  /// Events were missed and cannot be replayed (hub restart, cursor fell off
  /// the window, or this consumer lagged): re-hydrate the viewport from REST
  /// — storage is the source of truth — then keep consuming.
  Gap {
    reason: String,
  },
  /// A frame was rejected; the connection and its subscription are unchanged.
  Error {
    message: String,
  },
  /// Keepalive, every 30 seconds; nothing to answer. A client that hears no
  /// frame at all for a few intervals should reconnect: a socket can die
  /// without a close ever arriving.
  Ping,
  /// The server is closing the connection (auth loss).
  Shutdown {
    reason: String,
  },
}
