// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::domain::channel::Channel;
use crate::types::domain::event_kind::EventKind;
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
pub struct SetWebhookRequest {
  /// Required for users and platform keys; group-bound keys imply their group.
  pub group_uid: Option<Uid>,
  pub url: String,
  /// Event kinds delivered to this subscription; omit for everything. The
  /// live-only kinds (the presence kinds), which reach only the event socket,
  /// are refused here.
  pub events: Option<Vec<EventKind>>,
  /// Channels delivered to this subscription; omit for everything.
  pub channels: Option<Vec<Channel>>,
}
