// This file was generated by tapir. Do not edit this file manually.
#![allow(unused_imports, non_snake_case, non_camel_case_types, clippy::all)]
use crate::types::primitives::uid::Uid;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[cfg_attr(feature = "tapir", derive(tapir::Reflect), tapir(namespace = "integro_sdk.event"))]
pub struct SetWebhookResponse {
  pub uid: Uid,
  /// HMAC secret for `X-Integro-Signature` — shown only here; rotated on every
  /// reconfiguration.
  pub secret: String,
}
