// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::user::set_user_account_notification_request::SetUserAccountNotificationRequest;
use crate::types::domain::user_account_notification::UserAccountNotification;

/// List the caller's own notification choices per social account. An account without an entry rings both the message sound and the call alert.
///
/// Authenticated user acting on their own account.
pub async fn list(__client: &crate::runtime::Client) -> crate::runtime::ApiResult<Vec<UserAccountNotification>> {
  let mut __path = String::from("/user/me/account-notification");
  __client.request(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Change the caller's own notification choices on the listed social accounts; a `null` choice stays as it is. Personal to the caller: colleagues on the same accounts keep their own.
///
/// Authenticated user acting on their own account; every listed account must sit in a group where they hold `ViewMessages`.
pub async fn set(__client: &crate::runtime::Client, __body: &SetUserAccountNotificationRequest) -> crate::runtime::ApiResult<()> {
  let mut __path = String::from("/user/me/account-notification");
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, Some(__body)).await
}
