// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::media::upload_media_form::UploadMediaForm;
use crate::types::media::upload_media_response::UploadMediaResponse;

/// Delete a hub-hosted media file. The uid may carry the same cosmetic
/// extension suffix the serve route accepts, so the URL handed back by upload
/// can be deleted verbatim. Platform posts/messages already published with it
/// keep working (Meta copies media on ingestion), but new sends referencing
/// the URL will fail.
///
/// Requires `DeleteMedia` in the media's group.
pub async fn delete(client: &Client, media_uid: &str) -> ApiResult<()> {
  let mut __path = String::from("/media/{media_uid}");
  __path = __path.replace("{media_uid}", &encode_path(media_uid));
  client.request(Method::DELETE, &__path, None::<&()>, None::<&()>).await
}
/// Serve a hub-hosted media file. The uid may carry a cosmetic extension
/// suffix (`{uid}.m4a`) — generated URLs include one as a format signal for
/// external fetchers; it is stripped before lookup.
///
/// Public — no authentication required; the unguessable uid is the capability.
pub async fn serve(client: &Client, media_uid: &str) -> ApiResult<Vec<u8>> {
  let mut __path = String::from("/media/{media_uid}");
  __path = __path.replace("{media_uid}", &encode_path(media_uid));
  client.request_bytes(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Upload a media file to the hub; the returned public URL can be used in any
/// message or post payload (Meta fetches it from the hub).
///
/// Requires `UploadMedia` in the target group; group-scoped API keys upload into their own group, others must name it.
pub async fn upload(client: &Client, form: reqwest::multipart::Form) -> ApiResult<UploadMediaResponse> {
  let mut __path = String::from("/media");
  client.request_multipart(Method::POST, &__path, None::<&()>, form).await
}
