// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::types::media::create_upload_url_request::CreateUploadUrlRequest;
use crate::types::media::create_upload_url_response::CreateUploadUrlResponse;
use crate::types::media::upload_media_form::UploadMediaForm;
use crate::types::media::upload_media_response::UploadMediaResponse;

/// Issue a single-use URL that accepts one file's raw bytes over `PUT`, so a
/// client holding only bytes can put them in the hub without a multipart
/// form. The URL carries its own unguessable token, needs no credential, and
/// expires 15 minutes after this call; the first upload consumes it whether
/// or not the bytes are accepted, and the upload answers with the stored
/// media and its public URL.
///
/// Requires `UploadMedia` in the target group; group-scoped API keys upload into their own group, others must name it. A human caller is additionally rejected when they trip the per-user file-upload throttle.
pub async fn create_upload_url(__client: &crate::runtime::Client, __body: &CreateUploadUrlRequest) -> crate::runtime::ApiResult<CreateUploadUrlResponse> {
  let mut __path = String::from("/media/upload-ticket");
  __client.request(crate::runtime::Method::POST, &__path, None::<&()>, Some(__body)).await
}
/// Serve a hub-hosted media file. The uid may carry a cosmetic extension
/// suffix (`{uid}.m4a`) — generated URLs include one as a format signal for
/// external fetchers; it is stripped before lookup. A uid nothing names any
/// more answers 404: the file went with its last referrer.
///
/// Public — no authentication required; the unguessable uid is the capability.
pub async fn serve(__client: &crate::runtime::Client, media_uid: &str) -> crate::runtime::ApiResult<Vec<u8>> {
  let mut __path = String::from("/media/{media_uid}");
  __path = __path.replace("{media_uid}", &crate::runtime::encode_path(media_uid));
  __client.request_bytes(crate::runtime::Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Upload a media file to the hub; the returned public URL can be used in any
/// message or post payload (Meta fetches it from the hub). Bytes the hub
/// already holds come back as the existing file — same uid, same URL. The
/// URL stays valid while a message, post or campaign template names it, and
/// for 24 hours after this upload otherwise; a third party handed the URL
/// copies what it needs while it resolves.
///
/// Requires `UploadMedia` in the target group; group-scoped API keys upload into their own group, others must name it. A human caller is additionally rejected when they trip the per-user file-upload throttle.
pub async fn upload(__client: &crate::runtime::Client, __form: reqwest::multipart::Form) -> crate::runtime::ApiResult<UploadMediaResponse> {
  let mut __path = String::from("/media");
  __client.request_multipart(crate::runtime::Method::POST, &__path, None::<&()>, __form).await
}
/// Store the file an upload ticket was issued for: the raw bytes are the whole
/// request body, the request `content-type` is a type hint the bytes
/// themselves override, and the ticket supplies the filename. The ticket is
/// consumed by this call whether or not the bytes are accepted — an empty
/// body, or one past 100 MiB, is refused and the client asks for a new
/// ticket. The reply is the stored media, whose public URL can be used in any
/// message or post payload.
///
/// Public — no authentication; the unguessable ticket token is the capability, issued by `media.createUploadUrl` and valid for 15 minutes.
pub async fn upload_with_ticket(__client: &crate::runtime::Client, token: &str) -> crate::runtime::ApiResult<UploadMediaResponse> {
  let mut __path = String::from("/media/upload/{token}");
  __path = __path.replace("{token}", &crate::runtime::encode_path(token));
  __client.request(crate::runtime::Method::PUT, &__path, None::<&()>, None::<&()>).await
}
