// This file was generated by tapi. Do not edit this file manually.
#![allow(unused_imports, unused_mut, clippy::all)]
use crate::runtime::{Client, Method, ApiResult, WsConnection, WsHandlers, encode_path};
use crate::types::database::server_uptime::ServerUptime;
use crate::types::uptime::server_uptime_range_query::ServerUptimeRangeQuery;
use crate::types::database::server_uptime_stats::ServerUptimeStats;

/// Get the most recent server uptime record.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn get_latest(client: &Client) -> ApiResult<Option<ServerUptime>> {
  let mut __path = String::from("/uptime/latest");
  client.request(Method::GET, &__path, None::<&()>, None::<&()>).await
}
/// Compute aggregate server uptime statistics within a time range.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn get_stats(client: &Client, query: &ServerUptimeRangeQuery) -> ApiResult<ServerUptimeStats> {
  let mut __path = String::from("/uptime/stats");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
/// List server uptime records within a time range.
///
/// Requires `ViewPulse`, which only platform staff hold.
pub async fn list(client: &Client, query: &ServerUptimeRangeQuery) -> ApiResult<Vec<ServerUptime>> {
  let mut __path = String::from("/uptime");
  client.request(Method::GET, &__path, Some(query), None::<&()>).await
}
